# TIPOS DE DADOS#

## NUMÉRICOS##

#### TIPOS INTEIROS:

* Int8 — inteiros 8-bit com sinal variando de - $2^7 ~~a~~ 2^7 - 1$.
* Int8 — inteiros 8-bit sem sinal variando de $0 ~~a~~ 2^8 - 1$.
* Int16 — inteiros 16-bit com sinal variando de $-2^{15}~~ a ~~ 2^{15} - 1$.
* Int16 — inteiros 16-bit sem sinal variando de $0~~ a ~~2^{16} - 1$.
* Int32 — inteiros 32-bit com sinal variando de $-2^{31} ~~a~~ 2^{31} - 1$.
* Int32 — inteiros 32-bit sem sinal variando de $0~~ a~~ 2^{32} - 1$.
* Int64 — inteiros 64-bit com sinal variando de $-2^{63} ~~a~~ 2^{63} - 1$.
* Int64 — inteiros 64-bit sem sinal variando de $0 ~~a~~ 2^{64} - 1$.
* Int128 — inteiros 128-bit com sinal variando de $-2^{127}~~ a~~ 2^{127} - 1$.
* Int128 — inteiros 128-bit sem sinal variando de $0~~ a~~ 2^{128} - 1$.
* Bool — valendo ou true (verdadeiro) ou false (falso), que correspondem numericamente a 1 ou 0, respectivamente.
* Char — um tipo numérico de 32 bits representando um caracter Unicode (veja Strings para mais detalhes).

#### TIPOS PONTO FLUTUANTE:

* Float32 — Números de ponto flutuante 32-bit seguindo o padrão IEEE 754.
* Float64 — Números de ponto flutuante 64-bit seguindo o padrão IEEE 754.

#### NUMEROS COMPLEXOS 

Para definir, usa-se a parte real em conjunto com a parte imaginária **im**

In [10]:
1 + 2im

1 + 2im

In [11]:
(1 + 8im) + (2 - 3im)

3 + 5im

In [12]:
(1 + 8im) * (2 - 3im)

26 + 13im

In [13]:
(26 + 13im)^2

507 + 676im

In [14]:
real(1 + 2im)

1

In [15]:
imag(1 + 2im)

2

In [16]:
conj(1 + 2im)

1 - 2im

In [17]:
abs(1 + 2im)

2.23606797749979

## CONSTANTES

In [18]:
pi, e, golden

(π = 3.1415926535897...,e = 2.7182818284590...,φ = 1.6180339887498...)

<strong>Declarando uma constante</strong><br>
Constantes, declarado como <strong>const</strong>, são variáveis imutáveis quanto ao tipo. Ou seja, podem mudar de valor (será dado um aviso) mas não podem mudar de tipo.


In [19]:
# variável "vel_luz" do tipo string

const vel_luz = "299792458"

"299792458"

In [20]:
# Alterando a variável para outro valor do mesmo tipo string. Será dado um aviso

const vel_luz = "30000000"

"30000000"

In [21]:
# Não é possível alterar o tipo da variável "vel_luz" para inteiro. Ocorrerá ero

const vel_luz = 30000000

LoadError: LoadError: invalid redefinition of constant vel_luz
while loading In[21], in expression starting on line 3

In [22]:
vel_luz

"30000000"

In [23]:
# saber o tipo da constante

typeof(vel_luz)

ASCIIString

## VARIÁVEIS

* ** Resetar todas as variáveis**

Julia não reseta, de fato, as variáveis. Na verdade ele configura outro workspace.

In [24]:
workspace()

* **Trabalhando com variáveis**

In [36]:
# Atribindo o valor 2 a variavel x

x = 2

2

In [26]:
# Executando o calculo

x^2

4

In [27]:
# Variável literal

y = "so testando";

In [28]:
y

"so testando"

In [29]:
# Ao tentar utilizar uma variável nao declarada, ocorre um erro "Xvar not defined"

Xvar

LoadError: LoadError: UndefVarError: Xvar not defined
while loading In[29], in expression starting on line 3

In [30]:
# verificar o tipo da variável

typeof(x),typeof(y)

(Int64,ASCIIString)

In [31]:
# testar tipo

isa(x, Int64)

true

In [32]:
# construção de um complexo 

a = 2
b = 3.5

complex(a,b)

2.0 + 3.5im

* **Declarando  Várias variáveis ao mesmo tempo **

In [33]:
# Declarando Várias variáveis

x = 5 
y = 10 
z = "julia";

In [34]:
x,y,z

(5,10,"julia")

In [35]:
# Por padrão, será impresso somente a ultima linha, mas as variáveis internas estão acessíveis

w = begin
    x = 2
    y = 3
    x+y
    
end

5

In [36]:
# y do bloco de w

y

3

In [37]:
# outra forma. Por padrão, será impresso somente a ultima linha, mas as variáveis internas estão acessíveis

w = (x = 2; y = 3; x + y)

w

5

* ** Variáveis criadas ** 

In [38]:
whos()

                          Base  24768 KB     Module
                          Core   3194 KB     Module
                      LastMain  25563 KB     Module


* **Macro @printf**

In [29]:
x = 10.0

@printf("valor de x é %f",x)

valor de x é 10.000000

## STRING

** Convertendo uma string em uma expressão matemática **

In [39]:
string_formula = "x^2 + 1"

y = parse(string_formula)

:(x ^ 2 + 1)

In [40]:
typeof(y)

Expr

In [41]:
x = 0

eval(y)

1

## CONVERSÃO DE TIPOS

<div style="text-align: justify;">Tabela de Tipos<br>
</div>
<table style="text-align: left; width: 271px; height: 304px;" border="1"
cellpadding="2" cellspacing="2">
<tbody>
<tr>
<td style="vertical-align: top;">a<br>
</td>
<td style="vertical-align: top;">a<br>
</td>
</tr>
<tr>
<td style="vertical-align: top;">a<br>
</td>
<td style="vertical-align: top;">a<br>
</td>
</tr>
<tr>
<td style="vertical-align: top;">a<br>
</td>
<td style="vertical-align: top;">a<br>
</td>
</tr>
<tr>
<td style="vertical-align: top;">a<br>
</td>
<td style="vertical-align: top;">a<br>
</td>
</tr>
<tr>
<td style="vertical-align: top;">a<br>
</td>
<td style="vertical-align: top;">a<br>
</td>
</tr>
<tr>
<td style="vertical-align: top;">a<br>
</td>
<td style="vertical-align: top;">a<br>
</td>
</tr>
<tr>
<td style="vertical-align: top;">a<br>
</td>
<td style="vertical-align: top;">a<br>
</td>
</tr>
<tr>
<td style="vertical-align: top;">a<br>
</td>
<td style="vertical-align: top;">a<br>
</td>
</tr>
<tr>
<td style="vertical-align: top;">a<br>
</td>
<td style="vertical-align: top;">a<br>
</td>
</tr>
</tbody>
</table>

In [1]:
a = 8
b = 8.0
c = "julia"

a,b,c

(8,8.0,"julia")

In [2]:
typeof(a), typeof(b), typeof(c)

(Int64,Float64,ASCIIString)

In [44]:
d = Float64(a); e = convert(Int,b)

d , e

(8.0,8)

In [45]:
typeof(d),typeof(e)

(Float64,Int64)

## TUPLA

Tupla é uma sequência ordenada de elementos, como uma matriz. Uma tupla é representado por parênteses e vírgulas, em vez dos colchetes usados por matrizes. Tuplas são principalmente indicadas para agrupamento de comprimento fixo pequenas - eles são usados em todos os lugares em Julia, por exemplo, como listas de argumentos e de retorno de vários valores de funções.

A diferença importante entre matrizes e tuplas é que tuplas são **imutáveis**. Muitas funções de matrizes também pode ser usado em tuplas. Forma:
```julia
variavel  = (valor1,valor2)
```
E o tipo pode ser inteiro, float, complex e outros.

In [46]:
t1 = (1,2,3)

(1,2,3)

In [47]:
typeof(t1)

Tuple{Int64,Int64,Int64}

In [48]:
t2 = (1,2,"Julia")

(1,2,"Julia")

In [49]:
typeof(t2)

Tuple{Int64,Int64,ASCIIString}

** Coisas para fazer com tuplas**

In [206]:
+(1,2,4), *(1,2,4)

(7,8)

## DICIONÁRIO

Os dicionários são estruturas de dados que contém pares de chave-valor. Diferente de um vetor no qual os valores do vetor é indexadas por numeros inteiros, dicionários são indexados por chaves (keys), que podem ser de qualquer tipo imutável (como strings e inteiros). Dicionários são delimitados por parenteses e contém uma lista de pares ("chave",valor) separada por vírgulas. Forma básica:
```julia
Dict([(chave,valor),(chave,valor)]) ou Dict(chave => valor, chave => valor)
```
O tipo de um dicionário é na forma: Dict{"Tipo basico","Tipo basico"}

"Tipo basico" pode ser inteiro, Float, string, complex e any(valores heterogeneos).

In [1]:
d1 = Dict([("a", 1), ("b", 2),("c","Julia")])

Dict{ASCIIString,Any} with 3 entries:
  "c" => "Julia"
  "b" => 2
  "a" => 1

In [2]:
typeof(d1)

Dict{ASCIIString,Any}

In [50]:
# acessar valor da chave "c"

d1["c"]

"Julia"

In [49]:
# acessar somente as chaves

keys(d1)

Base.KeyIterator for a Dict{ASCIIString,Any} with 3 entries. Keys:
  "c"
  "b"
  "a"

outra forma mais compacta:

In [3]:
d2 = Dict(1 => "Maxima", 2 => 2, 3 =>"Julia")

Dict{Int64,Any} with 3 entries:
  2 => 2
  3 => "Julia"
  1 => "Maxima"

In [4]:
typeof(d2)

Dict{Int64,Any}

In [66]:
# acessar valor da chave 3

d2[3]

"Julia"

## CONJUNTOS

Um Set é um conjunto de elementos, como uma matriz ou dicionário, sem elementos duplicados. Forma:
```julia
Set([valor1, valor2])
``` 
O tipo básico pode ser: inteiro, float, complex... ou any.

In [18]:
Coisas = Set(["Julia",10])

Set(Any[10,"Julia"])

In [20]:
in("Julia", Coisas)

true

## SEQUÊNCIAS

Consiste de um conjunto ordenado de elementos,semelhante a um vetor, com cada elemento identificado por um índice. Range cria vetores unidimensionais ( Array{Tipo_dado,**1**} ) Forma:
```julia
range(inicio,passo, tamanho) ou
inicio : passo : tamanho
```
O tipo básico pode ser: inteiro, float, complex e outros. Não é possível alterar um valor de uma sequencia.

In [40]:
# range(inicio, passo, tamanho)

seq1 = range(1, 0.1, 3)

typeof(seq1)

FloatRange{Float64}

In [41]:
# so vai até 3, se tentar o vs[4] ocorre erro

seq1[3]

1.2

In [50]:
# Não é possível alterar um valor

5.0 => seq1[3]

5.0=>1.2

In [51]:
seq1[3]

1.2

In [6]:
seq2 = 1:0.1:3

typeof(seq2)

FloatRange{Float64}

In [7]:
seq2[3]

1.2

**Cuidado com os tipos! Veja a diferença**

In [56]:
r0 = range(1, 1  , 5)      # ranger do tipo inteiro
r1 = range(1, 1.0, 5)      # ranger do tipo float, observe o 1.0

display(r0)
display(r1)

display(typeof(r0))
display(typeof(r1))

1:1:5

1.0:1.0:5.0

StepRange{Int64,Int64}

FloatRange{Float64}

## LISTAS, ARRAY, VETORES E MATRIZES 

### LISTAS E ARRAY

Um array é uma coleção ordenada de elementos. É muitas vezes indicada com colchetes e itens separados por vírgulas. É possível criar arrays vazios ou arrays que armazenam valores de tipos diferentes ou restritas a valores de um tipo específico.

Na linguagem Julia, os arrays são usados para listas, vetores, tabelas e matrizes. Um array unidimensional atua como um vector ou uma lista. Uma array 2D pode ser utilizada como uma tabela ou matriz.

In [9]:
# Vetor aletório do tipo Inteiro de 3 elementos

A1 = Array(Int,3)

3-element Array{Int64,1}:
 139645202738352
 139645180101968
 139645232398768

In [10]:
# Vetor indefinido do tipo AbstractString de 3 elementos

A2 = Array(AbstractString,3)

3-element Array{AbstractString,1}:
 #undef
 #undef
 #undef

In [11]:
# Vetor aleatório do tipo Float32 de 3 elementos

A3 = Array(Float32,3)

3-element Array{Float32,1}:
 -1.24357e-11
  4.55604e-41
 -1.24357e-11

In [12]:
# Vetor aleatório do tipo Float32 vazio

A4 = Array[]

0-element Array{Array{T,N},1}

#### ARRAY UNIDIMENSIONAL / VETORES E ARRAY MULTIDIMENSIONAL / MATRIZES####

** Array Unidimensional / Vetores **

In [60]:
# Resetar todas a variáveis

workspace()

* ** Criação de vetores e acesso a dados em um vetor **

Para acessar um vetor utiliza a forma ** vetor[indice] **

In [248]:
# vetor vazio

a = []

0-element Array{Any,1}

In [249]:
# vetor coluna

a = [1, 2, 3, 4, 5]

# ou 

aa = [1;2;3;4;5]

display(a)
display(aa)

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [86]:
# dimensoes do vetor

size(a) 

(5,)

In [87]:
# Vetor Linha. Vetores linha são bidimensional Array{Tipo_dado,2}

b = [1 2 3 4 5]

1x5 Array{Int64,2}:
 1  2  3  4  5

In [88]:
# Comprimento do vetor

size(b) 

(1,5)

In [89]:
# transforma o vetor linha ou array (matrix de 1x5 (2 dimensoes)) em um vetor de uma dimensão

bb = vec(b)

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [97]:
# tipo do vetor e tipo dos elementos do vetor
# array (vetor b) de 2 dimensões e agora vetor de 1 dimensão (vetor bb)

println("vetor b: ",typeof(b)," , ",  eltype(b))
println("vetor bb: ",typeof(bb)," , ", eltype(bb))

vetor b: Array{Int64,2} , Int64
vetor bb: Array{Int64,1} , Int64


* **Manipulação de Arrays/vetores **

In [261]:
a = [1,2,3]

3-element Array{Int64,1}:
 1
 2
 3

In [262]:
# quantidade de elementos de um vetor ou tamanho do vetor

length(a)

3

In [263]:
# adicionando o elemento 10 e em seguida os elementos -2, -4, 500 e 100 ao final do vetor

push!(a,10), push!(a,-2,-4,500,100)

([1,2,3,10,-2,-4,500,100],[1,2,3,10,-2,-4,500,100])

In [264]:
# retirando elemento do final do vetor 

pop!(a), a

(100,[1,2,3,10,-2,-4,500])

In [265]:
# retirar elemento de uma posição específica. deleteat!(vetor,posição)

deleteat!(a,3)

6-element Array{Int64,1}:
   1
   2
  10
  -2
  -4
 500

In [266]:
# fatia o vetor na forma splice!(vetor,faixa de posições ou apenas uma posição,novo_vetor). 
# No exemplo, o vetor [100 1] é colocado na posição 2

splice!(a, 2, [100 1]), a

(2,[1,100,1,10,-2,-4,500])

In [267]:
# fatia o vetor na forma splice!(vetor,faixa de posições ou apenas uma posição,novo_vetor).
# no exemplo, o vetor [50 -50] é inserido entre as posições 2 a 4

splice!(a, 2:4, [50 -50]), a

([100,1,10],[1,50,-50,-2,-4,500])

In [268]:
# Aumentar o tamanho do vetor em 10 posições #undef significa tipo indefinido

resize!(a,5)

5-element Array{Int64,1}:
   1
  50
 -50
  -2
  -4

In [269]:
# Alterando o valor do 4 elemento do vetor "a"

a[4] = 100

a

5-element Array{Int64,1}:
   1
  50
 -50
 100
  -4

In [61]:
# Limpar o vetor 

empty!(a), a

(Any[],Any[])

Atenção: push e pop nao serve para vetores linha! Funciona somente para vetores coluna.

In [82]:
vl = [1 2 3]

push!(vl,10), pop!(vl)

LoadError: LoadError: MethodError: `push!` has no method matching push!(::Array{Int64,2}, ::Int64)

You might have used a 2d row vector where a 1d column vector was required.
Note the difference between 1d column vector [1,2,3] and 2d row vector [1 2 3].
You can convert to a column vector with the vec() function.
Closest candidates are:
  push!(::Any, ::Any, !Matched::Any)
  push!(::Any, ::Any, !Matched::Any, !Matched::Any...)
  push!(!Matched::Array{Any,1}, ::ANY)
  ...
while loading In[82], in expression starting on line 3

* ** Vetor aleatorio e vetor vazio indefinido**

In [76]:
# vetor aleatório

va = rand(3)

3-element Array{Float64,1}:
 0.510298  
 0.170566  
 0.00287493

In [80]:
# CUIDADO COM AS DIMENSÕES! VEJA A DIFERENÇA

v0 = rand(3)       # vetor unidimensional do tipo float
v1 = rand(3,1)     # vetor bidimensional do tipo float

display(v0)
display(v1)

display(size(v0))
display(size(v1))

3-element Array{Float64,1}:
 0.265661
 0.608694
 0.397295

3x1 Array{Float64,2}:
 0.301829
 0.969019
 0.800931

(3,)

(3,1)

In [59]:
# vetor de tipo definido com dados gerados aleatoriamente

b = Array(Int64,3)

3-element Array{Int64,1}:
 140101932068016
 140101909437776
 140101961065168

In [60]:
# acessar dado e um vetor

b[2]

140101909437776

In [61]:
# dimensoes do vetor

size(b)

(3,)

In [62]:
# quantidade de elementos de um vetor ou tamanho do vetor

length(b)

3

In [83]:
# vetor linha bidimensional de elementos indefinidos do tipo Any 

c = cell(1, 3)

1x3 Array{Any,2}:
 #undef  #undef  #undef

Informação sobre o tipo do vetor e tipo dos elementos

* ** Criando vetores de zeros e uns **

In [66]:
# vetor de zeros

d = zeros(3)

3-element Array{Float64,1}:
 0.0
 0.0
 0.0

In [67]:
# vetor de uns

e = ones(3)

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

In [87]:
# CUIDADO COM OS TIPOS! VEJA A DIFERENÇA

e0 = ones(3)       # vetor unidimensional do tipo float
e1 = ones(3,1)     # vetor bidimensional do tipo float
e2 = ones(1:3)     # vetor unidimensional do tipo inteiro
e3 = ones(1.0:3.0) # vetor unidimensional do tipo float

display(e0)
display(e1)
display(e2)
display(e3)

display(size(e0))
display(size(e1))
display(size(e2))
display(size(e3))

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

3x1 Array{Float64,2}:
 1.0
 1.0
 1.0

3-element Array{Int64,1}:
 1
 1
 1

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

(3,)

(3,1)

(3,)

(3,)

* ** Criando vetores usando o linspace **

O comando linspace cria vetores unidimensional ( Array{Tipo_dado,**1**} ). Sintaxe:
```julia
linspace(incio, fim, partes)
```

In [68]:
# Criando um vetor de 1 a 2 com 5 partes

x = linspace(1, 2, 5)

x   # hehehe nao mostra os dados

linspace(1.0,2.0,5)

In [69]:
# dimensoes e tipo do vetor

size(x), typeof(x)

((5,),LinSpace{Float64})

In [90]:
# quantidade de elementos de um vetor ou tamanho do vetor

length(x)

5

In [91]:
# acessando dados no vetor x

x[1],x[2],x[3],x[4],x[5]

(1.0,1.25,1.5,1.75,2.0)

* ** Criando vetores usando o collect **

O comando **collect** cria vetores unidimensional ( Array{Tipo_dado,**1**} ). Sintaxe:
```julia
collect(inicio : passo : fim)
```

In [92]:
# Criando um vetor de 1 a 2 de 0.25 em 0.25

y = collect(1:0.25:2) 

5-element Array{Float64,1}:
 1.0 
 1.25
 1.5 
 1.75
 2.0 

In [93]:
# dimensoes do vetor

size(y)

(5,)

In [94]:
# quantidade de elementos de um vetor ou tamanho do vetor

length(y)

5

In [95]:
# acessando dados no vetor y

y[1],y[2],y[3],y[4],y[5]

(1.0,1.25,1.5,1.75,2.0)

In [96]:
# CUIDADOS COM OS TIPO! VEJA A DIFERENÇA

y0 = collect(1:2:6)   # vetor unidimensional do tipo inteiro
y1 = collect(1.0:2:6) # vetor unidimensional do tipo float
y2 = collect(1:2.0:6) # vetor unidimensional do tipo float

display(y0)
display(y1)
display(y2)

display(size(y0))
display(size(y1))
display(size(y2))

3-element Array{Int64,1}:
 1
 3
 5

3-element Array{Float64,1}:
 1.0
 3.0
 5.0

3-element Array{Float64,1}:
 1.0
 3.0
 5.0

(3,)

(3,)

(3,)

* ** Criando vetores usando o range **

A range criada é um vetor unidimensional ( Array{Tipo_dado,**1**} ). Sintaxe:
```
range(inicio, passo, tamanho) ou
inicio : passo : tamanho
```
Não é possivel alterar o valor de um elemento da range

In [35]:
vr1 = range(0,0.1,5)

0.0:0.1:0.4

In [36]:
typeof(vr)

FloatRange{Float64}

In [37]:
# acessando elementos 

vr1[5]

0.4

In [52]:
# Não é possível alterar o valor de um elemento da range

vr1[5] = 0.0

LoadError: LoadError: indexed assignment not defined for FloatRange{Float64}
while loading In[52], in expression starting on line 3

Outra forma

In [98]:
# semelhante ao linspace do MatLab

vr2 = 1:0.25:2

1.0:0.25:2.0

In [99]:
typeof(vr2)

FloatRange{Float64}

In [100]:
# acessando dados no vetor z

vr2[1],vr2[2],vr2[3],vr2[4],vr2[5]

(1.0,1.25,1.5,1.75,2.0)

* ** Criando vetores usando preenchimento **

In [102]:
# cria um vetor linha de 5 elementos preenchidos com a letra a string julia

t = fill("julia", 1, 5)

1x5 Array{ASCIIString,2}:
 "julia"  "julia"  "julia"  "julia"  "julia"

In [103]:
# tipo do vetor e tipo dos elementos do vetor

typeof(t),eltype(t)

(Array{ASCIIString,2},ASCIIString)

In [101]:
# quantidade de elementos de um vetor ou tamanho do vetor

length(t)

5

* **Redimensionando vetores **

O comando resize! cria vetores unidimensionais ( Array{Tipo_dado,**1**} )

In [102]:
# resize!(vetor,x) Redefine um vetor para um tamanho "x". 
# Se o tamanho do vetor for menor que o tamanho "x", é feito o preenchimento adicional 
# de mais elementos aleatoriamente ao final do vetor.

# y é um vetor coluna de 1 até 2 de 0.5 em 0.5, de tamanho 4.

y = collect(1:0.5:2)

p = resize!(y,5)

5-element Array{Float64,1}:
 1.0
 1.5
 2.0
 0.0
 0.0

* ** Acessos especiais **

In [103]:
v = [1, 2, 3, 4, 5,6,7,8,9,10,11,12,13,14,15]

u = ["a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "l" "m" "n" "o" "p"];

In [104]:
# imprime os elementos a partir do elemento 1 até o ultimo (end) de 2 em 2 

v[1:2:end] , u[1:2:end] 

([1,3,5,7,9,11,13,15],ASCIIString["a","c","e","g","i","l","n","p"])

In [105]:
# imprime os elementos a partir do elemento 5 até o ultimo (end) de 2 em 2 

v[5:2:end] ,u[5:2:end] 

([5,7,9,11,13,15],ASCIIString["e","g","i","l","n","p"])

In [106]:
# imprime na forma de um vetor coluna, os elementos de ordem primeiro, terceiro e sexto

v[[1, 3, 6]], u[[1, 3, 6]]

([1,3,6],ASCIIString["a","c","f"])

In [107]:
# imprime na forma de um vetor linha, os elementos de ordem primeiro, terceiro e sexto

v[[4 5 6]], u[[4 5 6]]

(
1x3 Array{Int64,2}:
 4  5  6,

1x3 Array{ASCIIString,2}:
 "d"  "e"  "f")

In [108]:
# cria um subconjunto coluna do vetor do elemento de posição 1 até o elemento de posição 10 
# tomando de 2 em 2 posições

sub(v, 1:3:10), sub(u, 1:2:10)

([1,4,7,10],ASCIIString["a","c","e","g","i"])

In [109]:
# posição final do vetor

endof(v), endof(u)

(15,15)

* **Concatenação de vetores **

In [307]:
# concatenação de vetores

tta = [1 2 3]
ttb = [4 5 6]
yya = [1,2,3]
yyb = [4,5,6]
z = [tta ttb]  # cria um vetor linha

x = [yya,yyb]  # cria uma vetor coluna

display(z)
display(x)

1x6 Array{Int64,2}:
 1  2  3  4  5  6

6-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6

* ** Ordenação de vetores **

O comando **sort** somente ordena o vetor e **sort!** ordena e substitui os dados do vetor pelos dados ordenados.

In [121]:
# ordenando vetor

va = rand(3)

println("vetor normal :",va)

println("vetor ordenado :",sort(va));

vetor normal :[0.23874364316557295,0.35623266156092925,0.28286763584990005]
vetor ordenado :[0.23874364316557295,0.28286763584990005,0.35623266156092925]


* **Filtro de dados**

In [315]:
vet = 1:5

filter(x -> x > 2, vet)

3-element Array{Int64,1}:
 3
 4
 5

In [313]:
vet_nomes = ["julia","sage","maxima","julia","scilab","julia"]

filter(x -> x != "julia", vet_nomes)

3-element Array{ASCIIString,1}:
 "sage"  
 "maxima"
 "scilab"

Forma compacta de filtrar dados. O ponto " . " serve para avaliar elemento-elemento do vetor

In [314]:
vet[vet.> 2]

3-element Array{Int64,1}:
 3
 4
 5

In [285]:
vet[vet.!= 3]

4-element Array{Int64,1}:
 1
 2
 4
 5

In [294]:
vet_nomes[vet_nomes.!="julia"]

3-element Array{ASCIIString,1}:
 "sage"  
 "maxima"
 "scilab"

* **Criar par de elementos**

O comando **zip** cria pares ordenados.

In [318]:
vet_a = [8.4 9.5 10.6]
vet_b = [8.1 9.2 10.3]

pares = zip(vet_a,vet_b)

Base.Zip2{Array{Float64,2},Array{Float64,2}}(1x3 Array{Float64,2}:
 8.4  9.5  10.6,1x3 Array{Float64,2}:
 8.1  9.2  10.3)

In [319]:
typeof(pares)

Base.Zip2{Array{Float64,2},Array{Float64,2}}

In [322]:
# Listar elementos do vetor a

pares.a

1x3 Array{Float64,2}:
 8.4  9.5  10.6

In [321]:
# Acessar elementos do vetor a

pares.a[2]

9.5

In [173]:
# Acessar elementos do vetor b

pares.b

1x3 Array{Float64,2}:
 8.1  9.2  10.3

In [164]:
for i in pares
    print(i)    
end

(8.4,8.1)(9.5,9.2)(10.6,10.3)

outra forma usando tupla

In [168]:
pares_novo = ((8.4,8.1), (9.5, 9.2), (10.6, 10.3)) 

((8.4,8.1),(9.5,9.2),(10.6,10.3))

#### ARRAY MULTIDIMENSIONAL / MATRIZES####

* **Criação e manipulação de Matrizes**

In [323]:
#Criando uma matriz 3x3 

Ma = [2 4 6;8 9 10;12 14 16]

3x3 Array{Int64,2}:
  2   4   6
  8   9  10
 12  14  16

In [324]:
# criando matriz de valores aleatórios

Mb = rand(3,3)

3x3 Array{Float64,2}:
 0.352739  0.140004  0.876822
 0.515645  0.54971   0.377769
 0.503876  0.840689  0.992584

In [325]:
# criando uma matriz Mb 3x3 e testando se os elementos 2 e 15 fazem parte da matriz

Mc = [2 4 6;8 9 10;12 14 16]

(2 in Mb),(in(15, Mb))

(false,false)

In [326]:
# listar elentos impareres da matriz Mb

find(iseven, Mc)

8-element Array{Int64,1}:
 1
 2
 3
 4
 6
 7
 8
 9

In [331]:
# find(matriz,[elementos]) retorna a posição dos elementos de matriz "A"

display(Mc)

display(findin(Mc, [2,6]))

3x3 Array{Int64,2}:
  2   4   6
  8   9  10
 12  14  16

2-element Array{Int64,1}:
 1
 7

In [332]:
# testando

Mc[1], Mc[7]

(2,6)

In [117]:
# cria uma matriz formada pelos numeros de 1 a 9 sorteados aleatoriamente de tamanho 3x3

Mad = rand(1:9, 3, 3)

3x3 Array{Int64,2}:
 1  6  3
 7  9  2
 7  8  8

In [333]:
# jogos da mega sena parte 2: penultimate edition!

Mad = rand(1:60, 6, 6)

6x6 Array{Int64,2}:
 33  30  21  21  57  36
 24  14  38  59  55   7
 31  21  10  49  30  34
 48  33  25   7  60  25
 41  24  21   6  14  59
  1   8  44  26   4  45

* ** Ordenação de elementos **

In [334]:
# ordena as linhas 

sortrows(Mad)

6x6 Array{Int64,2}:
  1   8  44  26   4  45
 24  14  38  59  55   7
 31  21  10  49  30  34
 33  30  21  21  57  36
 41  24  21   6  14  59
 48  33  25   7  60  25

In [335]:
# ordena as colunas

sortcols(Mad)

6x6 Array{Int64,2}:
 21  21  30  33  36  57
 38  59  14  24   7  55
 10  49  21  31  34  30
 25   7  33  48  25  60
 21   6  24  41  59  14
 44  26   8   1  45   4

* ** Matrizes de zeros e uns **

In [121]:
# cria uma matriz 3x3 de zeros

Mz = zeros(3,3)

3x3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [122]:
# cria uma matriz 3x3 de uns

Mo = ones(3,3)

3x3 Array{Float64,2}:
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0

In [123]:
# cria uma matriz 3x3 identidade

Mi = eye(3, 3)

3x3 Array{Float64,2}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

* ** Preenchimento de matrizes **

In [124]:
# Cria uma matriz 3x3 preenchendo (fill) de strings "julia"

Mf = fill("julia", 3, 3)

3x3 Array{ASCIIString,2}:
 "julia"  "julia"  "julia"
 "julia"  "julia"  "julia"
 "julia"  "julia"  "julia"

In [193]:
# cria uma matriz repetindo a matriz nxm em x linhas e y colunas.
# o comando abaixo cria uma matriz repetindo a matriz de uns 2x2
# em 3 linhas e 3 colunas

repmat(ones(2), 3, 3)

6x3 Array{Float64,2}:
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0

In [189]:
# cria uma matriz com x*y elementos utilizando um vetor (pode ser range, linspace, rand e outros)
# o comando abaixo cria uma matriz de 5 linhas e 3 colunas a partir de um vetor de 15 elementos

reshape(1:15, 5, 3)

5x3 Array{Int64,2}:
 1   6  11
 2   7  12
 3   8  13
 4   9  14
 5  10  15

**Repetindo elementos para preencher matrizes**

Duas funções úteis para a criação de matrizes: são repmat (A, n, m) e repeat().

    A -> matriz
    n,m -> quantidade de repetições para n linhas e m colunas 

In [195]:
A = [1 2 3;4 5 6]

2x3 Array{Int64,2}:
 1  2  3
 4  5  6

In [197]:
# será repetido as linhas 3 vezes e 4 vezes as colunas.

repmat(A, 3, 4)

6x12 Array{Int64,2}:
 1  2  3  1  2  3  1  2  3  1  2  3
 4  5  6  4  5  6  4  5  6  4  5  6
 1  2  3  1  2  3  1  2  3  1  2  3
 4  5  6  4  5  6  4  5  6  4  5  6
 1  2  3  1  2  3  1  2  3  1  2  3
 4  5  6  4  5  6  4  5  6  4  5  6

* **Criação de matrizes a partir da concatenação de vetores **

In [337]:
v1 = [1 2 3]
v2 = [1,2,3]

display(v1)
display(v2)

1x3 Array{Int64,2}:
 1  2  3

3-element Array{Int64,1}:
 1
 2
 3

In [338]:
# matriz 1x6 

Mv1 = [v1 v1]

1x6 Array{Int64,2}:
 1  2  3  1  2  3

In [339]:
# matriz 3x2 

Mv2 = [v2 v2]

3x2 Array{Int64,2}:
 1  1
 2  2
 3  3

In [340]:
# matriz 2x3

Mv3 = [v1 ; v1]

2x3 Array{Int64,2}:
 1  2  3
 1  2  3

In [341]:
# ATENÇÃO: neste caso será criado um vetor
# devido a dimensão  Array{Int64,1}

Mv4 = [v2 ; v2]

6-element Array{Int64,1}:
 1
 2
 3
 1
 2
 3

* ** Concatenação de matrizes**

In [198]:
# criar as mastrizes

Mra = [1 2 3 ; 4 5 6 ]
Mrb = [0 0 0;1 1 1]

Mra, Mrb

(
2x3 Array{Int64,2}:
 1  2  3
 4  5  6,

2x3 Array{Int64,2}:
 0  0  0
 1  1  1)

In [135]:
# imprimir todos os elementos da segunda coluna da matriz Mra
display(Mra[:,2])

# imprimir todos os elementos da segunda linha da matriz Mrb
display(Mrb[2,:])

2-element Array{Int64,1}:
 2
 5

1x3 Array{Int64,2}:
 1  1  1

In [199]:
# concatenar 

display([Mra Mrb])

display([Mra;Mrb])

2x6 Array{Int64,2}:
 1  2  3  0  0  0
 4  5  6  1  1  1

4x3 Array{Int64,2}:
 1  2  3
 4  5  6
 0  0  0
 1  1  1

In [205]:
# criar uma matriz utilizando os elementos da segunda linha da matriz Mra
# e todos os elementos da matriz Mrb.

[Mra[:,2] Mrb]

2x4 Array{Int64,2}:
 2  0  0  0
 5  1  1  1

* **Filtro aplicado a uma matriz**

In [295]:
# criar uma matriz aleatória e cria o vetor
# contendo os elementos filtrados menores que 0.2

mat_num = rand(3,3)
display(mat_num)

filter(x -> x <= 0.2, mat_num)

3x3 Array{Float64,2}:
 0.00873755  0.112404  0.540787
 0.285546    0.542736  0.72288 
 0.133401    0.296688  0.188148

4-element Array{Float64,1}:
 0.00873755
 0.133401  
 0.112404  
 0.188148  

Forma compacta de filtrar dados

In [296]:
# a instrução ".>" é necessária para comparar elemento por elemento

mat_num[mat_num.<0.2]

4-element Array{Float64,1}:
 0.00873755
 0.133401  
 0.112404  
 0.188148  

## POLINOMIOS##

In [210]:
using SymPy
@syms x

(x,)

In [228]:
P = Poly(x^2 - 4, x)

Poly(x**2 - 4, x, domain='ZZ')

In [229]:
coeffs(P)

2-element Array{Any,1}:
  1
 -4

## TIPOS DEFINIDOS PELO PROGRAMADOR##

In [137]:
type Forca
    massa     ::Float64
    Aceleracao::Float64    
end

In [138]:
typeof(Forca)

DataType

In [139]:
objeto1 = Forca(5,0.1)

Forca(5.0,0.1)

In [140]:
typeof(objeto1)

Forca

In [141]:
fieldnames(objeto1)

2-element Array{Symbol,1}:
 :massa     
 :Aceleracao

In [142]:
objeto1.massa, objeto1.Aceleracao

(5.0,0.1)

In [143]:
type Aluno
    Nome    ::AbstractString
    Sexo    ::AbstractString
    Idade   ::Int64
    Endereco::AbstractString
end

In [144]:
J1 = Aluno("Julia","F",18,"Rua MIT,2001")

Aluno("Julia","F",18,"Rua MIT,2001")

In [145]:
typeof(J1)

Aluno

In [146]:
fieldnames(J1)

4-element Array{Symbol,1}:
 :Nome    
 :Sexo    
 :Idade   
 :Endereco

In [147]:
J1.Nome

"Julia"

In [148]:
J1.Idade

18

%%% Fim Tipos de Dados %%%