# TIPOS DE DADOS

## NUMÉRICOS

### TIPOS INTEIROS:

* Int8 — inteiros 8-bit com sinal variando de - $2^7 ~~a~~ 2^7 - 1$.
* Int8 — inteiros 8-bit sem sinal variando de $0 ~~a~~ 2^8 - 1$.
* Int16 — inteiros 16-bit com sinal variando de $-2^{15}~~ a ~~ 2^{15} - 1$.
* Int16 — inteiros 16-bit sem sinal variando de $0~~ a ~~2^{16} - 1$.
* Int32 — inteiros 32-bit com sinal variando de $-2^{31} ~~a~~ 2^{31} - 1$.
* Int32 — inteiros 32-bit sem sinal variando de $0~~ a~~ 2^{32} - 1$.
* Int64 — inteiros 64-bit com sinal variando de $-2^{63} ~~a~~ 2^{63} - 1$.
* Int64 — inteiros 64-bit sem sinal variando de $0 ~~a~~ 2^{64} - 1$.
* Int128 — inteiros 128-bit com sinal variando de $-2^{127}~~ a~~ 2^{127} - 1$.
* Int128 — inteiros 128-bit sem sinal variando de $0~~ a~~ 2^{128} - 1$.
* Bool — true (verdadeiro) ou false (falso), que correspondem numericamente a 1 ou 0, respectivamente.
* Char — um tipo numérico de 32 bits representando um caracter Unicode (veja Strings para mais detalhes).

### TIPOS PONTO FLUTUANTE:

* Float32 — Números de ponto flutuante 32-bit seguindo o padrão IEEE 754.
* Float64 — Números de ponto flutuante 64-bit seguindo o padrão IEEE 754.

### NUMEROS COMPLEXOS 

Para definir, usa-se a parte real em conjunto com a parte imaginária **im**

In [1]:
# real e imaginário
1 + 2im

1 + 2im

In [2]:
# soma de imaginários
(1 + 8im) + (2 - 3im)

3 + 5im

In [3]:
# produto
(1 + 8im) * (2 - 3im)

26 + 13im

In [4]:
# potencia
(26 + 13im)^2

507 + 676im

In [6]:
# extrair somente a parte real
real(1 + 2im)

1

In [7]:
# extrair somente a parte imaginária
imag(1 + 2im)

2

In [8]:
# conjugado
conj(1 + 2im)

1 - 2im

In [9]:
# módulo
abs(1 + 2im)

2.23606797749979

## CONSTANTES

In [193]:
pi, e, golden

(π = 3.1415926535897...,[1.0,1.0,1.0],φ = 1.6180339887498...)

<strong>Declarando uma constante</strong><br>
Constantes, declarado como <strong>const</strong>, são variáveis imutáveis quanto ao tipo. Ou seja, podem mudar de valor (será dado um aviso) mas não podem mudar de tipo.


In [194]:
# variável "vel_luz" do tipo string
const vel_luz = "299792458"

"299792458"

In [195]:
# Alterando a variável para outro valor do mesmo tipo string. Será dado um aviso
const vel_luz = "30000000"

"30000000"

In [196]:
# Não é possível alterar o tipo da variável "vel_luz" para inteiro. Ocorrerá ero
const vel_luz = 30000000

LoadError: LoadError: invalid redefinition of constant vel_luz
while loading In[196], in expression starting on line 2

In [197]:
vel_luz

"30000000"

In [198]:
# saber o tipo da constante
typeof(vel_luz)

ASCIIString

## VARIÁVEIS

* ** Resetar todas as variáveis**

Julia não possui um comando análogo ao **clear** do MATLAB; uma vez que um nome é definido em uma sessão de Julia (tecnicamente, no módulo principal), ele está sempre presente. Com o comando ` workspace()` Julia não reseta, de fato, as variáveis mas ele configura outro workspace.

In [199]:
workspace()

* **Trabalhando com variáveis**

In [200]:
# Atribindo o valor 2 a variavel x
x = 2

2

In [201]:
# Executando o calculo
x^2

4

In [202]:
# Variável literal
y = "so testando";

In [203]:
y

"so testando"

In [204]:
# Ao tentar utilizar uma variável nao declarada, ocorre um erro "Xvar not defined"
Xvar

LoadError: LoadError: UndefVarError: Xvar not defined
while loading In[204], in expression starting on line 2

In [205]:
# verificar o tipo da variável
typeof(x),typeof(y)

(Int64,ASCIIString)

In [206]:
# testar tipo
isa(x, Int64)

true

In [207]:
# construção de um complexo 
a = 2
b = 3.5

complex(a,b)

2.0 + 3.5im

* **Declarando  Várias variáveis ao mesmo tempo **

In [208]:
# Declarando Várias variáveis
x = 5 
y = 10 
z = "julia";

In [209]:
x,y,z

(5,10,"julia")

In [13]:
# Por padrão, será impresso somente a ultima linha, mas as variáveis internas estão acessíveis
w = begin
    x = 2
    y = 3
    x + y    
end

5

In [36]:
# y do bloco de w
y

3

In [38]:
# outra forma. Por padrão, será impresso somente a ultima linha, mas as variáveis internas estão acessíveis
w = (x = 2; y = 3; x + y)

5

* ** Variáveis criadas ** 

In [213]:
whos()

                          Base  29148 KB     Module
                          Core   4475 KB     Module
                      LastMain   4043 KB     Module
                          Main   4477 KB     Module
                             a      8 bytes  Int64
                             b      8 bytes  Float64
                             w      8 bytes  Int64
                             x      8 bytes  Int64
                             y      8 bytes  Int64
                             z     13 bytes  ASCIIString


* **Macro @printf**

In [214]:
x = 10.0
@printf("valor de x é %f",x)

valor de x é 10.000000

## STRING

Forma de expressão

** Convertendo uma string em uma expressão matemática **

In [215]:
string_formula = "x^2 + 1"
y = parse(string_formula)

:(x ^ 2 + 1)

In [216]:
typeof(y)

Expr

In [217]:
x = 0
eval(y)

1

## CONVERSÃO DE TIPOS

<div style="text-align: justify;">Tabela de Tipos<br>
</div>
<table style="text-align: left; width: 271px; height: 304px;" border="1"
cellpadding="2" cellspacing="2">
<tbody>
<tr>
<td style="vertical-align: top;">a<br>
</td>
<td style="vertical-align: top;">a<br>
</td>
</tr>
<tr>
<td style="vertical-align: top;">a<br>
</td>
<td style="vertical-align: top;">a<br>
</td>
</tr>
<tr>
<td style="vertical-align: top;">a<br>
</td>
<td style="vertical-align: top;">a<br>
</td>
</tr>
<tr>
<td style="vertical-align: top;">a<br>
</td>
<td style="vertical-align: top;">a<br>
</td>
</tr>
<tr>
<td style="vertical-align: top;">a<br>
</td>
<td style="vertical-align: top;">a<br>
</td>
</tr>
<tr>
<td style="vertical-align: top;">a<br>
</td>
<td style="vertical-align: top;">a<br>
</td>
</tr>
<tr>
<td style="vertical-align: top;">a<br>
</td>
<td style="vertical-align: top;">a<br>
</td>
</tr>
<tr>
<td style="vertical-align: top;">a<br>
</td>
<td style="vertical-align: top;">a<br>
</td>
</tr>
<tr>
<td style="vertical-align: top;">a<br>
</td>
<td style="vertical-align: top;">a<br>
</td>
</tr>
</tbody>
</table>

In [218]:
a = 8
b = 8.0
c = "julia"

a,b,c

(8,8.0,"julia")

In [219]:
typeof(a), typeof(b), typeof(c)

(Int64,Float64,ASCIIString)

In [220]:
d = Float64(a); e = convert(Int,b)
d , e

(8.0,8)

In [221]:
typeof(d),typeof(e)

(Float64,Int64)

## TUPLA

Tupla é uma sequência ordenada de elementos semelhante a um vetor. Uma tupla é representado por parênteses e vírgulas, em vez dos colchetes usados por matrizes. Tuplas são principalmente indicadas para agrupamento de comprimento fixo pequenas - eles são usados em todos os lugares em Julia, por exemplo, como listas de argumentos e de retorno de vários valores de funções.

A diferença importante entre matrizes e tuplas é que tuplas são **imutáveis**. Muitas funções de matrizes também pode ser usado em tuplas. Forma:
```julia
variavel  = (valor1, valor2)
```
E o tipo pode ser inteiro, float, complex e outros.

In [7]:
t1 = (1,2,3)

(1,2,3)

In [8]:
typeof(t1)

Tuple{Int64,Int64,Int64}

In [5]:
t1[2]

2

In [8]:
# tuplas são imutáveis
t1[2] = 0.0

LoadError: LoadError: MethodError: no method matching setindex!(::Tuple{Int64,Int64,Int64}, ::Float64, ::Int64)
while loading In[8], in expression starting on line 2

In [3]:
t2 = (1,2,"Julia")

(1,2,"Julia")

In [4]:
typeof(t2)

Tuple{Int64,Int64,String}

** Coisas para fazer com tuplas**

In [226]:
+(1,2,4), *(1,2,4)

(7,8)

## DICIONÁRIO

Os dicionários são estruturas de dados que contém pares de chave-valor. Diferente de um vetor no qual os valores são indexados por numeros inteiros, dicionários são indexados por chaves (keys), que podem ser de qualquer tipo imutável (como strings e inteiros). Dicionários são delimitados por parenteses e contém uma lista de pares ("chave",valor) separada por vírgulas. Forma básica:
```julia
Dict([(chave,valor),(chave,valor)]) 

ou 

Dict(chave => valor, chave => valor)
```
O tipo de um dicionário é na forma: 
```julia
Dict{"Tipo basico","Tipo basico"}
```
"Tipo basico" pode ser inteiro, Float, string, complex e any(valores heterogeneos).

In [24]:
d1 = Dict([("a", 1), ("b", 2),("c","Julia")])

Dict{String,Any} with 3 entries:
  "c" => "Julia"
  "b" => 2
  "a" => 1

In [25]:
d2 = Dict(1 => "Maxima", 2 => 2, 3 =>"Julia")

Dict{Int64,Any} with 3 entries:
  2 => 2
  3 => "Julia"
  1 => "Maxima"

In [60]:
d3 = Dict()
d3["Amostra"] = 1
d3[1] = "raio"
d3[2] = 2

d3

Dict{Any,Any} with 3 entries:
  2         => 2
  "Amostra" => 1
  1         => "raio"

In [28]:
# veja que existe a informação sobre a chave e valor
typeof(d1), typeof(d2), typeof(d3)

(Dict{String,Any},Dict{Int64,Any},Dict{Any,Any})

In [15]:
# acessar valor da chave "c" de d1
d1["c"]

"Julia"

In [16]:
# acessar somente as chaves de d1
keys(d1)

Base.KeyIterator for a Dict{String,Any} with 3 entries. Keys:
  "c"
  "b"
  "a"

In [17]:
# deletar uma key de d1
delete!(d1, "b")

Dict{String,Any} with 2 entries:
  "c" => "Julia"
  "a" => 1

In [35]:
# ordenar o dicionário d3
sort(collect(keys(d3)))

3-element Array{Any,1}:
 "a"
 "b"
 "c"

**Alterar a Key do dicionário**

Keys são imutáveis, logo não permitem modificação de nome. O que se faz é copiar o conteúdo de uma `key` desejada para outra `nova key` e depois apaga-se o a `key` copiada

In [18]:
# copia a key "c" para a key "novo" e apaga-se a key "c"
d1["novo"] = pop!(d1,"c")

"Julia"

In [19]:
d1

Dict{String,Any} with 2 entries:
  "a"    => 1
  "novo" => "Julia"

**União e Merge**

O comando  junta os dois discionários mantendo a ordem de cada um. Sintaxe:
```julia 
union(dic_1,dic_2, ..., dic_n)
union!(dic_1,dic_2, ..., dic_n) # une os dicionários e sobrescreve no dic_1. CUIDADO!
```
O comando `marge()` também junta os dicionários mas se a mesma chave está presente em outra coleção, o valor para essa chave será o valor que tem na última coleta listados. Sintaxe:
```julia 
merge(dic_1,dic_2, ..., dic_n)
merge!(dic_1,dic_2, ..., dic_n) # merge os dicionário e sobrescreve no dic_1. CUIDADO!
```

In [46]:
display(d1), display(d3)

Dict{String,Any} with 3 entries:
  "c" => "Julia"
  "b" => 2
  "a" => 1

Dict{Any,Any} with 3 entries:
  "c"           => 1.0e-6
  "Resistencia" => 2000
  "Amostra"     => 1

(nothing,nothing)

In [47]:
u = (union(d1,d3))

6-element Array{Pair{A,Any},1}:
 Pair{String,Any}("c","Julia")    
 Pair{String,Any}("b",2)          
 Pair{String,Any}("a",1)          
 Pair{Any,Any}("c",1.0e-6)        
 Pair{Any,Any}("Resistencia",2000)
 Pair{Any,Any}("Amostra",1)       

In [48]:
m = merge(d1,d3)

Dict{Any,Any} with 5 entries:
  "c"           => 1.0e-6
  "Resistencia" => 2000
  "b"           => 2
  "Amostra"     => 1
  "a"           => 1

In [49]:
merge!(d1,d3)

Dict{String,Any} with 5 entries:
  "c"           => 1.0e-6
  "Resistencia" => 2000
  "b"           => 2
  "Amostra"     => 1
  "a"           => 1

In [52]:
d1

Dict{String,Any} with 5 entries:
  "c"           => 1.0e-6
  "Resistencia" => 2000
  "b"           => 2
  "Amostra"     => 1
  "a"           => 1

** Diferença e interseção entre dicionários**

In [61]:
# par (key, valor) diferentes entre d3 e d2
setdiff(d3, d2)

2-element Array{Pair{A,Any},1}:
 Pair{Any,Any}("Amostra",1)
 Pair{Any,Any}(1,"raio")   

In [64]:
# par (key, valor) diferentes entre d2 e d3
setdiff(d2, d3)

2-element Array{Pair{A,Any},1}:
 Pair{Int64,Any}(3,"Julia") 
 Pair{Int64,Any}(1,"Maxima")

In [65]:
# # par (key, valor) iguais entre d3 e d2
intersect(d2, d3)

1-element Array{Pair{A,Any},1}:
 Pair{Int64,Any}(2,2)

## CONJUNTOS

Um Set é um conjunto de elementos, como uma matriz ou dicionário, sem elementos duplicados. Existe duas duas diferenças importantes entre um conjunto e outros tipos de dados. A primeira é que em um conjunto que você pode ter apenas um de cada elemento, e a segunda é que em um conjunto a ordem dos elementos não é importante (ao passo que uma matriz pode ter várias cópias de um elemento e sua ordem é importante). Sintaxe:
```julia
Set([valor1, valor2])
``` 
O tipo básico pode ser: inteiro, float, complex... ou any.

In [9]:
# O conjunto filtra elementos repetidos e permite somente uma entrada única
Coisas = Set(["Julia" , 10 , [1,2,3], "Julia"])

Set(Any[10,"Julia",[1,2,3]])

In [10]:
# verificar se um valor esta contido no conjunto
in("Julia", Coisas)

true

In [11]:
# acrescentando elemento
push!(Coisas, [7 8 9; 4 5 6], "Sage") 

Set(Any[10,"Sage","Julia",
[7 8 9; 4 5 6],

[1,2,3]])

## LISTAS, ARRAY, VETORES E MATRIZES 

Um array é uma coleção ordenada de elementos. É muitas vezes indicada com colchetes e itens separados por vírgulas. É possível criar arrays vazios ou arrays que armazenam valores de tipos diferentes ou restritas a valores de um tipo específico.

Na linguagem Julia, os arrays são usados para listas, vetores, tabelas e matrizes. Um array unidimensional atua como um vector ou uma lista. Uma array bidimensional pode ser utilizada como uma tabela ou matriz.

### ARRAY UNIDIMENSIONAL / VETORES

In [247]:
# Resetar todas a variáveis
workspace()

* ** Criação de vetores e acesso a dados em um vetor **

In [3]:
# vetor vazio
v_vaz = []

0-element Array{Any,1}

In [24]:
# vetor coluna
v_col1 = [1, 2, 3, 4, 5, 6, 7]

# ou 

v_col2 = ["a";"b";"c";"d";"e"]

display(a)
display(aa)

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [25]:
# Vetor Linha. Vetores linha são bidimensional Array{Tipo_dado,2}
v_lin1 = [1 2 3 4 5]

1×5 Array{Int64,2}:
 1  2  3  4  5

In [26]:
# dimensoes do vetor
size(v_vaz) , size(v_col1), size(v_col2) , size(v_lin1)

((0,),(7,),(5,),(1,5))

In [27]:
# comprimento do vetor
length(v_vaz), length(v_col1) , length(v_col2), length(v_lin1)

(0,7,5,5)

In [28]:
# transforma o vetor linha ou array (matrix de 1x5 (2 dimensoes)) em um vetor de uma dimensão
v_tr = vec(v_lin1)

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [29]:
# tipo do vetor e tipo dos elementos do vetor
# array (vetor b) de 2 dimensões e agora vetor de 1 dimensão (vetor bb)

println("vetor col 1: ",typeof(v_col1)," , ",  eltype(v_col1))
println("vetor transf: ",typeof(v_tr)," , ", eltype(v_tr))

vetor col 1: Array{Int64,1} , Int64
vetor transf: Array{Int64,1} , Int64


Para acessar vetores, utilize a sintaxe:
```julia
vetor[ordem_elemento]
```

In [30]:
v_col1[1] , v_col2[2] , v_lin1[3]

(1,"b",3)

* **Vetor aninhado**

Vetores aninhados são na verdade listas que possuem estuturas de dados como elementos. Estas estruturas podem ser: outros vetores, matrizes, tuplas, dicionários e outros que a linguagem permitir. A principal vantagem é a organização das informações e acesso rápido. Sintaxe:
```julia
vetor_aninhado[posição_estrutura_interna][posição_elemento_estrutura]
```

In [127]:
van = [("Elementos", "Tabela1"), ["Calcio", 20] , ["Sodio", 11] , ["Potassio",19], ["Bromo",5 ]]

5-element Array{Any,1}:
 ("Elementos","Tabela1")
 Any["Calcio",20]       
 Any["Sodio",11]        
 Any["Potassio",19]     
 Any["Bromo",5]         

In [128]:
# acessar o vetor de posição 5 e elemento 2
van[5]

2-element Array{Any,1}:
  "Bromo"
 5       

In [41]:
# acessar o vetor de posição 5 e elemento 2
van[5][2] 

5

In [42]:
# acessar a tupla de posição 1 e elemento 1
van[1][1]

"Elementos"

* **Manipulação de Arrays/vetores **

Os comandos abaixo não funcionam para vetores linha.

In [255]:
a = [1,2,3]

3-element Array{Int64,1}:
 1
 2
 3

In [256]:
# quantidade de elementos de um vetor ou tamanho do vetor
length(a)

3

In [257]:
# adicionando o elemento 10 e em seguida os elementos -2, -4, 500 e 100 ao final do vetor
append!(a,[10])

4-element Array{Int64,1}:
  1
  2
  3
 10

In [258]:
# adicionando os elementos -2, -4, 500 e 100 ao final do vetor
append!(a,[-2,-4,500,100])

8-element Array{Int64,1}:
   1
   2
   3
  10
  -2
  -4
 500
 100

In [259]:
# adicionando o elemento 55 na posição 2
insert!(a,2,55)

9-element Array{Int64,1}:
   1
  55
   2
   3
  10
  -2
  -4
 500
 100

In [260]:
# adicionando o elemento 77 e 88  no início do vetor
prepend!(a,[77,88])

11-element Array{Int64,1}:
  77
  88
   1
  55
   2
   3
  10
  -2
  -4
 500
 100

In [261]:
# retirando elemento do final do vetor 
pop!(a), a

(100,[77,88,1,55,2,3,10,-2,-4,500])

In [262]:
# retirando elemento do início do vetor 
shift!(a), a

(77,[88,1,55,2,3,10,-2,-4,500])

In [263]:
# retirar elemento de uma posição específica. deleteat!(vetor,posição)
deleteat!(a,3)

8-element Array{Int64,1}:
  88
   1
   2
   3
  10
  -2
  -4
 500

In [264]:
# fatia o vetor na forma splice!(vetor,faixa de posições ou apenas uma posição,novo_vetor). 
# No exemplo, o vetor [100 1] é colocado na posição 2
splice!(a, 2, [100 1]), a

(1,[88,100,1,2,3,10,-2,-4,500])

In [265]:
# fatia o vetor na forma splice!(vetor,faixa de posições ou apenas uma posição,novo_vetor).
# no exemplo, o vetor [50 -50] é inserido entre as posições 2 a 4
splice!(a, 2:4, [50 -50]), a

([100,1,2],[88,50,-50,3,10,-2,-4,500])

In [266]:
# Aumentar o tamanho do vetor em 10 posições #undef significa tipo indefinido
resize!(a,5)

5-element Array{Int64,1}:
  88
  50
 -50
   3
  10

In [267]:
# Alterando o valor do 4 elemento do vetor "a"
a[4] = 100

a

5-element Array{Int64,1}:
  88
  50
 -50
 100
  10

In [268]:
# Limpar o vetor 
empty!(a), a

(Int64[],Int64[])

Atenção: o comando `pop` nao serve para vetores linha! Funciona somente para vetores coluna.

* ** Vetor de dados aleatorio**

Julia permite criar vetores aleatórios de vários tipo e formatação. Vejamos alguns:

1. rand(número_elementos_vet_coluna) : Para criar um vetor de dados aleatórios entre 0 e 1

2. rand(a : b, número_elementos_vet_coluna) : Para criar um vetor de dados aleatórios entre a e b

3. randexp(número_elementos_vet_coluna) : 

4.  randn

5. randperm

6.  randstring

In [11]:
# vetor aleatório float64
va = rand(3)

3-element Array{Float64,1}:
 0.0089814
 0.111532 
 0.183307 

In [270]:
# CUIDADO COM AS DIMENSÕES! VEJA A DIFERENÇA
v0 = rand(3)       # vetor unidimensional do tipo float
v1 = rand(3,1)     # vetor bidimensional do tipo float

display(v0)
display(v1)

display(size(v0))
display(size(v1))

3-element Array{Float64,1}:
 0.850728
 0.291052
 0.459037

3x1 Array{Float64,2}:
 0.00799775
 0.00227305
 0.981339  

(3,)

(3,1)

In [12]:
# vetor de tipo definido com dados gerados aleatoriamente
b = rand(Int64,3)

3-element Array{Int64,1}:
  6801825722750884198
 -8813371183551945043
 -5345388248383517306

In [13]:
# acessar dado e um vetor
b[2]

-8813371183551945043

In [14]:
# dimensoes do vetor
size(b)

(3,)

In [15]:
# quantidade de elementos de um vetor ou tamanho do vetor
length(b)

3

Informação sobre o tipo do vetor e tipo dos elementos

* ** Criando vetores de zeros e uns **

In [276]:
# vetor de zeros
d = zeros(3)

3-element Array{Float64,1}:
 0.0
 0.0
 0.0

In [277]:
# vetor de uns
e = ones(3)

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

In [278]:
# CUIDADO COM OS TIPOS! VEJA A DIFERENÇA
e0 = ones(3)       # vetor unidimensional do tipo float
e1 = ones(3,1)     # vetor bidimensional do tipo float
e2 = ones(1:3)     # vetor unidimensional do tipo inteiro
e3 = ones(1.0:3.0) # vetor unidimensional do tipo float

display(e0)
display(e1)
display(e2)
display(e3)

display(size(e0))
display(size(e1))
display(size(e2))
display(size(e3))

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

3x1 Array{Float64,2}:
 1.0
 1.0
 1.0

3-element Array{Int64,1}:
 1
 1
 1

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

(3,)

(3,1)

(3,)

(3,)

* ** Criando vetores usando o linspace **

O comando linspace cria vetores unidimensional ( Array{Tipo_dado,**1**} ). Sintaxe:
```julia
linspace(incio, fim, partes)
```

In [279]:
# Criando um vetor de 1 a 2 com 5 partes
x = linspace(1, 2, 5)

x   # hehehe nao mostra os dados

linspace(1.0,2.0,5)

In [280]:
# dimensoes e tipo do vetor
size(x), typeof(x)

((5,),LinSpace{Float64})

In [281]:
# quantidade de elementos de um vetor ou tamanho do vetor
length(x)

5

In [282]:
# acessando dados no vetor x
x[1],x[2],x[3],x[4],x[5]

(1.0,1.25,1.5,1.75,2.0)

* ** Criando vetores usando o collect **

O comando **collect** cria vetores unidimensional ( Array{Tipo_dado,**1**} ). Sintaxe:
```julia
collect(inicio : passo : fim)
```

In [283]:
# Criando um vetor de 1 a 2 de 0.25 em 0.25
y = collect(1:0.25:2) 

5-element Array{Float64,1}:
 1.0 
 1.25
 1.5 
 1.75
 2.0 

In [284]:
# dimensoes do vetor
size(y)

(5,)

In [285]:
# quantidade de elementos de um vetor ou tamanho do vetor
length(y)

5

In [286]:
# acessando dados no vetor y
y[1],y[2],y[3],y[4],y[5]

(1.0,1.25,1.5,1.75,2.0)

In [287]:
# CUIDADOS COM OS TIPO! VEJA A DIFERENÇA
y0 = collect(1:2:6)   # vetor unidimensional do tipo inteiro
y1 = collect(1.0:2:6) # vetor unidimensional do tipo float
y2 = collect(1:2.0:6) # vetor unidimensional do tipo float

display(y0)
display(y1)
display(y2)

display(size(y0))
display(size(y1))
display(size(y2))

3-element Array{Int64,1}:
 1
 3
 5

3-element Array{Float64,1}:
 1.0
 3.0
 5.0

3-element Array{Float64,1}:
 1.0
 3.0
 5.0

(3,)

(3,)

(3,)

* ** Criando vetores usando o range **

Consiste de um conjunto ordenado de elementos,semelhante a um vetor, com cada elemento identificado por um índice. Range cria vetores unidimensionais ( Array{Tipo_dado,**1**} ). Sintaxe:
```julia
range(inicio,passo, tamanho) 
ou
inicio : passo : tamanho
```
O tipo básico pode ser: inteiro, float, complex e outros. Não é possível alterar um valor de uma sequencia.

In [288]:
vr1 = range(0,0.1,5)

0.0:0.1:0.4

In [289]:
typeof(vr)

LoadError: LoadError: UndefVarError: vr not defined
while loading In[289], in expression starting on line 1

In [290]:
# acessando elementos 
vr1[5]

0.4

In [291]:
# Não é possível alterar o valor de um elemento da range
vr1[5] = 0.0

LoadError: LoadError: indexed assignment not defined for FloatRange{Float64}
while loading In[291], in expression starting on line 2

Outra forma

In [292]:
# semelhante ao linspace do MatLab
vr2 = 1:0.25:2

1.0:0.25:2.0

In [293]:
typeof(vr2)

FloatRange{Float64}

In [294]:
# acessando dados no vetor z
vr2[1],vr2[2],vr2[3],vr2[4],vr2[5]

(1.0,1.25,1.5,1.75,2.0)

Cuidados com os tipos

In [92]:
r0 = range(1, 1  , 5) # ranger do tipo inteiro
r1 = 1 : 1.0 : 5      # ranger do tipo float, observe o valor 1.0 do tipo float

display(r0)
display(r1)

display(typeof(r0))
display(typeof(r1))

1:1:5

1.0:1.0:5.0

StepRange{Int64,Int64}

FloatRange{Float64}

* ** Criando vetores usando preenchimento **

In [295]:
# cria um vetor linha de 5 elementos preenchidos com a letra a string julia
t = fill("julia", 1, 5)

1x5 Array{ASCIIString,2}:
 "julia"  "julia"  "julia"  "julia"  "julia"

In [296]:
# tipo do vetor e tipo dos elementos do vetor
typeof(t),eltype(t)

(Array{ASCIIString,2},ASCIIString)

In [297]:
# quantidade de elementos de um vetor ou tamanho do vetor
length(t)

5

* **Redimensionando vetores **

O comando `resize!` cria vetores unidimensionais `( Array{Tipo_dado,**1**} )`

In [298]:
# resize!(vetor,x) Redefine um vetor para um tamanho "x". 
# Se o tamanho do vetor for menor que o tamanho "x", é feito o preenchimento adicional 
# de mais elementos aleatoriamente ao final do vetor.

# y é um vetor coluna de 1 até 2 de 0.5 em 0.5, de tamanho 4.
y = collect(1:0.5:2)

p = resize!(y,5)

5-element Array{Float64,1}:
 1.0
 1.5
 2.0
 0.0
 0.0

* ** Acessos especiais **

In [299]:
v = [1, 2, 3, 4, 5,6,7,8,9,10,11,12,13,14,15]
u = ["a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "l" "m" "n" "o" "p"];

In [300]:
# imprime os elementos a partir do elemento 1 até o ultimo (end) de 2 em 2 
v[1:2:end] , u[1:2:end] 

([1,3,5,7,9,11,13,15],ASCIIString["a","c","e","g","i","l","n","p"])

In [301]:
# imprime os elementos a partir do elemento 5 até o ultimo (end) de 2 em 2 
v[5:2:end] ,u[5:2:end] 

([5,7,9,11,13,15],ASCIIString["e","g","i","l","n","p"])

In [302]:
# imprime na forma de um vetor coluna, os elementos de ordem primeiro, terceiro e sexto
v[[1, 3, 6]], u[[1, 3, 6]]

([1,3,6],ASCIIString["a","c","f"])

In [303]:
# imprime na forma de um vetor linha, os elementos de ordem primeiro, terceiro e sexto
v[[4 5 6]], u[[4 5 6]]

(
1x3 Array{Int64,2}:
 4  5  6,

1x3 Array{ASCIIString,2}:
 "d"  "e"  "f")

In [304]:
# cria um subconjunto coluna do vetor do elemento de posição 1 até o elemento de posição 10 
# tomando de 2 em 2 posições
sub(v, 1:3:10), sub(u, 1:2:10)

([1,4,7,10],ASCIIString["a","c","e","g","i"])

In [305]:
# posição final do vetor
endof(v), endof(u)

(15,15)

* **Concatenação de vetores **

In [306]:
# concatenação de vetores
tta = [1 2 3]
ttb = [4 5 6]

yya = [1,2,3]
yyb = [4,5,6]

z = [tta ttb]  # cria um vetor linha

x = [yya; yyb]  # cria uma vetor coluna

display(z)
display(x)

1x6 Array{Int64,2}:
 1  2  3  4  5  6

6-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6

* ** Ordenação de vetores **

O comando **sort** somente ordena o vetor e **sort!** ordena e substitui os dados do vetor pelos dados ordenados.

In [307]:
# ordenando vetor
va = rand(3)

println("vetor normal :",va)
println("vetor ordenado :",sort(va));

vetor normal :[0.81802692036074,0.528389203054072,0.304322354836857]
vetor ordenado :[0.304322354836857,0.528389203054072,0.81802692036074]


* **Filtro aplicado a vetores**

Aplica o filtro a uma matriz e imprime somente os valores filtrados. Sintaxe:
```julia
vetor[vetor .operador_comparação valor]
ou 
vetor[(vetor .operador_comparação valor)operador_logico(vetor .operador_comparação valor)]

```

In [94]:
# definir o vetor numerico
vet_num = 1:5;

In [70]:
# filtrar numeros > 3
vet_num[vet_num.> 3]

2-element Array{Int64,1}:
 4
 5

In [44]:
# filtrar numeros diferente de 3
vet_num[vet_num.!= 3]

4-element Array{Int64,1}:
 1
 2
 4
 5

In [114]:
vet_nomes = ["julia","sage","maxima","julia","scilab","fremat"]

6-element Array{String,1}:
 "julia" 
 "sage"  
 "maxima"
 "julia" 
 "scilab"
 "fremat"

In [48]:
# filtrar nomes diferentes de "julia"
vet_nomes[vet_nomes.!= "julia"]

4-element Array{String,1}:
 "sage"  
 "maxima"
 "scilab"
 "fremat"

In [49]:
#filtar nomes maiores que contenham letra superior a "j" da string "julia
vet_nomes[vet_nomes.> "julia"]

3-element Array{String,1}:
 "sage"  
 "maxima"
 "scilab"

In [116]:
#filtar nomes maiores que contenham "julia" e "maxima"
vet_nomes[(vet_nomes.!= "julia")&((vet_nomes.!= "maxima"))]

3-element Array{String,1}:
 "sage"  
 "scilab"
 "fremat"

* **Criar par de elementos**

O comando **zip** cria pares ordenados.

In [113]:
vet_a = [8.4 9.5 10.6]
vet_b = [8.1 9.2 10.3]

pares = zip(vet_a,vet_b)

Base.Zip2{Array{Float64,2},Array{Float64,2}}([8.4 9.5 10.6],[8.1 9.2 10.3])

In [114]:
typeof(pares)

Base.Zip2{Array{Float64,2},Array{Float64,2}}

In [115]:
# Listar elementos do vetor a
pares.a

1×3 Array{Float64,2}:
 8.4  9.5  10.6

In [116]:
# Acessar elementos do vetor a
pares.a[2]

9.5

In [117]:
# Acessar elementos do vetor b
pares.b

1×3 Array{Float64,2}:
 8.1  9.2  10.3

In [118]:
# Acessar um par 
par = pares.a[2],pares.b[2]

(9.5,9.2)

In [119]:
# acessar elemento específico do par
par[1]

9.5

In [122]:
# listar todos os elementos usando uma LC
[println(i) for i in pares]

(8.4,8.1)
(9.5,9.2)
(10.6,10.3)


1×3 Array{Void,2}:
 nothing  nothing  nothing

outra forma usando tupla

In [11]:
pares_novo = ((8.4,8.1), (9.5, 9.2), (10.6, 10.3)) 

((8.4,8.1),(9.5,9.2),(10.6,10.3))

In [17]:
pares_novo[3]

(10.6,10.3)

In [18]:
pares_novo[3][1]

10.6

* ** Combinação e Permutação de elementos**

Em Julia 0.5 ou superior o comando `combinations` pertence ao pacote **Combinatorics.jl**. Para instalar e importar use :
```julia
Pkg.add("Combinatorics")
using Combinatorics
```
Sintaxe do comando:
```julia
combinations(vetor,pares)
```

In [21]:
using Combinatorics

# combinação 2x2
vetor = [1,2,3,4]
collect(combinations(vetor,2))

6-element Array{Array{Int64,1},1}:
 [1,2]
 [1,3]
 [1,4]
 [2,3]
 [2,4]
 [3,4]

In [74]:
# combinação 3x3
collect(combinations(vetor,3)) 

4-element Array{Array{Int64,1},1}:
 [1,2,3]
 [1,2,4]
 [1,3,4]
 [2,3,4]

In [73]:
# todas as possíveis
collect(permutations(vetor))

24-element Array{Array{Int64,1},1}:
 [1,2,3,4]
 [1,2,4,3]
 [1,3,2,4]
 [1,3,4,2]
 [1,4,2,3]
 [1,4,3,2]
 [2,1,3,4]
 [2,1,4,3]
 [2,3,1,4]
 [2,3,4,1]
 [2,4,1,3]
 [2,4,3,1]
 [3,1,2,4]
 [3,1,4,2]
 [3,2,1,4]
 [3,2,4,1]
 [3,4,1,2]
 [3,4,2,1]
 [4,1,2,3]
 [4,1,3,2]
 [4,2,1,3]
 [4,2,3,1]
 [4,3,1,2]
 [4,3,2,1]

### ARRAY MULTIDIMENSIONAL / MATRIZES

* **Criação e acesso a elementos de uma Matrizes**

Matrizes são formadas por vetores linhas (matriz 1xn) e a ordem dos elementos segue a lógica de 1 a n (quantidade de elementos) lidos de cima para baixo, coluna por coluna. Sintaxe:
```julia
[elemento_1_1  elemento_1_2 ... ; elemento_2_1  elemento_2_2...; elemento_n_1  ...  elemento_n_m]
```
Para acessar elementos de uma matriz temos a sintaxe:
```julia
matriz[linha, coluna]
```

In [300]:
#Criando uma matriz 3x3 
Ma = [2 4 6 ; 8 9 10 ; 12 14 15]

3×3 Array{Int64,2}:
  2   4   6
  8   9  10
 12  14  15

In [281]:
# acesso elemento da segunda linha e terceira coluna da matriz
Ma[2,3]

10

In [282]:
# acessar somente os elementos da primeira linha
Ma[1,:]

3-element Array{Int64,1}:
 2
 4
 6

In [283]:
# acessar somente os elementos da primeira coluna
Ma[:,1]

3-element Array{Int64,1}:
  2
  8
 12

* **Busca por elementos em uma matriz**

Comando `in ` procura o elemento e retorna `true`se encontrar ou `false` se não existir.
```julia
elemento_procurado in Matriz
```
Comando `find` retorna a ordem do elemento se determinada condição for verdadeira.
```julia
find(condição , Matriz)
```
Comando `findoin` retorna somente a ordem dos elementos que existem na matriz. 
```julia
findin(Matriz, [elemento_1, elemento_2 ...])
```

In [284]:
# testar se os elementos 2 e 15 fazem parte da matriz
(2 in Ma),(in(15, Ma))

(true,false)

In [306]:
# listar a ordem dos elementos impares da matriz Ma
find(isodd,Ma)

2-element Array{Int64,1}:
 5
 9

In [311]:
# testando
Ma[9]

15

In [309]:
# listar a ordem dos elementos pares da matriz Ma
find(iseven,Ma)

7-element Array{Int64,1}:
 1
 2
 3
 4
 6
 7
 8

In [310]:
# testando
Ma[3]

12

In [356]:
# findin retorna a posição dos elementos da matriz Ma
findin(Ma, [2,15])

2-element Array{Int64,1}:
 1
 9

In [333]:
# testando
Ma[1], Ma[9]

(2,15)

In [334]:
# retorna o valor máximo e ordem do elemento
findmax(Ma)

(15,9)

In [357]:
# retorna o valor mínimo e ordem do elemento
findmin(Ma)

(2,1)

* **Matriz Aleatória**

Julia permite criar matrizes aleatórios de vários tipo e formatação. Vejamos alguns:

1. rand(número_elementos_linha, número_elementos_coluna) : Para criar um vetor de dados aleatórios entre 0 e 1

2. rand(a : b, número_elementos_linha, número_elementos_coluna) : Para criar um vetor de dados aleatórios entre a e b

3. randexp(número_elementos_linha, número_elementos_coluna) : 

4.  randn()

In [358]:
# matriz de números aleatórios entre 0 e 1
rand(3,3)

3×3 Array{Float64,2}:
 0.27306   0.976967  0.404116
 0.475401  0.398966  0.502539
 0.9326    0.143578  0.782139

In [361]:
# matriz de números aleatórios entre 1 e 60 de tamanho 6x6 (NÚMEROS DA MEGA-SENA)
rand(1:60, 6 , 6)

6×6 Array{Int64,2}:
 55  42   2  28  50  17
 56  38  25  36   6  59
 23  14  53  18  56  20
 11  17   2  13  56  22
  6  11  54  47  23   1
 48  39  10  43  49  60

In [390]:
# matriz de números aleatórios exponenciais
randexp(3,3)

3×3 Array{Float64,2}:
 1.72878   0.345531  0.655864
 6.36918   1.27563   1.05396 
 0.138641  0.75898   2.10599 

In [389]:
# matriz de números aleatórios de distribuição normal
randn(3,3)

3×3 Array{Float64,2}:
  0.43042   -0.314809   1.21776 
 -1.17255   -0.490893  -1.27044 
  0.967282  -0.146325  -0.882543

* ** Ordenação de elementos **

In [333]:
# ordena as linhas 
sortrows(Mad)

6x6 Array{Int64,2}:
  8   4  31  14  17  52
 27   1  16  37  22   8
 30   3  28  33   4   2
 45  36  52  12  59  32
 46  51  28  32  58  30
 47  43  10  31  42   3

In [334]:
# ordena as colunas
sortcols(Mad)

6x6 Array{Int64,2}:
  3  10  31  42  43  47
 52  31  14  17   4   8
  2  28  33   4   3  30
 30  28  32  58  51  46
  8  16  37  22   1  27
 32  52  12  59  36  45

* ** Matrizes de zeros e uns **

In [335]:
# cria uma matriz 3x3 de zeros
Mz = zeros(3,3)

3x3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [336]:
# cria uma matriz 3x3 de uns
Mo = ones(3,3)

3x3 Array{Float64,2}:
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0

In [337]:
# cria uma matriz 3x3 identidade
Mi = eye(3, 3)

3x3 Array{Float64,2}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

* ** Preenchimento de matrizes **

In [69]:
# Cria uma matriz 3x3 preenchendo (fill) de strings "julia"
Mf = fill("julia", 3, 3)

3×3 Array{String,2}:
 "julia"  "julia"  "julia"
 "julia"  "julia"  "julia"
 "julia"  "julia"  "julia"

In [70]:
# cria uma matriz repetindo a matriz nxm em x linhas e y colunas.
# o comando abaixo cria uma matriz repetindo a matriz de uns 2x2
# em 3 linhas e 3 colunas
repmat(ones(2), 3, 3)

6×3 Array{Float64,2}:
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0

In [340]:
# cria uma matriz com x*y elementos utilizando um vetor (pode ser range, linspace, rand e outros)
# o comando abaixo cria uma matriz de 5 linhas e 3 colunas a partir de um vetor de 15 elementos
reshape(1:15, 5, 3)

5x3 Array{Int64,2}:
 1   6  11
 2   7  12
 3   8  13
 4   9  14
 5  10  15

**Repetindo elementos para preencher matrizes**

Duas funções úteis para a criação de matrizes: são repmat (A, n, m) e repeat().

    A -> matriz
    n,m -> quantidade de repetições para n linhas e m colunas 

In [341]:
A = [1 2 3;4 5 6]

2x3 Array{Int64,2}:
 1  2  3
 4  5  6

In [342]:
# será repetido as linhas 3 vezes e 4 vezes as colunas.
repmat(A, 3, 4)

6x12 Array{Int64,2}:
 1  2  3  1  2  3  1  2  3  1  2  3
 4  5  6  4  5  6  4  5  6  4  5  6
 1  2  3  1  2  3  1  2  3  1  2  3
 4  5  6  4  5  6  4  5  6  4  5  6
 1  2  3  1  2  3  1  2  3  1  2  3
 4  5  6  4  5  6  4  5  6  4  5  6

* **Criação de matrizes a partir da concatenação de vetores **

In [343]:
v1 = [1 2 3]
v2 = [1,2,3]

display(v1)
display(v2)

1x3 Array{Int64,2}:
 1  2  3

3-element Array{Int64,1}:
 1
 2
 3

In [344]:
# matriz 1x6 
Mv1 = [v1 v1]

1x6 Array{Int64,2}:
 1  2  3  1  2  3

In [345]:
# matriz 3x2 
Mv2 = [v2 v2]

3x2 Array{Int64,2}:
 1  1
 2  2
 3  3

In [346]:
# matriz 2x3
Mv3 = [v1 ; v1]

2x3 Array{Int64,2}:
 1  2  3
 1  2  3

In [347]:
# ATENÇÃO: neste caso será criado um vetor
# devido a dimensão  Array{Int64,1}
Mv4 = [v2 ; v2]

6-element Array{Int64,1}:
 1
 2
 3
 1
 2
 3

* ** Concatenação de matrizes**

In [189]:
# criar as matrizes
Mra = [1 2 3 ; 4 5 6 ]
Mrb = [0 0 0;1 1 1]

Mra, Mrb

(
[1 2 3; 4 5 6],

[0 0 0; 1 1 1])

In [190]:
# concatenar na horizontal
[Mra Mrb]

2×6 Array{Int64,2}:
 1  2  3  0  0  0
 4  5  6  1  1  1

In [191]:
# concatenar na vertical
[Mra;Mrb]

4×3 Array{Int64,2}:
 1  2  3
 4  5  6
 0  0  0
 1  1  1

In [351]:
# criar uma matriz utilizando os elementos da segunda linha da matriz Mra
# e todos os elementos da matriz Mrb.
[Mra[:,2] Mrb]

2x4 Array{Int64,2}:
 2  0  0  0
 5  1  1  1

* **Filtro aplicado a uma matriz**

Aplica o filtro a uma matriz e imprime somente os valores filtrados. Sintaxe:
```julia
matriz[matriz .operador_logico valor]
```

In [231]:
# criar uma matriz aleatória e cria o vetor
# contendo os elementos filtrados menores que 0.2
mat_num = rand(1:10,3,3) 

3×3 Array{Int64,2}:
 6  3  6
 9  8  6
 5  5  1

In [232]:
# filtrar numeros maiores ou iguais a 5
# a instrução ".<" é necessária para comparar elemento por elemento
mat_num[mat_num.<=5]

4-element Array{Int64,1}:
 5
 3
 5
 1

In [242]:
# filtrar elementos maiores ou igual a 5 E menores ou igual a 8
# a instrução ".<" é necessária para comparar elemento por elemento
mat_num[(mat_num.>=5)&(mat_num.<=9)]

7-element Array{Int64,1}:
 6
 9
 5
 8
 5
 6
 6

In [243]:
# filtrar elementos menores ou  igual a 5 OU maiores ou igual a 9
# a instrução ".<" é necessária para comparar elemento por elemento
mat_num[(mat_num.<=5)|(mat_num.>=9)]

5-element Array{Int64,1}:
 9
 5
 3
 5
 1

## TIPOS DEFINIDOS PELO PROGRAMADOR##

In [244]:
type Amostra
    material  ::AbstractString
    massa     ::Float64 # kg
    volume    ::Float64 # m^3
end

In [245]:
typeof(Amostra)

DataType

In [246]:
# criar um elemento do tipo amostra
objeto1 = Amostra("isopor", 0.001, 0.0001)

Amostra("isopor",0.001,0.0001)

In [247]:
# conferir tipo
typeof(objeto1)

Amostra

In [248]:
# conferir campos
fieldnames(objeto1)

3-element Array{Symbol,1}:
 :material
 :massa   
 :volume  

In [249]:
# conferir atributos do elemento criado
objeto1.massa, objeto1.material

(0.001,"isopor")

In [250]:
# alterar valor atributo massa
objeto1.massa = 0.002

0.002

**%%% Fim Tipos de Dados %%%**