# TIPOS DE DADOS

## NUMÉRICOS

### TIPOS INTEIROS:

* Int8 — inteiros 8-bit com sinal variando de - $2^7 ~~a~~ 2^7 - 1$.
* Int8 — inteiros 8-bit sem sinal variando de $0 ~~a~~ 2^8 - 1$.
* Int16 — inteiros 16-bit com sinal variando de $-2^{15}~~ a ~~ 2^{15} - 1$.
* Int16 — inteiros 16-bit sem sinal variando de $0~~ a ~~2^{16} - 1$.
* Int32 — inteiros 32-bit com sinal variando de $-2^{31} ~~a~~ 2^{31} - 1$.
* Int32 — inteiros 32-bit sem sinal variando de $0~~ a~~ 2^{32} - 1$.
* Int64 — inteiros 64-bit com sinal variando de $-2^{63} ~~a~~ 2^{63} - 1$.
* Int64 — inteiros 64-bit sem sinal variando de $0 ~~a~~ 2^{64} - 1$.
* Int128 — inteiros 128-bit com sinal variando de $-2^{127}~~ a~~ 2^{127} - 1$.
* Int128 — inteiros 128-bit sem sinal variando de $0~~ a~~ 2^{128} - 1$.
* Bool — valendo ou true (verdadeiro) ou false (falso), que correspondem numericamente a 1 ou 0, respectivamente.
* Char — um tipo numérico de 32 bits representando um caracter Unicode (veja Strings para mais detalhes).

### TIPOS PONTO FLUTUANTE:

* Float32 — Números de ponto flutuante 32-bit seguindo o padrão IEEE 754.
* Float64 — Números de ponto flutuante 64-bit seguindo o padrão IEEE 754.

### NUMEROS COMPLEXOS 

Para definir, usa-se a parte real em conjunto com a parte imaginária **im**

In [185]:
1 + 2im

1 + 2im

In [186]:
(1 + 8im) + (2 - 3im)

3 + 5im

In [187]:
(1 + 8im) * (2 - 3im)

26 + 13im

In [188]:
(26 + 13im)^2

507 + 676im

In [189]:
real(1 + 2im)

1

In [190]:
imag(1 + 2im)

2

In [191]:
conj(1 + 2im)

1 - 2im

In [192]:
abs(1 + 2im)

2.23606797749979

## CONSTANTES

In [193]:
pi, e, golden

(π = 3.1415926535897...,[1.0,1.0,1.0],φ = 1.6180339887498...)

<strong>Declarando uma constante</strong><br>
Constantes, declarado como <strong>const</strong>, são variáveis imutáveis quanto ao tipo. Ou seja, podem mudar de valor (será dado um aviso) mas não podem mudar de tipo.


In [194]:
# variável "vel_luz" do tipo string
const vel_luz = "299792458"

"299792458"

In [195]:
# Alterando a variável para outro valor do mesmo tipo string. Será dado um aviso
const vel_luz = "30000000"

"30000000"

In [196]:
# Não é possível alterar o tipo da variável "vel_luz" para inteiro. Ocorrerá ero
const vel_luz = 30000000

LoadError: LoadError: invalid redefinition of constant vel_luz
while loading In[196], in expression starting on line 2

In [197]:
vel_luz

"30000000"

In [198]:
# saber o tipo da constante
typeof(vel_luz)

ASCIIString

## VARIÁVEIS

* ** Resetar todas as variáveis**

Julia não tem um análogo da função **clear** do MATLAB; uma vez que um nome é definido em uma sessão de Julia (tecnicamente, no módulo principal), ele está sempre presente. Julia dessa forma não reseta, de fato, as variáveis. Na verdade ele configura outro workspace.

In [199]:
workspace()

* **Trabalhando com variáveis**

In [200]:
# Atribindo o valor 2 a variavel x
x = 2

2

In [201]:
# Executando o calculo
x^2

4

In [202]:
# Variável literal
y = "so testando";

In [203]:
y

"so testando"

In [204]:
# Ao tentar utilizar uma variável nao declarada, ocorre um erro "Xvar not defined"
Xvar

LoadError: LoadError: UndefVarError: Xvar not defined
while loading In[204], in expression starting on line 2

In [205]:
# verificar o tipo da variável
typeof(x),typeof(y)

(Int64,ASCIIString)

In [206]:
# testar tipo
isa(x, Int64)

true

In [207]:
# construção de um complexo 
a = 2
b = 3.5

complex(a,b)

2.0 + 3.5im

* **Declarando  Várias variáveis ao mesmo tempo **

In [208]:
# Declarando Várias variáveis
x = 5 
y = 10 
z = "julia";

In [209]:
x,y,z

(5,10,"julia")

In [210]:
# Por padrão, será impresso somente a ultima linha, mas as variáveis internas estão acessíveis
w = begin
    x = 2
    y = 3
    x+y
    
end

5

In [211]:
# y do bloco de w
y

3

In [212]:
# outra forma. Por padrão, será impresso somente a ultima linha, mas as variáveis internas estão acessíveis
w = (x = 2; y = 3; x + y)

w

5

* ** Variáveis criadas ** 

In [213]:
whos()

                          Base  29148 KB     Module
                          Core   4475 KB     Module
                      LastMain   4043 KB     Module
                          Main   4477 KB     Module
                             a      8 bytes  Int64
                             b      8 bytes  Float64
                             w      8 bytes  Int64
                             x      8 bytes  Int64
                             y      8 bytes  Int64
                             z     13 bytes  ASCIIString


* **Macro @printf**

In [214]:
x = 10.0
@printf("valor de x é %f",x)

valor de x é 10.000000

## STRING

** Convertendo uma string em uma expressão matemática **

In [215]:
string_formula = "x^2 + 1"
y = parse(string_formula)

:(x ^ 2 + 1)

In [216]:
typeof(y)

Expr

In [217]:
x = 0
eval(y)

1

## CONVERSÃO DE TIPOS

<div style="text-align: justify;">Tabela de Tipos<br>
</div>
<table style="text-align: left; width: 271px; height: 304px;" border="1"
cellpadding="2" cellspacing="2">
<tbody>
<tr>
<td style="vertical-align: top;">a<br>
</td>
<td style="vertical-align: top;">a<br>
</td>
</tr>
<tr>
<td style="vertical-align: top;">a<br>
</td>
<td style="vertical-align: top;">a<br>
</td>
</tr>
<tr>
<td style="vertical-align: top;">a<br>
</td>
<td style="vertical-align: top;">a<br>
</td>
</tr>
<tr>
<td style="vertical-align: top;">a<br>
</td>
<td style="vertical-align: top;">a<br>
</td>
</tr>
<tr>
<td style="vertical-align: top;">a<br>
</td>
<td style="vertical-align: top;">a<br>
</td>
</tr>
<tr>
<td style="vertical-align: top;">a<br>
</td>
<td style="vertical-align: top;">a<br>
</td>
</tr>
<tr>
<td style="vertical-align: top;">a<br>
</td>
<td style="vertical-align: top;">a<br>
</td>
</tr>
<tr>
<td style="vertical-align: top;">a<br>
</td>
<td style="vertical-align: top;">a<br>
</td>
</tr>
<tr>
<td style="vertical-align: top;">a<br>
</td>
<td style="vertical-align: top;">a<br>
</td>
</tr>
</tbody>
</table>

In [218]:
a = 8
b = 8.0
c = "julia"

a,b,c

(8,8.0,"julia")

In [219]:
typeof(a), typeof(b), typeof(c)

(Int64,Float64,ASCIIString)

In [220]:
d = Float64(a); e = convert(Int,b)
d , e

(8.0,8)

In [221]:
typeof(d),typeof(e)

(Float64,Int64)

## TUPLA

Tupla é uma sequência ordenada de elementos, como uma matriz. Uma tupla é representado por parênteses e vírgulas, em vez dos colchetes usados por matrizes. Tuplas são principalmente indicadas para agrupamento de comprimento fixo pequenas - eles são usados em todos os lugares em Julia, por exemplo, como listas de argumentos e de retorno de vários valores de funções.

A diferença importante entre matrizes e tuplas é que tuplas são **imutáveis**. Muitas funções de matrizes também pode ser usado em tuplas. Forma:
```julia
variavel  = (valor1,valor2)
```
E o tipo pode ser inteiro, float, complex e outros.

In [222]:
t1 = (1,2,3)

(1,2,3)

In [223]:
typeof(t1)

Tuple{Int64,Int64,Int64}

In [224]:
t2 = (1,2,"Julia")

(1,2,"Julia")

In [225]:
typeof(t2)

Tuple{Int64,Int64,ASCIIString}

** Coisas para fazer com tuplas**

In [226]:
+(1,2,4), *(1,2,4)

(7,8)

## DICIONÁRIO

Os dicionários são estruturas de dados que contém pares de chave-valor. Diferente de um vetor no qual os valores do vetor é indexadas por numeros inteiros, dicionários são indexados por chaves (keys), que podem ser de qualquer tipo imutável (como strings e inteiros). Dicionários são delimitados por parenteses e contém uma lista de pares ("chave",valor) separada por vírgulas. Forma básica:
```julia
Dict([(chave,valor),(chave,valor)]) ou Dict(chave => valor, chave => valor)
```
O tipo de um dicionário é na forma: Dict{"Tipo basico","Tipo basico"}

"Tipo basico" pode ser inteiro, Float, string, complex e any(valores heterogeneos).

In [227]:
d1 = Dict([("a", 1), ("b", 2),("c","Julia")])

Dict{ASCIIString,Any} with 3 entries:
  "c" => "Julia"
  "b" => 2
  "a" => 1

In [228]:
typeof(d1)

Dict{ASCIIString,Any}

In [229]:
# acessar valor da chave "c"
d1["c"]

"Julia"

In [230]:
# acessar somente as chaves
keys(d1)

Base.KeyIterator for a Dict{ASCIIString,Any} with 3 entries. Keys:
  "c"
  "b"
  "a"

outra forma mais compacta:

In [231]:
d2 = Dict(1 => "Maxima", 2 => 2, 3 =>"Julia")

Dict{Int64,Any} with 3 entries:
  2 => 2
  3 => "Julia"
  1 => "Maxima"

In [232]:
typeof(d2)

Dict{Int64,Any}

In [233]:
# acessar valor da chave 3
d2[3]

"Julia"

## CONJUNTOS

Um Set é um conjunto de elementos, como uma matriz ou dicionário, sem elementos duplicados. Forma:
```julia
Set([valor1, valor2])
``` 
O tipo básico pode ser: inteiro, float, complex... ou any.

In [234]:
Coisas = Set(["Julia",10])

Set(Any[10,"Julia"])

In [235]:
in("Julia", Coisas)

true

## SEQUÊNCIAS

Consiste de um conjunto ordenado de elementos,semelhante a um vetor, com cada elemento identificado por um índice. Range cria vetores unidimensionais ( Array{Tipo_dado,**1**} ) Forma:
```julia
range(inicio,passo, tamanho) ou
inicio : passo : tamanho
```
O tipo básico pode ser: inteiro, float, complex e outros. Não é possível alterar um valor de uma sequencia.

In [2]:
# range(inicio, passo, tamanho)
seq1 = range(1, 0.1, 3)

typeof(seq1)

FloatRange{Float64}

In [3]:
# so vai até 3, se tentar o seq1[4] ocorre erro
seq1[3]

1.2

In [4]:
# Não é possível alterar um valor
seq1[3] = 5

LoadError: LoadError: indexed assignment not defined for FloatRange{Float64}
while loading In[4], in expression starting on line 2

In [7]:
# outra forma de criar uma range
seq2 = 1:0.1:3
typeof(seq2)

FloatRange{Float64}

In [8]:
seq2[3]

1.2

**Cuidado com os tipos! Veja a diferença**

In [242]:
r0 = range(1, 1  , 5)      # ranger do tipo inteiro
r1 = range(1, 1.0, 5)      # ranger do tipo float, observe o 1.0

display(r0)
display(r1)

display(typeof(r0))
display(typeof(r1))

1:1:5

1.0:1.0:5.0

StepRange{Int64,Int64}

FloatRange{Float64}

## LISTAS, ARRAY, VETORES E MATRIZES 

### LISTAS E ARRAY

Um array é uma coleção ordenada de elementos. É muitas vezes indicada com colchetes e itens separados por vírgulas. É possível criar arrays vazios ou arrays que armazenam valores de tipos diferentes ou restritas a valores de um tipo específico.

Na linguagem Julia, os arrays são usados para listas, vetores, tabelas e matrizes. Um array unidimensional atua como um vector ou uma lista. Uma array 2D pode ser utilizada como uma tabela ou matriz.

In [243]:
# Vetor aletório do tipo Inteiro de 3 elementos
A1 = Array(Int,3)

3-element Array{Int64,1}:
 140350761076496
 140342025815376
 140342025936976

In [244]:
# Vetor indefinido do tipo AbstractString de 3 elementos
A2 = Array(AbstractString,3)

3-element Array{AbstractString,1}:
 #undef
 #undef
 #undef

In [245]:
# Vetor aleatório do tipo Float32 de 3 elementos
A3 = Array(Float32,3)

3-element Array{Float32,1}:
 -5.99197e28 
  4.57874e-41
 -6.32886e28 

In [246]:
# Vetor aleatório do tipo Float32 vazio
A4 = Array[]

0-element Array{Array{T,N},1}

#### ARRAY UNIDIMENSIONAL / VETORES E ARRAY MULTIDIMENSIONAL / MATRIZES####

** Array Unidimensional / Vetores **

In [247]:
# Resetar todas a variáveis
workspace()

* ** Criação de vetores e acesso a dados em um vetor **

Para acessar um vetor utiliza a forma ** vetor[indice] **

In [248]:
# vetor vazio
a = []

0-element Array{Any,1}

In [249]:
# vetor coluna
a = [1, 2, 3, 4, 5]

# ou 

aa = [1;2;3;4;5]

display(a)
display(aa)

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [250]:
# dimensoes do vetor
size(a) 

(5,)

In [251]:
# Vetor Linha. Vetores linha são bidimensional Array{Tipo_dado,2}
b = [1 2 3 4 5]

1x5 Array{Int64,2}:
 1  2  3  4  5

In [252]:
# Comprimento do vetor
size(b) 

(1,5)

In [253]:
# transforma o vetor linha ou array (matrix de 1x5 (2 dimensoes)) em um vetor de uma dimensão
bb = vec(b)

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [254]:
# tipo do vetor e tipo dos elementos do vetor
# array (vetor b) de 2 dimensões e agora vetor de 1 dimensão (vetor bb)

println("vetor b: ",typeof(b)," , ",  eltype(b))
println("vetor bb: ",typeof(bb)," , ", eltype(bb))

vetor b: Array{Int64,2} , Int64
vetor bb: Array{Int64,1} , Int64


* **Manipulação de Arrays/vetores **

Os comandos abaixo não funcionam para vetores linha.

In [255]:
a = [1,2,3]

3-element Array{Int64,1}:
 1
 2
 3

In [256]:
# quantidade de elementos de um vetor ou tamanho do vetor
length(a)

3

In [257]:
# adicionando o elemento 10 e em seguida os elementos -2, -4, 500 e 100 ao final do vetor
append!(a,[10])

4-element Array{Int64,1}:
  1
  2
  3
 10

In [258]:
# adicionando os elementos -2, -4, 500 e 100 ao final do vetor
append!(a,[-2,-4,500,100])

8-element Array{Int64,1}:
   1
   2
   3
  10
  -2
  -4
 500
 100

In [259]:
# adicionando o elemento 55 na posição 2
insert!(a,2,55)

9-element Array{Int64,1}:
   1
  55
   2
   3
  10
  -2
  -4
 500
 100

In [260]:
# adicionando o elemento 77 e 88  no início do vetor
prepend!(a,[77,88])

11-element Array{Int64,1}:
  77
  88
   1
  55
   2
   3
  10
  -2
  -4
 500
 100

In [261]:
# retirando elemento do final do vetor 
pop!(a), a

(100,[77,88,1,55,2,3,10,-2,-4,500])

In [262]:
# retirando elemento do início do vetor 
shift!(a), a

(77,[88,1,55,2,3,10,-2,-4,500])

In [263]:
# retirar elemento de uma posição específica. deleteat!(vetor,posição)
deleteat!(a,3)

8-element Array{Int64,1}:
  88
   1
   2
   3
  10
  -2
  -4
 500

In [264]:
# fatia o vetor na forma splice!(vetor,faixa de posições ou apenas uma posição,novo_vetor). 
# No exemplo, o vetor [100 1] é colocado na posição 2
splice!(a, 2, [100 1]), a

(1,[88,100,1,2,3,10,-2,-4,500])

In [265]:
# fatia o vetor na forma splice!(vetor,faixa de posições ou apenas uma posição,novo_vetor).
# no exemplo, o vetor [50 -50] é inserido entre as posições 2 a 4
splice!(a, 2:4, [50 -50]), a

([100,1,2],[88,50,-50,3,10,-2,-4,500])

In [266]:
# Aumentar o tamanho do vetor em 10 posições #undef significa tipo indefinido
resize!(a,5)

5-element Array{Int64,1}:
  88
  50
 -50
   3
  10

In [267]:
# Alterando o valor do 4 elemento do vetor "a"
a[4] = 100

a

5-element Array{Int64,1}:
  88
  50
 -50
 100
  10

In [268]:
# Limpar o vetor 
empty!(a), a

(Int64[],Int64[])

Atenção:  e pop nao serve para vetores linha! Funciona somente para vetores coluna.

* ** Vetor aleatorio e vetor vazio indefinido**

In [269]:
# vetor aleatório
va = rand(3)

3-element Array{Float64,1}:
 0.686316
 0.467494
 0.781185

In [270]:
# CUIDADO COM AS DIMENSÕES! VEJA A DIFERENÇA
v0 = rand(3)       # vetor unidimensional do tipo float
v1 = rand(3,1)     # vetor bidimensional do tipo float

display(v0)
display(v1)

display(size(v0))
display(size(v1))

3-element Array{Float64,1}:
 0.850728
 0.291052
 0.459037

3x1 Array{Float64,2}:
 0.00799775
 0.00227305
 0.981339  

(3,)

(3,1)

In [271]:
# vetor de tipo definido com dados gerados aleatoriamente
b = Array(Int64,3)

3-element Array{Int64,1}:
 140342073642000
 140342069326032
 140342069326064

In [272]:
# acessar dado e um vetor
b[2]

140342069326032

In [273]:
# dimensoes do vetor
size(b)

(3,)

In [274]:
# quantidade de elementos de um vetor ou tamanho do vetor
length(b)

3

In [275]:
# vetor linha bidimensional de elementos indefinidos do tipo Any
c = cell(1, 3)

1x3 Array{Any,2}:
 #undef  #undef  #undef

Informação sobre o tipo do vetor e tipo dos elementos

* ** Criando vetores de zeros e uns **

In [276]:
# vetor de zeros
d = zeros(3)

3-element Array{Float64,1}:
 0.0
 0.0
 0.0

In [277]:
# vetor de uns
e = ones(3)

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

In [278]:
# CUIDADO COM OS TIPOS! VEJA A DIFERENÇA
e0 = ones(3)       # vetor unidimensional do tipo float
e1 = ones(3,1)     # vetor bidimensional do tipo float
e2 = ones(1:3)     # vetor unidimensional do tipo inteiro
e3 = ones(1.0:3.0) # vetor unidimensional do tipo float

display(e0)
display(e1)
display(e2)
display(e3)

display(size(e0))
display(size(e1))
display(size(e2))
display(size(e3))

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

3x1 Array{Float64,2}:
 1.0
 1.0
 1.0

3-element Array{Int64,1}:
 1
 1
 1

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

(3,)

(3,1)

(3,)

(3,)

* ** Criando vetores usando o linspace **

O comando linspace cria vetores unidimensional ( Array{Tipo_dado,**1**} ). Sintaxe:
```julia
linspace(incio, fim, partes)
```

In [279]:
# Criando um vetor de 1 a 2 com 5 partes
x = linspace(1, 2, 5)

x   # hehehe nao mostra os dados

linspace(1.0,2.0,5)

In [280]:
# dimensoes e tipo do vetor
size(x), typeof(x)

((5,),LinSpace{Float64})

In [281]:
# quantidade de elementos de um vetor ou tamanho do vetor
length(x)

5

In [282]:
# acessando dados no vetor x
x[1],x[2],x[3],x[4],x[5]

(1.0,1.25,1.5,1.75,2.0)

* ** Criando vetores usando o collect **

O comando **collect** cria vetores unidimensional ( Array{Tipo_dado,**1**} ). Sintaxe:
```julia
collect(inicio : passo : fim)
```

In [283]:
# Criando um vetor de 1 a 2 de 0.25 em 0.25
y = collect(1:0.25:2) 

5-element Array{Float64,1}:
 1.0 
 1.25
 1.5 
 1.75
 2.0 

In [284]:
# dimensoes do vetor
size(y)

(5,)

In [285]:
# quantidade de elementos de um vetor ou tamanho do vetor
length(y)

5

In [286]:
# acessando dados no vetor y
y[1],y[2],y[3],y[4],y[5]

(1.0,1.25,1.5,1.75,2.0)

In [287]:
# CUIDADOS COM OS TIPO! VEJA A DIFERENÇA
y0 = collect(1:2:6)   # vetor unidimensional do tipo inteiro
y1 = collect(1.0:2:6) # vetor unidimensional do tipo float
y2 = collect(1:2.0:6) # vetor unidimensional do tipo float

display(y0)
display(y1)
display(y2)

display(size(y0))
display(size(y1))
display(size(y2))

3-element Array{Int64,1}:
 1
 3
 5

3-element Array{Float64,1}:
 1.0
 3.0
 5.0

3-element Array{Float64,1}:
 1.0
 3.0
 5.0

(3,)

(3,)

(3,)

* ** Criando vetores usando o range **

A range criada é um vetor unidimensional ( Array{Tipo_dado,**1**} ). Sintaxe:
```
range(inicio, passo, tamanho) ou
inicio : passo : tamanho
```
Não é possivel alterar o valor de um elemento da range

In [288]:
vr1 = range(0,0.1,5)

0.0:0.1:0.4

In [289]:
typeof(vr)

LoadError: LoadError: UndefVarError: vr not defined
while loading In[289], in expression starting on line 1

In [290]:
# acessando elementos 
vr1[5]

0.4

In [291]:
# Não é possível alterar o valor de um elemento da range
vr1[5] = 0.0

LoadError: LoadError: indexed assignment not defined for FloatRange{Float64}
while loading In[291], in expression starting on line 2

Outra forma

In [292]:
# semelhante ao linspace do MatLab
vr2 = 1:0.25:2

1.0:0.25:2.0

In [293]:
typeof(vr2)

FloatRange{Float64}

In [294]:
# acessando dados no vetor z
vr2[1],vr2[2],vr2[3],vr2[4],vr2[5]

(1.0,1.25,1.5,1.75,2.0)

* ** Criando vetores usando preenchimento **

In [295]:
# cria um vetor linha de 5 elementos preenchidos com a letra a string julia
t = fill("julia", 1, 5)

1x5 Array{ASCIIString,2}:
 "julia"  "julia"  "julia"  "julia"  "julia"

In [296]:
# tipo do vetor e tipo dos elementos do vetor
typeof(t),eltype(t)

(Array{ASCIIString,2},ASCIIString)

In [297]:
# quantidade de elementos de um vetor ou tamanho do vetor
length(t)

5

* **Redimensionando vetores **

O comando resize! cria vetores unidimensionais ( Array{Tipo_dado,**1**} )

In [298]:
# resize!(vetor,x) Redefine um vetor para um tamanho "x". 
# Se o tamanho do vetor for menor que o tamanho "x", é feito o preenchimento adicional 
# de mais elementos aleatoriamente ao final do vetor.

# y é um vetor coluna de 1 até 2 de 0.5 em 0.5, de tamanho 4.
y = collect(1:0.5:2)

p = resize!(y,5)

5-element Array{Float64,1}:
 1.0
 1.5
 2.0
 0.0
 0.0

* ** Acessos especiais **

In [299]:
v = [1, 2, 3, 4, 5,6,7,8,9,10,11,12,13,14,15]
u = ["a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "l" "m" "n" "o" "p"];

In [300]:
# imprime os elementos a partir do elemento 1 até o ultimo (end) de 2 em 2 
v[1:2:end] , u[1:2:end] 

([1,3,5,7,9,11,13,15],ASCIIString["a","c","e","g","i","l","n","p"])

In [301]:
# imprime os elementos a partir do elemento 5 até o ultimo (end) de 2 em 2 
v[5:2:end] ,u[5:2:end] 

([5,7,9,11,13,15],ASCIIString["e","g","i","l","n","p"])

In [302]:
# imprime na forma de um vetor coluna, os elementos de ordem primeiro, terceiro e sexto
v[[1, 3, 6]], u[[1, 3, 6]]

([1,3,6],ASCIIString["a","c","f"])

In [303]:
# imprime na forma de um vetor linha, os elementos de ordem primeiro, terceiro e sexto
v[[4 5 6]], u[[4 5 6]]

(
1x3 Array{Int64,2}:
 4  5  6,

1x3 Array{ASCIIString,2}:
 "d"  "e"  "f")

In [304]:
# cria um subconjunto coluna do vetor do elemento de posição 1 até o elemento de posição 10 
# tomando de 2 em 2 posições
sub(v, 1:3:10), sub(u, 1:2:10)

([1,4,7,10],ASCIIString["a","c","e","g","i"])

In [305]:
# posição final do vetor
endof(v), endof(u)

(15,15)

* **Concatenação de vetores **

In [306]:
# concatenação de vetores
tta = [1 2 3]
ttb = [4 5 6]

yya = [1,2,3]
yyb = [4,5,6]

z = [tta ttb]  # cria um vetor linha

x = [yya; yyb]  # cria uma vetor coluna

display(z)
display(x)

1x6 Array{Int64,2}:
 1  2  3  4  5  6

6-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6

* ** Ordenação de vetores **

O comando **sort** somente ordena o vetor e **sort!** ordena e substitui os dados do vetor pelos dados ordenados.

In [307]:
# ordenando vetor
va = rand(3)

println("vetor normal :",va)
println("vetor ordenado :",sort(va));

vetor normal :[0.81802692036074,0.528389203054072,0.304322354836857]
vetor ordenado :[0.304322354836857,0.528389203054072,0.81802692036074]


* **Filtro de dados**

In [308]:
vet = 1:5
filter(x -> x > 2, vet)

3-element Array{Int64,1}:
 3
 4
 5

In [309]:
vet_nomes = ["julia","sage","maxima","julia","scilab","julia"]
filter(x -> x != "julia", vet_nomes)

3-element Array{ASCIIString,1}:
 "sage"  
 "maxima"
 "scilab"

Forma compacta "julitronica" de filtrar dados. O ponto " . " serve para avaliar elemento-elemento do vetor

In [310]:
vet[vet.> 2]

3-element Array{Int64,1}:
 3
 4
 5

In [311]:
vet[vet.!= 3]

4-element Array{Int64,1}:
 1
 2
 4
 5

In [312]:
vet_nomes[vet_nomes.!="julia"]

3-element Array{ASCIIString,1}:
 "sage"  
 "maxima"
 "scilab"

* **Criar par de elementos**

O comando **zip** cria pares ordenados.

In [313]:
vet_a = [8.4 9.5 10.6]
vet_b = [8.1 9.2 10.3]

pares = zip(vet_a,vet_b)

Base.Zip2{Array{Float64,2},Array{Float64,2}}(1x3 Array{Float64,2}:
 8.4  9.5  10.6,1x3 Array{Float64,2}:
 8.1  9.2  10.3)

In [314]:
typeof(pares)

Base.Zip2{Array{Float64,2},Array{Float64,2}}

In [315]:
# Listar elementos do vetor a
pares.a

1x3 Array{Float64,2}:
 8.4  9.5  10.6

In [316]:
# Acessar elementos do vetor a
pares.a[2]

9.5

In [317]:
# Acessar elementos do vetor b
pares.b

1x3 Array{Float64,2}:
 8.1  9.2  10.3

In [318]:
# Acessar um par 
par = pares.a[2],pares.b[2]

(9.5,9.2)

In [319]:
# acessar elemento específico do par
par[1]

9.5

In [320]:
for i in pares
    print(i)    
end

(8.4,8.1)(9.5,9.2)(10.6,10.3)

outra forma usando tupla

In [11]:
pares_novo = ((8.4,8.1), (9.5, 9.2), (10.6, 10.3)) 

((8.4,8.1),(9.5,9.2),(10.6,10.3))

In [17]:
pares_novo[3]

(10.6,10.3)

In [18]:
pares_novo[3][1]

10.6

* ** Combinação e Permutação de elementos**

In [322]:
vetor = [1,2,3,4]
collect(combinations(vetor,2)) 

6-element Array{Array{Int64,1},1}:
 [1,2]
 [1,3]
 [1,4]
 [2,3]
 [2,4]
 [3,4]

In [323]:
collect(combinations(vetor,3)) 

4-element Array{Array{Int64,1},1}:
 [1,2,3]
 [1,2,4]
 [1,3,4]
 [2,3,4]

In [324]:
collect(permutations(vetor))

24-element Array{Array{Int64,1},1}:
 [1,2,3,4]
 [1,2,4,3]
 [1,3,2,4]
 [1,3,4,2]
 [1,4,2,3]
 [1,4,3,2]
 [2,1,3,4]
 [2,1,4,3]
 [2,3,1,4]
 [2,3,4,1]
 [2,4,1,3]
 [2,4,3,1]
 [3,1,2,4]
 [3,1,4,2]
 [3,2,1,4]
 [3,2,4,1]
 [3,4,1,2]
 [3,4,2,1]
 [4,1,2,3]
 [4,1,3,2]
 [4,2,1,3]
 [4,2,3,1]
 [4,3,1,2]
 [4,3,2,1]

#### ARRAY MULTIDIMENSIONAL / MATRIZES####

* **Criação e manipulação de Matrizes**

In [325]:
#Criando uma matriz 3x3 
Ma = [2 4 6;8 9 10;12 14 16]

3x3 Array{Int64,2}:
  2   4   6
  8   9  10
 12  14  16

In [326]:
# criando matriz de valores aleatórios
Mb = rand(3,3)

3x3 Array{Float64,2}:
 0.257468  0.941746   0.647588
 0.124783  0.967132   0.580631
 0.712656  0.0250734  0.626283

In [327]:
# criando uma matriz Mb 3x3 e testando se os elementos 2 e 15 fazem parte da matriz
Mc = [2 4 6;8 9 10;12 14 16]

(2 in Mb),(in(15, Mb))

(false,false)

In [328]:
# listar elentos impareres da matriz Mb
find(iseven, Mc)

8-element Array{Int64,1}:
 1
 2
 3
 4
 6
 7
 8
 9

In [329]:
# find(matriz,[elementos]) retorna a posição dos elementos de matriz "A"
display(Mc)
display(findin(Mc, [2,6]))

3x3 Array{Int64,2}:
  2   4   6
  8   9  10
 12  14  16

2-element Array{Int64,1}:
 1
 7

In [330]:
# testando
Mc[1], Mc[7]

(2,6)

In [331]:
# cria uma matriz formada pelos numeros de 1 a 9 sorteados aleatoriamente de tamanho 3x3
Mad = rand(1:9, 3, 3)

3x3 Array{Int64,2}:
 6  4  9
 3  4  6
 3  6  8

In [332]:
# jogos da mega sena parte 2: penultimate edition!
Mad = rand(1:60, 6, 6)

6x6 Array{Int64,2}:
 47  43  10  31  42   3
  8   4  31  14  17  52
 30   3  28  33   4   2
 46  51  28  32  58  30
 27   1  16  37  22   8
 45  36  52  12  59  32

* ** Ordenação de elementos **

In [333]:
# ordena as linhas 
sortrows(Mad)

6x6 Array{Int64,2}:
  8   4  31  14  17  52
 27   1  16  37  22   8
 30   3  28  33   4   2
 45  36  52  12  59  32
 46  51  28  32  58  30
 47  43  10  31  42   3

In [334]:
# ordena as colunas
sortcols(Mad)

6x6 Array{Int64,2}:
  3  10  31  42  43  47
 52  31  14  17   4   8
  2  28  33   4   3  30
 30  28  32  58  51  46
  8  16  37  22   1  27
 32  52  12  59  36  45

* ** Matrizes de zeros e uns **

In [335]:
# cria uma matriz 3x3 de zeros
Mz = zeros(3,3)

3x3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [336]:
# cria uma matriz 3x3 de uns
Mo = ones(3,3)

3x3 Array{Float64,2}:
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0

In [337]:
# cria uma matriz 3x3 identidade
Mi = eye(3, 3)

3x3 Array{Float64,2}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

* ** Preenchimento de matrizes **

In [338]:
# Cria uma matriz 3x3 preenchendo (fill) de strings "julia"
Mf = fill("julia", 3, 3)

3x3 Array{ASCIIString,2}:
 "julia"  "julia"  "julia"
 "julia"  "julia"  "julia"
 "julia"  "julia"  "julia"

In [339]:
# cria uma matriz repetindo a matriz nxm em x linhas e y colunas.
# o comando abaixo cria uma matriz repetindo a matriz de uns 2x2
# em 3 linhas e 3 colunas
repmat(ones(2), 3, 3)

6x3 Array{Float64,2}:
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0

In [340]:
# cria uma matriz com x*y elementos utilizando um vetor (pode ser range, linspace, rand e outros)
# o comando abaixo cria uma matriz de 5 linhas e 3 colunas a partir de um vetor de 15 elementos
reshape(1:15, 5, 3)

5x3 Array{Int64,2}:
 1   6  11
 2   7  12
 3   8  13
 4   9  14
 5  10  15

**Repetindo elementos para preencher matrizes**

Duas funções úteis para a criação de matrizes: são repmat (A, n, m) e repeat().

    A -> matriz
    n,m -> quantidade de repetições para n linhas e m colunas 

In [341]:
A = [1 2 3;4 5 6]

2x3 Array{Int64,2}:
 1  2  3
 4  5  6

In [342]:
# será repetido as linhas 3 vezes e 4 vezes as colunas.
repmat(A, 3, 4)

6x12 Array{Int64,2}:
 1  2  3  1  2  3  1  2  3  1  2  3
 4  5  6  4  5  6  4  5  6  4  5  6
 1  2  3  1  2  3  1  2  3  1  2  3
 4  5  6  4  5  6  4  5  6  4  5  6
 1  2  3  1  2  3  1  2  3  1  2  3
 4  5  6  4  5  6  4  5  6  4  5  6

* **Criação de matrizes a partir da concatenação de vetores **

In [343]:
v1 = [1 2 3]
v2 = [1,2,3]

display(v1)
display(v2)

1x3 Array{Int64,2}:
 1  2  3

3-element Array{Int64,1}:
 1
 2
 3

In [344]:
# matriz 1x6 
Mv1 = [v1 v1]

1x6 Array{Int64,2}:
 1  2  3  1  2  3

In [345]:
# matriz 3x2 
Mv2 = [v2 v2]

3x2 Array{Int64,2}:
 1  1
 2  2
 3  3

In [346]:
# matriz 2x3
Mv3 = [v1 ; v1]

2x3 Array{Int64,2}:
 1  2  3
 1  2  3

In [347]:
# ATENÇÃO: neste caso será criado um vetor
# devido a dimensão  Array{Int64,1}
Mv4 = [v2 ; v2]

6-element Array{Int64,1}:
 1
 2
 3
 1
 2
 3

* ** Concatenação de matrizes**

In [348]:
# criar as mastrizes
Mra = [1 2 3 ; 4 5 6 ]
Mrb = [0 0 0;1 1 1]

Mra, Mrb

(
2x3 Array{Int64,2}:
 1  2  3
 4  5  6,

2x3 Array{Int64,2}:
 0  0  0
 1  1  1)

In [349]:
# imprimir todos os elementos da segunda coluna da matriz Mra
display(Mra[:,2])

# imprimir todos os elementos da segunda linha da matriz Mrb
display(Mrb[2,:])

2-element Array{Int64,1}:
 2
 5

1x3 Array{Int64,2}:
 1  1  1

In [350]:
# concatenar 
display([Mra Mrb])

display([Mra;Mrb])

2x6 Array{Int64,2}:
 1  2  3  0  0  0
 4  5  6  1  1  1

4x3 Array{Int64,2}:
 1  2  3
 4  5  6
 0  0  0
 1  1  1

In [351]:
# criar uma matriz utilizando os elementos da segunda linha da matriz Mra
# e todos os elementos da matriz Mrb.
[Mra[:,2] Mrb]

2x4 Array{Int64,2}:
 2  0  0  0
 5  1  1  1

* **Filtro aplicado a uma matriz**

In [352]:
# criar uma matriz aleatória e cria o vetor
# contendo os elementos filtrados menores que 0.2
mat_num = rand(3,3)
display(mat_num)

filter(x -> x <= 0.2, mat_num)

3x3 Array{Float64,2}:
 0.578904  0.210068    0.268277 
 0.229334  0.00668847  0.0246584
 0.695281  0.484257    0.74226  

2-element Array{Float64,1}:
 0.00668847
 0.0246584 

Forma compacta de filtrar dados

In [353]:
# a instrução ".>" é necessária para comparar elemento por elemento
mat_num[mat_num.<0.2]

2-element Array{Float64,1}:
 0.00668847
 0.0246584 

## POLINOMIOS##

In [19]:
using SymPy
@syms x

(x,)

In [20]:
P = Poly(x^2 - 4, x)

Poly(x**2 - 4, x, domain='ZZ')

In [21]:
coeffs(P)

2-element Array{Any,1}:
  1
 -4

## TIPOS DEFINIDOS PELO PROGRAMADOR##

In [357]:
type Forca
    massa     ::Float64
    Aceleracao::Float64    
end

In [358]:
typeof(Forca)

DataType

In [359]:
objeto1 = Forca(5,0.1)

Forca(5.0,0.1)

In [360]:
typeof(objeto1)

Forca

In [361]:
fieldnames(objeto1)

2-element Array{Symbol,1}:
 :massa     
 :Aceleracao

In [362]:
objeto1.massa, objeto1.Aceleracao

(5.0,0.1)

In [363]:
type Aluno
    Nome    ::AbstractString
    Sexo    ::AbstractString
    Idade   ::Int64
    Endereco::AbstractString
end

In [364]:
J1 = Aluno("Julia","F",18,"Rua MIT,2001")

Aluno("Julia","F",18,"Rua MIT,2001")

In [365]:
typeof(J1)

Aluno

In [366]:
fieldnames(J1)

4-element Array{Symbol,1}:
 :Nome    
 :Sexo    
 :Idade   
 :Endereco

In [367]:
J1.Nome

"Julia"

In [368]:
J1.Idade

18

%%% Fim Tipos de Dados %%%