#TIPOS DE DADOS#

##NUMÉRICOS##

#### TIPOS INTEIROS:####

* Int8 — inteiros 8-bit com sinal variando de - 2^7 a 2^7 - 1.
* Int8 — inteiros 8-bit sem sinal variando de 0 a 2^8 - 1.
* Int16 — inteiros 16-bit com sinal variando de -2^15 a 2^15 - 1.
* Int16 — inteiros 16-bit sem sinal variando de 0 a 2^16 - 1.
* Int32 — inteiros 32-bit com sinal variando de -2^31 a 2^31 - 1.
* Int32 — inteiros 32-bit sem sinal variando de 0 a 2^32 - 1.
* Int64 — inteiros 64-bit com sinal variando de -2^63 a 2^63 - 1.
* Int64 — inteiros 64-bit sem sinal variando de 0 a 2^64 - 1.
* Int128 — inteiros 128-bit com sinal variando de -2^127 a 2^127 - 1.
* Int128 — inteiros 128-bit sem sinal variando de 0 a 2^128 - 1.
* Bool — valendo ou true (verdadeiro) ou false (falso), que correspondem numericamente a 1 ou 0, respectivamente.
* Char — um tipo numérico de 32 bits representando um caracter Unicode (veja Strings para mais detalhes).

####TIPOS PONTO FLUTUANTE:####

* Float32 — Números de ponto flutuante 32-bit seguindo o padrão IEEE 754.
* Float64 — Números de ponto flutuante 64-bit seguindo o padrão IEEE 754.

#### NUMEROS COMPLEXOS ####

Para definir, usa-se a parte real em conjunto com a parte imaginária im

In [3]:
1 + 2im

1 + 2im

In [5]:
(1 + 8im) + (2 - 3im)

3 + 5im

In [6]:
(1 + 8im) * (2 - 3im)

26 + 13im

In [7]:
(26 + 13im)^2

507 + 676im

In [8]:
real(1 + 2im)

1

In [9]:
imag(1 + 2im)

2

In [10]:
conj(1 + 2im)

1 - 2im

In [11]:
abs(1 + 2im)

2.23606797749979

##CONSTANTES##

In [37]:
pi, e, golden

(π = 3.1415926535897...,e = 2.7182818284590...,φ = 1.6180339887498...)

<strong>Declarando uma constante</strong><br>
Constantes, declarado como <strong>const</strong>, são variáveis imutáveis quanto ao tipo. Ou seja, podem mudar de valor (será dado um aviso) mas não podem mudar de tipo.


In [38]:
# variável "vel_luz" do tipo string

const vel_luz = "299792458"

"299792458"

In [39]:
# Alterando a variável para outro valor do mesmo tipo string. Será dado um aviso

const vel_luz = "30000000"

"30000000"

In [40]:
# Não é possível alterar o tipo da variável "vel_luz" para inteiro. Ocorrerá ero

const vel_luz = 30000000

LoadError: LoadError: invalid redefinition of constant vel_luz
while loading In[40], in expression starting on line 3

In [41]:
vel_luz

"30000000"

In [42]:
# saber o tipo da constante

typeof(vel_luz)

ASCIIString

##VARIÁVEIS##

<strong>Resetar todas as variáveis</strong>

Julia não reseta, de fato, as variáveis. Na verdade ele configura outro workspace.

In [43]:
workspace()

<strong>Trabalhando com variáveis</strong>

In [44]:
# Atribindo o valor 2 a variavel x

x = 2;

In [45]:
# Executando o calculo

x^2

4

In [46]:
# Variável literal

y = "so testando";

In [47]:
y

"so testando"

In [48]:
# Ao tentar utilizar uma variável nao declarada, ocorre um erro "Xvar not defined"

Xvar

LoadError: LoadError: UndefVarError: Xvar not defined
while loading In[48], in expression starting on line 3

In [49]:
# verificar o tipo da variável

typeof(x),typeof(y)

(Int64,ASCIIString)

In [50]:
# testar tipo

isa(x, Int64)

true

In [14]:
# construção de um complexo 

a = 2
b = 3.5

complex(a,b)

2.0 + 3.5im

<strong>Declarando  Várias variáveis ao mesmo tempo</strong>

In [51]:
# Declarando Várias variáveis

x = 5 ; 
y=10 ; 
z = "julia";

In [52]:
x,y,z

(5,10,"julia")

In [53]:
# Por padrão, será impresso somente a ultima linha, mas as variáveis internas estão acessíveis

w = begin
    x = 2
    y = 3
    x+y
    
end

5

In [54]:
# y do bloco de w

y

3

In [55]:
# outra forma

w = (x = 2; y = 3; x + y); 

w

5

<strong>Variáveis criadas </strong>

In [56]:
whos()

                          Base  28186 KB     Module
                          Core   3292 KB     Module
                      LastMain  34953 KB     Module
                          Main   3301 KB     Module
                             w      8 bytes  Int64
                             x      8 bytes  Int64
                             y      8 bytes  Int64
                             z     13 bytes  ASCIIString


## STRING##

Convertendo uma string em uma expressão matemática

In [1]:
string_formula = "x^2 + 1"

y = parse(string_formula)

:(x ^ 2 + 1)

In [2]:
typeof(y)

Expr

In [3]:
x = 0

eval(y)

1

<strong>CONVERSÃO DE TIPOS</strong>

<div style="text-align: justify;">Tabela de Tipos<br>
</div>
<table style="text-align: left; width: 271px; height: 304px;" border="1"
cellpadding="2" cellspacing="2">
<tbody>
<tr>
<td style="vertical-align: top;">a<br>
</td>
<td style="vertical-align: top;">a<br>
</td>
</tr>
<tr>
<td style="vertical-align: top;">a<br>
</td>
<td style="vertical-align: top;">a<br>
</td>
</tr>
<tr>
<td style="vertical-align: top;">a<br>
</td>
<td style="vertical-align: top;">a<br>
</td>
</tr>
<tr>
<td style="vertical-align: top;">a<br>
</td>
<td style="vertical-align: top;">a<br>
</td>
</tr>
<tr>
<td style="vertical-align: top;">a<br>
</td>
<td style="vertical-align: top;">a<br>
</td>
</tr>
<tr>
<td style="vertical-align: top;">a<br>
</td>
<td style="vertical-align: top;">a<br>
</td>
</tr>
<tr>
<td style="vertical-align: top;">a<br>
</td>
<td style="vertical-align: top;">a<br>
</td>
</tr>
<tr>
<td style="vertical-align: top;">a<br>
</td>
<td style="vertical-align: top;">a<br>
</td>
</tr>
<tr>
<td style="vertical-align: top;">a<br>
</td>
<td style="vertical-align: top;">a<br>
</td>
</tr>
</tbody>
</table>

In [60]:
a = 8;
b = 8.0;
c = "julia"

a,b,c

(8,8.0,"julia")

In [61]:
typeof(a), typeof(b), typeof(c)

(Int64,Float64,ASCIIString)

In [62]:
d = Float64(a); e = convert(Int,b)

d , e

(8.0,8)

In [63]:
typeof(d),typeof(e)

(Float64,Int64)

##TUPLA##
Uma tupla é uma seqüência ordenada de elementos, como uma matriz. Uma tupla é representado por parênteses e vírgulas, em vez dos colchetes usados por matrizes. Tuplas são principalmente indicadas para agrupamento de comprimento fixo pequenas - eles são usados em todos os lugares em Julia, por exemplo, como listas de argumentos e de retorno de vários valores de funções.

A diferença importante entre matrizes e tuplas é que tuplas são <strong>imutáveis</strong>. Muitas funções de matrizes também pode ser usado em tuplas.

In [4]:
t1 = (1,2,3)

(1,2,3)

In [5]:
typeof(t1)

Tuple{Int64,Int64,Int64}

In [2]:
t2 = (1,2,"Julia")

(1,2,"Julia")

In [6]:
typeof(t2)

Tuple{Int64,Int64,ASCIIString}

## DICIONÁRIO ##

In [17]:
d1 = Dict([("a", 1), ("b", 2),("c","Julia")])

Dict{ASCIIString,Any} with 3 entries:
  "c" => "Julia"
  "b" => 2
  "a" => 1

In [15]:
d2 = Dict("a"=>1, "b"=>2, "c" =>"Julia")

Dict{ASCIIString,Any} with 3 entries:
  "c" => "Julia"
  "b" => 2
  "a" => 1

## SEQUENCIAS##

In [7]:
# range(inicio, passo, tamanho)

vs1 = range(1, 0.1, 3)

typeof(vs1)

FloatRange{Float64}

In [8]:
# so vai até 3, se tentar o vs[4] ocorre erro

vs1[3]

1.2

In [9]:
vs2 = 1:0.1:3

typeof(vs2)

FloatRange{Float64}

In [11]:
vs2[3]

1.2

## LISTAS, ARRAY, VETORES E MATRIZES ##

###LISTAS E ARRAY###

Um array é uma coleção ordenada de elementos. É muitas vezes indicada com colchetes e itens separados por vírgulas. É possível criar arrays vazios ou arrays que armazenam valores de tipos diferentes ou restritas a valores de um tipo específico.

Em Julia, os arrays são usados para listas, vetores, tabelas e matrizes. Um array unidimensional atua como um vector ou uma lista. Uma array 2D pode ser utilizada como uma tabela ou matriz.

In [32]:
A1 = Array(Int,5)

5-element Array{Int64,1}:
      8589934594
      2147483649
               0
               0
 140283705895232

In [35]:
A2 = Array(AbstractString,5)

5-element Array{AbstractString,1}:
 #undef
 #undef
 #undef
 #undef
 #undef

#### ARRAY UNIDIMENSIONAL/VETORES E ARRAY MULTIDIMENSIONAL/MATRIZES####

** Array Unidimensional / Vetores **

In [64]:
# Resetar todas a variáveis

workspace()

<strong>Criação de vetores e acesso a dados em um vetor</strong><br> Para acessar um vetor utiliza a forma vetor[indice]

In [65]:
# vetor vazio

a = []

0-element Array{Any,1}

In [66]:
# quantidade de elementos de um vetor ou tamanho do vetor

length(a)

0

In [67]:
# adicionando o elemento 10 e em seguida os elementos -2, -4, 500 e 100 ao final do vetor

push!(a,10), push!(a,-2,-4,500,100)

(Any[10,-2,-4,500,100],Any[10,-2,-4,500,100])

In [68]:
# retirando elemento do final do vetor 

pop!(a), a

(100,Any[10,-2,-4,500])

In [69]:
# retirar elemento de uma posição específica. deleteat!(vetor,posição)

deleteat!(a,3)

3-element Array{Any,1}:
  10
  -2
 500

In [70]:
# fatia o vetor na forma splice!(vetor,faixa de posições ou apenas uma posição,novo_vetor). 
# No exemplo, o vetor [100 1] é colocado na posição 2

splice!(a, 2, [100 1]),a

(-2,Any[10,100,1,500])

In [71]:
# fatia o vetor na forma splice!(vetor,faixa de posições ou apenas uma posição,novo_vetor).
# no exemplo, o vetor [50 -50] é inserido entre as posições 2 a 4

splice!(a, 2:4, [50 -50]), a

(Any[100,1,500],Any[10,50,-50])

In [72]:
# Aumentar o tamanho do vetor em 10 posições #undef significa tipo indefinido

resize!(a,10)

10-element Array{Any,1}:
  10   
  50   
 -50   
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef

In [73]:
# Limpar o vetor 

empty!(a), a

(Any[],Any[])

In [74]:
# vetor de tipo definido com dados gerados aleatoriamente

b = Array(Int64,1,3 )

1x3 Array{Int64,2}:
 140372721103520  140372712478224  140372721103536

In [75]:
# dimensoes do vetor

size(b)

(1,3)

In [76]:
# quantidade de elementos de um vetor ou tamanho do vetor

length(b)

3

In [77]:
# push e pop nao serve para vetores linha! Funciona somente para vetores coluna.

push!(b,10), pop!(b)

LoadError: LoadError: MethodError: `push!` has no method matching push!(::Array{Int64,2}, ::Int64)

You might have used a 2d row vector where a 1d column vector was required.
Note the difference between 1d column vector [1,2,3] and 2d row vector [1 2 3].
You can convert to a column vector with the vec() function.
Closest candidates are:
  push!(::Any, ::Any, !Matched::Any)
  push!(::Any, ::Any, !Matched::Any, !Matched::Any...)
  push!(!Matched::Array{Any,1}, ::ANY)
  ...
while loading In[77], in expression starting on line 3

In [78]:
# tipo do vetor e tipo dos elementos do vetor

typeof(b),eltype(b)

(Array{Int64,2},Int64)

In [79]:
# acessar dado e um vetor

b[2]

140372712478224

In [80]:
# vetor de tipo indefinido vazio

c = cell(1, 3)

1x3 Array{Any,2}:
 #undef  #undef  #undef

In [81]:
# vetor de zeros

d = zeros(5)

5-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0

In [82]:
# vetor de uns

e = ones(5)

5-element Array{Float64,1}:
 1.0
 1.0
 1.0
 1.0
 1.0

In [83]:
# Criando um vetor de 1 a 2 com 5 partes

x = linspace(1, 2, 5);

x   # hehehe nao mostra os dados

linspace(1.0,2.0,5)

In [84]:
# dimensoes do vetor

size(x)

(5,)

In [85]:
# quantidade de elementos de um vetor ou tamanho do vetor

length(x)

5

In [86]:
# acessando dados no vetor x

x[1],x[2],x[3],x[4],x[5]

(1.0,1.25,1.5,1.75,2.0)

In [87]:
# Criando um vetor de 1 a 2 de 0.25 em 0.25

y = collect(1:0.25:2) 

5-element Array{Float64,1}:
 1.0 
 1.25
 1.5 
 1.75
 2.0 

In [88]:
# dimensoes do vetor

size(y)

(5,)

In [89]:
# quantidade de elementos de um vetor ou tamanho do vetor

length(y)

5

In [90]:
# acessando dados no vetor y

y[1],y[2],y[3],y[4],y[5]

(1.0,1.25,1.5,1.75,2.0)

In [91]:
# semelhante ao linspace do MatLab

z = 1:0.25:2

1.0:0.25:2.0

In [92]:
# acessando dados no vetor z

z[1],z[2],z[3],z[4],z[5]

(1.0,1.25,1.5,1.75,2.0)

In [93]:
# cria um vetor de 5 elementos preenchidos com a letra a string julia

t = fill("julia", 1, 5)

1x5 Array{ASCIIString,2}:
 "julia"  "julia"  "julia"  "julia"  "julia"

In [94]:
# tipo do vetor e tipo dos elementos do vetor

typeof(t),eltype(t)

(Array{ASCIIString,2},ASCIIString)

In [95]:
# quantidade de elementos de um vetor ou tamanho do vetor

length(t)

5

In [96]:
# resize!(vetor,x) Redefine um vetor para um tamanho "x". 
# Se o tamanho do vetor for menor que o tamanho "x", é feito o preenchimento adicional 
# de mais elementos aleatoriamente ao final do vetor.

# y é um vetor coluna de 1 até 2 de 0.5 em 0.5, de tamanho 4.

y = collect(1:0.5:2); 

p = resize!(y,5)

5-element Array{Float64,1}:
 1.0
 1.5
 2.0
 0.0
 0.0

In [97]:
# vetor coluna

a = [1, 2, 3, 4, 5]

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [98]:
# dimensoes do vetor

size(a) 

(5,)

In [99]:
# vetor coluna

aa = [1; 2; 3; 4; 5]

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [100]:
# dimensoes do vetor

size(aa) 

(5,)

In [101]:
# Vetor Linha

b = [1 2 3 4 5]

1x5 Array{Int64,2}:
 1  2  3  4  5

In [102]:
# dimensoes do vetor

size(b) 

(1,5)

In [103]:
# transforma o vetor linha ou array (matrix de 1x5 (2 dimensoes)) em um vetor de uma dimensão

bb = vec(b)

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [104]:
# array de 2 dimensões e agora vetor de 1 dimensão

typeof(b), typeof(bb)

(Array{Int64,2},Array{Int64,1})

Acessos especiais

In [105]:
v = [1, 2, 3, 4, 5,6,7,8,9,10,11,12,13,14,15];

u = ["a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "l" "m" "n" "o" "p"];

In [106]:
# imprime os elementos a partir do elemento 1 até o ultimo (end) de 2 em 2 

v[1:2:end] , u[1:2:end] 

([1,3,5,7,9,11,13,15],ASCIIString["a","c","e","g","i","l","n","p"])

In [107]:
# imprime os elementos a partir do elemento 5 até o ultimo (end) de 2 em 2 

v[5:2:end] ,u[5:2:end] 

([5,7,9,11,13,15],ASCIIString["e","g","i","l","n","p"])

In [108]:
# imprime na forma de um vetor coluna, os elementos de ordem primeiro, terceiro e sexto

v[[1, 3, 6]], u[[1, 3, 6]]

([1,3,6],ASCIIString["a","c","f"])

In [109]:
# imprime na forma de um vetor linha, os elementos de ordem primeiro, terceiro e sexto

v[[4 5 6]], u[[4 5 6]]

(
1x3 Array{Int64,2}:
 4  5  6,

1x3 Array{ASCIIString,2}:
 "d"  "e"  "f")

In [110]:
# cria um subconjunto coluna do vetor do elemento de posição 1 até o elemento de posição 10 
# tomando de 2 em 2 posições

sub(v, 1:3:10), sub(u, 1:2:10)

([1,4,7,10],ASCIIString["a","c","e","g","i"])

In [111]:
# posição final do vetor

endof(v), endof(u)

(15,15)

In [112]:
# concatenação de vetores

tta = [1 2 3 ];
ttb = [4 5 6];

z = [tta ttb]   # cria um vetor linha
x = [tta ; ttb] # cria uma matriz 3x2

z, x

(
1x6 Array{Int64,2}:
 1  2  3  4  5  6,

2x3 Array{Int64,2}:
 1  2  3
 4  5  6)

In [113]:
# ordenando vetor

va = rand(5); 

println("vetor normal :",va);

println("vetor ordenado :",sort(va));

vetor normal :[0.796301710539036,0.6834555158617024,0.6957256257546232,0.6490609799857996,0.15923474562884565]
vetor ordenado :[0.15923474562884565,0.6490609799857996,0.6834555158617024,0.6957256257546232,0.796301710539036]


#### ARRAY MULTIDIMENSIONAL / MATRIZES####

**Criação e manipulação de Matrizes**

In [114]:
#Criando uma matriz 3x3 

M = [2 4 6;8 9 10;12 14 16]

3x3 Array{Int64,2}:
  2   4   6
  8   9  10
 12  14  16

In [115]:
# criando matriz de valores aleatórios

Ma = rand(3,3)

3x3 Array{Float64,2}:
 0.720527  0.419283  0.460826
 0.394008  0.132754  0.803992
 0.460456  0.681111  0.112315

In [116]:
# criando uma matriz Mb 3x3 e testando se os elementos 2 e 15 fazem parte da matriz

Mb = [2 4 6;8 9 10;12 14 16]

(2 in Mb),(in(15, Mb))

(true,false)

In [117]:
# listar elentos impareres da matriz Mb

find(iseven, Mb)

8-element Array{Int64,1}:
 1
 2
 3
 4
 6
 7
 8
 9

In [118]:
# devolve os índices dos elementos de matriz "A", onde os elementos podem ser encontrados:

println(Mb)

println()

println(findin(Mb, [2,6]))

[2 4 6
 8 9 10
 12 14 16]

[1,7]


In [119]:
# cria uma matriz formada pelos numeros de 1 a 9 sorteados aleatoriamente de tamanho 3x3

Mad = rand(1:9, 3, 3)

3x3 Array{Int64,2}:
 4  6  8
 1  2  1
 8  6  1

In [120]:
# jogos da mega sena parte 2: penultimate edition!

Mad = rand(1:60, 6, 6)

6x6 Array{Int64,2}:
 49  47  28   2  46  59
 20  58  54   8  60  20
 30  23   8  59  20   9
 59  54  41  51   2   5
 13  49  59  22  11   2
 59   5  51  50  23  17

In [121]:
# ordena as linhas 

sortrows(Mad)

6x6 Array{Int64,2}:
 13  49  59  22  11   2
 20  58  54   8  60  20
 30  23   8  59  20   9
 49  47  28   2  46  59
 59   5  51  50  23  17
 59  54  41  51   2   5

In [122]:
# ordena as colunas

sortcols(Mad)

6x6 Array{Int64,2}:
  2  28  46  47  49  59
  8  54  60  58  20  20
 59   8  20  23  30   9
 51  41   2  54  59   5
 22  59  11  49  13   2
 50  51  23   5  59  17

In [123]:
# Cria uma matriz 3x3 preenchendo (fill) de strings "julia"

Mf = fill("julia", 3, 3)

3x3 Array{ASCIIString,2}:
 "julia"  "julia"  "julia"
 "julia"  "julia"  "julia"
 "julia"  "julia"  "julia"

In [124]:
# cria uma matriz 3x3 de zeros

Mz = zeros(3,3)

3x3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [125]:
# cria uma matriz 3x3 de uns

Mo = ones(3,3)

3x3 Array{Float64,2}:
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0

In [126]:
# cria uma matriz 3x3 identidade

Mi = eye(3, 3)

3x3 Array{Float64,2}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

In [127]:
# cria uma matriz repetindo a matriz 3x3 .....

repmat(ones(3), 4, 2)

12x2 Array{Float64,2}:
 1.0  1.0
 1.0  1.0
 1.0  1.0
 1.0  1.0
 1.0  1.0
 1.0  1.0
 1.0  1.0
 1.0  1.0
 1.0  1.0
 1.0  1.0
 1.0  1.0
 1.0  1.0

In [128]:
# 

reshape(linspace(0, 100, 30), 10, 3)

10x3 Array{Float64,2}:
  0.0      34.4828   68.9655
  3.44828  37.931    72.4138
  6.89655  41.3793   75.8621
 10.3448   44.8276   79.3103
 13.7931   48.2759   82.7586
 17.2414   51.7241   86.2069
 20.6897   55.1724   89.6552
 24.1379   58.6207   93.1034
 27.5862   62.069    96.5517
 31.0345   65.5172  100.0   

<strong>Criação de matrizes a partir da concatenação de vetores</strong>

In [129]:
v1 = [1 2 3]
v2 = [1,2,3]

display(v1)
display(v2)

1x3 Array{Int64,2}:
 1  2  3

3-element Array{Int64,1}:
 1
 2
 3

In [130]:
# matriz 1x6 

Mv1 = [v1 v1]

1x6 Array{Int64,2}:
 1  2  3  1  2  3

In [131]:
# matriz 3x2 

Mv2 = [v2 v2]

3x2 Array{Int64,2}:
 1  1
 2  2
 3  3

In [132]:
# matriz 2x3

Mv3 = [v1 ; v1]

2x3 Array{Int64,2}:
 1  2  3
 1  2  3

In [133]:
# matriz 6x1 
Mv4 = [v2 ; v2]

6-element Array{Int64,1}:
 1
 2
 3
 1
 2
 3

** concatenação de matrizes**

In [134]:
Mra = [1 2 3 ; 4 5 6 ]; 
Mrb = [0 0 0;1 1 1];

Mra, Mrb

(
2x3 Array{Int64,2}:
 1  2  3
 4  5  6,

2x3 Array{Int64,2}:
 0  0  0
 1  1  1)

In [135]:
display([Mra Mrb])

display([Mra;Mrb])

2x6 Array{Int64,2}:
 1  2  3  0  0  0
 4  5  6  1  1  1

4x3 Array{Int64,2}:
 1  2  3
 4  5  6
 0  0  0
 1  1  1

In [136]:
# imprimir todos os elementos da segunda coluna da matriz Mra
display(Mra[:,2])

# imprimir todos os elementos da segunda linha da matriz Mrb
display(Mrb[2,:])

2-element Array{Int64,1}:
 2
 5

1x3 Array{Int64,2}:
 1  1  1

In [137]:
# 

[Mra[:,2] Mrb]

2x4 Array{Int64,2}:
 2  0  0  0
 5  1  1  1

Repeating elements to fill arrays

Two useful functions for creating arrays by repeating smaller ones are repmat() and repeat().

The syntax for the first is repmat(A, n, m), the source array is repeated by n times in the first dimension (rows), and m times in the second (columns).

You don't have to supply the second dimension, just supply how many rows you want:

In [138]:
repmat([1, 2, 3], 2, 3)

6x3 Array{Int64,2}:
 1  1  1
 2  2  2
 3  3  3
 1  1  1
 2  2  2
 3  3  3

## TIPOS DEFINIDOS PELO PROGRAMADOR##

In [8]:
type Forca
    massa     ::Float64
    Aceleracao::Float64    
end

In [9]:
typeof(Forca)

DataType

In [10]:
objeto1 = Forca(5,0.1)

Forca(5.0,0.1)

In [11]:
typeof(objeto1)

Forca

In [13]:
fieldnames(objeto1)

2-element Array{Symbol,1}:
 :massa     
 :Aceleracao

In [14]:
objeto1.massa, objeto1.Aceleracao

(5.0,0.1)

In [15]:
type Aluno
    Nome    ::AbstractString
    Sexo    ::AbstractString
    Idade   ::Int64
    Endereco::AbstractString
end

In [16]:
J1 = Aluno("Julia","F",18,"Rua MIT,2001")

Aluno("Julia","F",18,"Rua MIT,2001")

In [17]:
typeof(J1)

Aluno

In [19]:
fieldnames(J1)

4-element Array{Symbol,1}:
 :Nome    
 :Sexo    
 :Idade   
 :Endereco

In [20]:
J1.Nome

"Julia"

In [21]:
J1.Idade

18

%%% Fim Tipos de Dados %%%