# PROGRAMAÇÃO BÁSICA

## OPERADORES LÓGIGOS E BOLEANOS

Todos os operadores de comparação da JULIA retornam TRUE como verdade e FALSE como falso. Resumo:

* x <  y   verdade se x é menor que y.
* x <= y   verdade se x é menor ou igual a y.
* x >= y   verdade se x é maior ou igual a y.
* x >  y   verdade se x é maior que y.
* x == y   verdade se x é igual a y.
* x != y   verdade se x diferente de y
* x ~= y   verdade se x é diferente de y.

Principais operadores lógicos:

+ |, operador “ou”
+ &, operador “e”
+ ~ ou !, operador “não”

Uma expressão booleana é verdadeira se o resultado do cálculo das combinações lógicas das expressões booleanas for verdadeiro.

## ESTRUTURAS DE CONTROLE 

As principais estruturas de controle de fluxo em Julia são: `while, for, do, if, switch(opcional)`

### CONDICIONAL "SE" (IF) 

O comando  `sleep(tempo_segundos)` permite controlar o laço em um determinado tempo em segundos.Sintaxe Básica:

Apenas `SE`: ${~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~}$ `SE .. ENTÃO`:${~~~~~~~~~~~~~~~~~~~~~~~}$ `SE ..SENÃO ... ENTÃO`:
```julia
if condição                   if condição                if condição
   instruções                    instruções                 instruções
end                              else                       elseif
                                     instruções                 instruções
                              end                           elseif
                                                               :
                                                            else
                                                                instruções
                                                          end
                              
```

**Implementando Laços IF**

In [1]:
# Definindo os vetores X e Y
x = rand(0:10)

y = rand(0:10)

x,y

(9,9)

In [2]:
# se x < y será impresso a mensagem, se ocorrer x > y não será feito nada

if x < y
    println("x é menor que y")
end

Melhorando....

In [46]:
if x < y
    println("x é menor que y .","Valor de x: ",x," Valor de y: ",y)
else
    println("x é maior que y .","Valor de x: ",x," Valor de y: ",y)
end

x é maior que y .Valor de x: 10 Valor de y: 6


Melhorando mais....

In [12]:
if x < y
  println("x é menor que y .","Valor de x: ",x," Valor de y: ",y)
    
elseif x > y
  println("x é maior que y .","Valor de x: ",x," Valor de y: ",y)
    
else
    println("x é igual a y .","Valor de x: ",x," Valor de y: ",y)
end

x é menor que y .Valor de x: 5 Valor de y: 7


**Definindo funções descontínuas**
 
$~
f(x) = \begin{cases}
\cos(x) & x \geq 0\\
1 - e^{-1/x^2} & \text{x < 0}.
\end{cases}
~$

In [47]:
x  = rand(-1:1)

if x >= 0
    print("f = cos(x) = ",cos(x))
    
elseif x < 0
    print("f = exp(-1/x^2) = ",exp(-1/x^2))
    
end

f = exp(-1/x^2) = 0.36787944117144233

### CONDICIONAL "TROCAR" (SWITCH) 

Não existe um comando nativo para "case" ou "swith". Pode ser utilizado uma sequencia de "if..elseif..else" ou instalar o "case" do pacote "Switch". O comando  `sleep(tempo_segundos)` permite controlar o laço em um determinado tempo em segundos. Sintaxe Básica:

```julia
SE...SENÃO...ELSE                     SWITCH
if variável condição                  variável condição
    instruções                        @switch variável begin
    elseif variável condição          @case valor variável
        instruções                         instruções
    elseif variável condição               break
        instruções                    @case valor variável
    else 	                               instruções
        println("Não encontrado")          break
                                      @default
                                           println("Não encontrado")
                                      end
```

**Implementando SWITCH**

In [23]:
y = rand(0:4)

if  y == 0
    print( "y vale $y")
    
elseif y ==1 
    println("y vale $y")
    
elseif y == 2 
    println("y vale $y")
else
    println("Não encontrado.numero acima de 2")
end


y vale 2


In [4]:
using Switch

y = rand(0:4)

@switch y begin
    @case 0
    print( "y vale $y")
    break

    @case 1
    println("y vale $y")
    break

    @case 2
    println("y vale $y")
    break

    @default
    println("Não encontrado numero acima de 2")
end

LoadError: LoadError: UndefVarError: @switch not defined
while loading In[4], in expression starting on line 5

### REPETIÇÃO "PARA" (FOR) 

O comando  `sleep(tempo_segundos)` permite controlar o laço em um determinado tempo em segundos.

Sintaxe Básica:
```julia
for var = vetor/matriz/dicionário/conjunto # pode ser também var in semelhante ao  python 
    instruções var
end
```

**Implementando Laços FOR**

In [7]:
# Laço FOR aplicado a um VETOR
print("Valor da função sin(x)*cos(x/2)+x: \n\n")
x = [1.0, 2.0, 3.0, 4.0, 5.0] 

for i = 1:length(x)  # pode ser também x in 
    
    println(sin(x[i])*cos(x[i]/2) + x[i]," Para x = ",x[i])    
end

Valor da função sin(x)*cos(x/2)+x: 

1.7384602626041288 Para x = 1.0
2.491295496433882 Para x = 2.0
3.0099824344694786 Para x = 3.0
4.314940964313378 Para x = 4.0
5.768236060439348 Para x = 5.0


In [58]:
# Laço FOR aplicado a um VETOR
print("Valor da função sin(x)*cos(x/2)+x: \n\n")
x = [1.0, 2.0, 3.0, 4.0, 5.0] 

for i = x  # pode ser também x in 
    
    println(sin(i)*cos(i/2) + i," Para x = ",i)    
end

Valor da função sin(x)*cos(x/2)+x: 

1.7384602626041288 Para x = 1.0
2.491295496433882 Para x = 2.0
3.0099824344694786 Para x = 3.0
4.314940964313378 Para x = 4.0
5.768236060439348 Para x = 5.0


In [36]:
# Laço FOR aplicado a um VETOR
print("Valor da função sin(x)*cos(x/2)+x: \n\n")

for x = [1.0, 2.0, 3.0, 4.0, 5.0] # pode ser também x in vetor
    
    println(sin(x)*cos(x/2)+x," Para x = ",x)    
end

Valor da função sin(x)*cos(x/2)+x: 

1.7384602626041288 Para x = 1.0
2.491295496433882 Para x = 2.0
3.0099824344694786 Para x = 3.0
4.314940964313378 Para x = 4.0
5.768236060439348 Para x = 5.0


In [51]:
# Laço FOR aplicado a um VETOR e controle de tempo
print("Valor da função sin(x)*cos(x/2)+x: \n\n")

for x = [1.0 2.0 3.0 4.0 5.0] # pode ser também x in vetor
    
    println(sin(x)*cos(x/2)+x," Para x = ",x)
    sleep(1)                  # atraso de 1s
end

Valor da função sin(x)*cos(x/2)+x: 

1.7384602626041288 Para x = 1.0
2.491295496433882 Para x = 2.0
3.0099824344694786 Para x = 3.0
4.314940964313378 Para x = 4.0
5.768236060439348 Para x = 5.0


In [66]:
# Laço FOR aplicado a um VETOR reverso
print("Valor da função sin(x)*cos(x/2)+x: \n\n")

for x = 5:-1:1 # pode ser também x in vetor
    
    println(sin(x)*cos(x/2)+x," Para x = ",x)
    
end

Valor da função sin(x)*cos(x/2)+x: 

5.768236060439348 Para x = 5
4.314940964313378 Para x = 4
3.0099824344694786 Para x = 3
2.491295496433882 Para x = 2
1.7384602626041288 Para x = 1


In [59]:
# Laço FOR aplicado a um DICIONÁRIO
for i = Dict("Sage"=>10, "Julia"=>10, "Matlab"=>8) # ou i in Dict()
    println(i)
end

"Sage"=>10
"Matlab"=>8
"Julia"=>10


In [50]:
# Laço FOR aplicado a uma MATRIZ
mnum = [2 4;8 9]

linhas , colunas = size(mnum)

for i = 1:linhas    
    for j = 1:colunas        
        println("elemento da linha $i coluna $j é :",mnum[i,j])
    end
end

elemento da linha 1 coluna 1 é :2
elemento da linha 1 coluna 2 é :4
elemento da linha 2 coluna 1 é :8
elemento da linha 2 coluna 2 é :9


Melhorando....

In [62]:
linhas,colunas =  size(mnum)

for i = 1:linhas , j = 1:colunas
    println("elemento da linha $i coluna $j é :",mnum[i,j])
end 

elemento da linha 1 coluna 1 é :2
elemento da linha 1 coluna 2 é :4
elemento da linha 2 coluna 1 é :8
elemento da linha 2 coluna 2 é :9


Agora ficou like Python....

In [50]:
# lendo os elementos colunas por colunas 

for i = mnum
    println("elemento  $i")
end

elemento  2
elemento  8
elemento  4
elemento  9


In [52]:
# lendo os elementos linhas por linhas  (coloque aspas simples para inverter a matriz)

for i = mnum'
    println("elemento  $i")
end

elemento  2
elemento  4
elemento  8
elemento  9


**Break e Continue **

Sintaxe:
```julia
for var = vetor # pode ser var in 
    CONDIÇÃO var
        continue/break
    end
end
```

In [52]:
# para i de 1 até 10,
# se o resto da divisão i por 3 for diferente de zero, 
# então o loop é parado e retorna para o inicio do FOR
# e o loop será continuado até o final se o resto for 0

for i = 1:10
    if i % 3 != 0
        continue
    end
    println(i)
end


3
6
9


In [51]:
# para i de 1 até 10,
# se o resto da divisão i por 3 for igual a zero,então o loop é encerrado

for i = 1:10
    if i % 3 == 0
        break
    end
    println(i)
end

1
2


**Formas diversas do laço FOR**

In [28]:
for n = 1:2
    for m = 1:2
        println("$n * $m = $(n * m)")
    end
end 

1 * 1 = 1
1 * 2 = 2
2 * 1 = 2
2 * 2 = 4


In [29]:
for n = 1:2, m = 1:2
    println("$n * $m = $(n * m)")
end 

1 * 1 = 1
1 * 2 = 2
2 * 1 = 2
2 * 2 = 4


In [53]:
for x = 1:3, y = 1:3
    @show (sin(x)*y)
end

sin(x) * y = 0.8414709848078965
sin(x) * y = 1.682941969615793
sin(x) * y = 2.5244129544236893
sin(x) * y = 0.9092974268256817
sin(x) * y = 1.8185948536513634
sin(x) * y = 2.727892280477045
sin(x) * y = 0.1411200080598672
sin(x) * y = 0.2822400161197344
sin(x) * y = 0.4233600241796016


In [46]:
# (index, value) são nomes obrigatórios para funcionar o laço
lista = ["julia","python","sagemath","maxima","octave"]

for (index, value) =  enumerate(lista) # pode ser (index, value) in
           println("$index : $value")
end

1 : julia
2 : python
3 : sagemath
4 : maxima
5 : octave


In [71]:
# O comando zip agrupa os vetores Estado e Capital formando um conjunto zip
Estado   = ["Rio", "Piauí", "Goiás"]
Capital  = ["Rio de Janeiro", "Teresina", "Goiânia"]

for (i, j) = zip(Estado, Capital)
    println("A capital do $i é $j")
end

A capital do Rio é Rio de Janeiro
A capital do Piauí é Teresina
A capital do Goiás é Goiânia


**Teste de Benchmark - Método bruto de encontrar raízes de uma função **

In [54]:
# Método bruto de encontrar raízes de uma função
x = 1.0:0.0000001:10.0

@time begin

for k = x
    if abs(sin(k)*k^2 + cos(k)*k^2 + k + cos(sin(k))^2) < 0.00001
        println("Valor(y):",sin(k)*k^2 + cos(k)*k^2 + k + cos(sin(k))^2," . Raiz(x): ",k)        
    end
end
    
end

Valor(y):9.740306059824455e-6 . Raiz(x): 2.7049957
Valor(y):8.674175502876302e-6 . Raiz(x): 2.7049958
Valor(y):7.608044814588766e-6 . Raiz(x): 2.7049959
Valor(y):6.541914004620786e-6 . Raiz(x): 2.704996
Valor(y):5.475783068753515e-6 . Raiz(x): 2.7049961
Valor(y):4.409652002768105e-6 . Raiz(x): 2.7049962
Valor(y):3.3435208148802076e-6 . Raiz(x): 2.7049963
Valor(y):2.277389497873372e-6 . Raiz(x): 2.7049964
Valor(y):1.2112580597412048e-6 . Raiz(x): 2.7049965
Valor(y):1.4512649515463494e-7 . Raiz(x): 2.7049966
Valor(y):-9.210052007713188e-7 . Raiz(x): 2.7049967
Valor(y):-1.987137017267493e-6 . Raiz(x): 2.7049968
Valor(y):-3.0532689595519358e-6 . Raiz(x): 2.7049969
Valor(y):-4.119401031843495e-6 . Raiz(x): 2.704997
Valor(y):-5.185533225260386e-6 . Raiz(x): 2.7049971
Valor(y):-6.251665550238705e-6 . Raiz(x): 2.7049972
Valor(y):-7.317797995454178e-6 . Raiz(x): 2.7049973
Valor(y):-8.383930566346898e-6 . Raiz(x): 2.7049974
Valor(y):-9.450063268801046e-6 . Raiz(x): 2.7049975
Valor(y):-7.59078203

Foram encontradas 3 raízes: 2.70499, 5.35325 e 8.726468

.

**Resolução de Sistemas Lineares pelo Método de Gauss**

In [7]:
#********** PROGRAMA ELIMINAÇÃO PELO MÉTODO DE GAUSS ************* 

A = [4.1 -5.4 6.8;7.8 -8 -9;-17 4 1] # use numeros decimais mesmo que sejam inteiros
b = [1.0,2.0,3.0]                    # use numeros decimais mesmo que sejam inteiros

m = 0
al,ac = size(A)
x = zeros(al) # pré alocação da matrix x

#********** ESCALONAMENTO ************* 

# Aqui é escolhido o pivo e a matriz é escalonada

for k = 1:(al-1)
    
    for i = (k+1):al
       
        m = A[i,k]/(A[k,k])
        A[i,k] = 0
        for j = (k+1):al
            
            A[i,j] = A[i,j] - m*A[k,j]
            b[i] = b[i] - m*b[k]
        end
    end
end

# aqui os valores do vetor solução X são calculados

x[al] = b[al]/(A[al,al])

for k = (al-1):-1:1    
    s = 0
    for j = (k+1):al
       s = s+A[k,j]*x[j]
    end
       x[k] = (b[k]-s)/A[k,k]    
end

print(x)

[-0.555208,-0.57863,0.0223168]

#### LIST COMPREHENSIONS (LC)



Uma compreensão de lista é uma construção sintática disponível em algumas linguagens de programação para criação de uma lista baseada em listas existentes. Ela segue a forma da notação de definição de conjunto matemática (compreensão de conjunto) como forma distinta para uso de funções map e filter. **Fonte: wikipedia**. Sintaxe genérica:
```julia
[expressao_var for var = vetor] # resultado é um vetor.

[expressao_var for var_1 = vetor, var_2 = vetor] # resultado é uma matriz.

[expressao_var for var_1 = vetor for var_2 = vetor] # resultado é um vetor.

[expressao_var for var_1 = vetor if condição] # resultado é um vetor.
```

In [41]:
[x^2 for x = 1:5 ]

5-element Array{Int64,1}:
  1
  4
  9
 16
 25

In [54]:
# corresponde a FOR dentro de outro FOR e retorna os resultado em vetores linha
[x*y for x = 1:3, y = 3:6]

3×4 Array{Int64,2}:
 3   4   5   6
 6   8  10  12
 9  12  15  18

In [40]:
# corresponde a FOR dentro de outro FOR e retorna os resltado em um vetor
[x*y for x = 1:3 for y = 3:6]

12-element Array{Int64,1}:
  3
  4
  5
  6
  6
  8
 10
 12
  9
 12
 15
 18

In [53]:
x = [10, 11, 12, 13, 14, 15, 16, 17]

[ x[i] + x[i-1] for i = 2:length(x) ]

7-element Array{Int64,1}:
 21
 23
 25
 27
 29
 31
 33

In [48]:
# LC com filtro 
# Filtrar valores maiores que 4
# O ponto "." é necessáriopara comparar elemento por elemento

x = [1, 2, 3, 4, 5, 9, 25, 32, 55, 510]

[y*2 for y = x[x .> 4]]

6-element Array{Int64,1}:
   10
   18
   50
   64
  110
 1020

In [46]:
# LC com filtro 
# Filtrar valores maiores que 4
# O ponto "." é necessáriopara comparar elemento por elemento

x = [1, 2, 3, 4, 5, 9, 25, 32, 55, 510]

[y*2 for y = x if y > 4]

6-element Array{Int64,1}:
   10
   18
   50
   64
  110
 1020

In [18]:
# filtrar valores maiores que 4 e menores que 55
# O ponto "." é necessáriopara comparar elemento por elemento
x = [1, 2, 3, 4, 5, 9, 25, 32, 55, 510]

[y*2 for y = x[(x.> 4)&(x.< 55)]]

4-element Array{Int64,1}:
 10
 18
 50
 64

### REPETIÇÃO "ENQUANTO" (WHILE)

O comando  `sleep(tempo_segundos)` permite controlar o laço em um determinado tempo em segundos.
Sintaxe Básica:
```julia
while condição 
    instruções
end
```

**Implementando Laços WHILE**

In [43]:
# conta enquanto "a" menor ou igual a 5.
a = 0

while a <= 5    
    println(a)
    a = a + 1    
end

0
1
2
3
4
5


In [60]:
# conta enquanto "a" menor ou igual a 5.
a = 0
b = 1:5
while  a < length(b) 
    println(a)
    a = a + 1    
end

0
1
2
3
4


In [33]:
# controlando o laço com sleep
a = 0

while a <= 5   
    sleep(1)
    println(a)
    a = a+1    
end

0
1
2
3
4
5


**Continue e Break** 

```julia
while condição 
    CONDIÇÃO 
        break/continue
    end
end
```

In [16]:
# conta enquanto "a" menor ou igual a 5. 
# se "a" dividido por 3 for diferente de 0 para!

a = 0

while a <= 10    
    println(a)
    a = a + 1    
    if a % 3 == 0
        break
    end    
end

0
1
2


**Método da Bisseção**

In [45]:
"""
Metodo da Bisseccao

Calcula uma aproximação para uma raiz da função de f(x)

Entre os intervalo [ao,bo] e a tolerencia de erro daddo por tol.

adaptado de http://goo.gl/pQNh6z 

"""
a   = 1.5
b   = 3.0
tol = 0.0001
iteracao = 0

if (a^2 - 2*a)*(b^2 - 2*b) > 0 
        println("Não há raiz no intervalo")
        
    else
        x_medio = (a + b)/2
        err = abs(x_medio^2 - 2*x_medio)
        
        while err > tol
            println("interação: ", iteracao , " : ", x_medio, ", valor função: ",x_medio^2 - 2*x_medio)
            
            if (a^2 - 2*a)*(x_medio^2 - 2*x_medio) < 0 
                b = x_medio
            else
                a = x_medio
            end
            
            x_medio = (a + b)/2
            err = abs(x_medio^2 - 2*x_medio)
            iteracao = iteracao + 1
            
        end
        
    println("interação: ", iteracao , " : ", x_medio, ", valor função: ",x_medio^2 - 2*x_medio)
          
end

interação: 0 : 2.25, valor função: 0.5625
interação: 1 : 1.875, valor função: -0.234375
interação: 2 : 2.0625, valor função: 0.12890625
interação: 3 : 1.96875, valor função: -0.0615234375
interação: 4 : 2.015625, valor função: 0.031494140625
interação: 5 : 1.9921875, valor função: -0.01556396484375
interação: 6 : 2.00390625, valor função: 0.0078277587890625
interação: 7 : 1.998046875, valor função: -0.003902435302734375
interação: 8 : 2.0009765625, valor função: 0.0019540786743164062
interação: 9 : 1.99951171875, valor função: -0.0009763240814208984
interação: 10 : 2.000244140625, valor função: 0.0004883408546447754
interação: 11 : 1.9998779296875, valor função: -0.00024412572383880615
interação: 12 : 2.00006103515625, valor função: 0.00012207403779029846
interação: 13 : 1.999969482421875, valor função: -6.1034224927425385e-5


### REPETIÇÃO "FAÇA ATÉ QUE" (DO...UNTIL)

Sintaxe Básica:
```julia
comando_execução/função do
  instruções
  até que (condição)
end
```

**Implementando Laços DO..UNTIL**

In [147]:
# find retorna o indice do vetor quando encontrar o valor igual a 5
numeros = 1:0.1:20

find(numeros) do valor
    valor == 5
    
end

1-element Array{Int64,1}:
 41

In [95]:
numeros[41]

5.0

## FUNÇÕES ( function( ) ) 

Em Julia, uma função é um objeto que mapeia uma tupla de valores de argumentos de entrada e produz um ou vários valores de retorno. Como será visto em outros tópicos uma `function` é uma função do tipo genérica. Sintaxe:
```julia
function nome(var_1, var_2,..,var_n)
    expressoes_variaveis
    return valores_calculados
end
```
No caso de retorno mutiplo, `return` retorna uma tupla de valores. Sintaxe:
```julia
function nome(var_1, var_2,..,var_n)
   expressoes_variaveis
   return valores_calculados_1, valores_calculados_2 ...valores_calculados_n
end
```
`return` é necessário quando deseja-se manipular o valor calculado dentro da função. Se o objetivo é apenas mostrar o resultado podemos usar `print` ou `display`.

### FUNÇÕES DEFINIDAS

* **Função Dimensão Matriz**

In [1]:
# a função apenas imprime a dimensão da matriz
function fmatrixD(M)
    println("------------ inicio funcao -----------")
    
    display(M)    
        
    println("a dimensão da matriz é :",size(M))
    
    println("--------------- fim -----------------")
    
end

fmatrixD (generic function with 1 method)

In [2]:
fmatrixD([1 1 2 ; 4 8 9])

2×3 Array{Int64,2}:
 1  1  2
 4  8  9

------------ inicio funcao -----------
a dimensão da matriz é :(2,3)
--------------- fim -----------------


* **Função Cálculo da Área **

In [21]:
# a função calcula a área e faz o retorno multiplo de valores que podem ser manipulado na forma de uma tupla
function areaC(raio)
    areaCirc = pi * raio^2
    return "A área vale: ", round(areaCirc,5) 
end

areaC (generic function with 1 method)

In [22]:
area_circulo = areaC(3) # resultado é uma tupla(texto,valor)

("A área vale: ",28.27433)

In [23]:
# acesso valor da área
area_circulo[2]

28.27433

In [24]:
# manipulando o valor da área para 5 circulos
5*area_circulo[2]

141.37165

* **Função Raízes Equação de Báskara**

In [10]:
function fraiz(a,b,c)    
    delta = (b^2) - (4*a*c)    
    if delta < 0
        print("Delta negativo, raiz real impossivel de ser extraida.")        
    else                
        x1 = (-b + sqrt(delta)) / (2*a)
        x2 = (-b - sqrt(delta)) / (2*a)        
        return x1 , x2 # retorno multiplo na forma de uma tupla
    end
end

fraiz (generic function with 1 method)

In [11]:
# entre com os coeficientes da função do segundo grau

raizf = fraiz(2,-1,-3) # resultado é um vetor de dados

(1.5,-1.0)

In [12]:
# acesso segunda raiz

raizf[2]

-1.0

* **Função Método da Bissecção**

In [1]:
"""
Metodo da Bisseccao

Calcula uma aproximação para uma raiz da função de f(x)

Entre os intervalo [ao,bo] e a tolerencia de erro daddo por tol.

adaptado de http://goo.gl/pQNh6z 

"""
function fmetbissec(a,b,tol)
iteracao = 0
    if (a^2 - 2*a)*(b^2 - 2*b) > 0 
        println("Não há raiz no intervalo")
        
    else
        x_medio = (a + b)/2
        err = abs(x_medio^2 - 2*x_medio)
        
        while err > tol
            println("interação: ", iteracao , " : ", x_medio, ", valor função: ",x_medio^2 - 2*x_medio)
            
            if (a^2 - 2*a)*(x_medio^2 - 2*x_medio) < 0 
                b = x_medio
            else
                a = x_medio
            end
            
            x_medio = (a + b)/2
            err = abs(x_medio^2 - 2*x_medio)
            iteracao = iteracao + 1
            
        end
        
    println("interação: ", iteracao , " : ", x_medio, ", valor função: ",x_medio^2 - 2*x_medio)
    return x_medio
        
    end     
end

fmetbissec

In [14]:
raizf = fmetbissec(1.0, 2.5, 0.000001)

interação: 0 : 1.75, valor função: -0.4375
interação: 1 : 2.125, valor função: 0.265625
interação: 2 : 1.9375, valor função: -0.12109375
interação: 3 : 2.03125, valor função: 0.0634765625
interação: 4 : 1.984375, valor função: -0.031005859375
interação: 5 : 2.0078125, valor função: 0.01568603515625
interação: 6 : 1.99609375, valor função: -0.0077972412109375
interação: 7 : 2.001953125, valor função: 0.003910064697265625
interação: 8 : 1.9990234375, valor função: -0.0019521713256835938
interação: 9 : 2.00048828125, valor função: 0.0009768009185791016
interação: 10 : 1.999755859375, valor função: -0.0004882216453552246
interação: 11 : 2.0001220703125, valor função: 0.00024415552616119385
interação: 12 : 1.99993896484375, valor função: -0.00012206658720970154
interação: 13 : 2.000030517578125, valor função: 6.103608757257462e-5
interação: 14 : 1.9999847412109375, valor função: -3.0517345294356346e-5
interação: 15 : 2.0000076293945312, valor função: 1.5258847270160913e-5
interação: 16 : 1.

2.000000476837158

Para ler o cabeçalho da função use: ? metbissec

In [3]:
? fmetbissec

search:



Metodo da Bisseccao

Calcula uma aproximação para uma raiz da função de f(x)

Entre os intervalo [ao,bo] e a tolerencia de erro daddo por tol.

adaptado de http://goo.gl/pQNh6z 


* **Função série de Fibonacci Recursiva** 

Na matemática, a Sucessão de Fibonacci (também Sequência de Fibonacci), é uma sequência de números inteiros, começando normalmente por 0 e 1, na qual, cada termo subsequente corresponde a soma dos dois anteriores. A sequência recebeu o nome do matemático italiano Leonardo de Pisa, mais conhecido por Fibonacci , que descreveu, no ano de 1202, o crescimento de uma população de coelhos, a partir desta. Tal sequência já era no entanto, conhecida na antiguidade.

Os números de Fibonacci são, portanto, os números que compõem a seguinte sequência (sequência A000045 na OEIS):

    0,1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, ... .

Em termos matemáticos, a sequência é definida recursivamente pela fórmula abaixo, sendo o primeiro termo F1= 1:

${\displaystyle F_{n}=F_{n-1}+F_{n-2},}$

e valores iniciais

${\displaystyle F_{1}=1,\;F_{2}=1.}$

A sequência de Fibonacci tem aplicações na análise de mercados financeiros, na ciência da computação e na teoria dos jogos. Também aparece em configurações biológicas, como, por exemplo, na disposição dos galhos das árvores ou das folhas em uma haste, no arranjo do cone da alcachofra, do abacaxi, ou no desenrolar da samambaia.

In [30]:
function fiboR(n) 
    if n < 2 
        return n
    else
        fiboR(n-1) + fiboR(n-2)
    end
end

fiboR (generic function with 1 method)

In [31]:
@time fiboR(35)

  0.108047 seconds (800 allocations: 40.784 KB)


9227465

### ARGUMENTOS TIPADOS, ARGUMENTOS PADRONIZADOS, ARGUMENTOS NOMEADOS E DESPACHO MULTIPLO

**Argumentos Tipados**

In [19]:
function empuxo_0( v, d::Float64, g::Float64)
    println("Volume: ",v,"m³")
    println("Densidade: ",d,"kg/m³")
    println("A.gravidade: ",g,"m/s²")
    
    return v*d*g
end

empuxo_0 (generic function with 1 method)

In [22]:
empuxo_0(0.05,1.0,10.0)

Volume: 0.05m³
Densidade: 1.0kg/m³
A.gravidade: 10.0m/s²


0.5

In [25]:
# passando os tipos Float64, Float64 e Int64
empuxo_0(0.05,1.0,10)

LoadError: LoadError: MethodError: no method matching empuxo_0(::Float64, ::Float64, ::Int64)
Closest candidates are:
  empuxo_0(::Any, ::Float64, !Matched::Float64) at In[19]:2
while loading In[25], in expression starting on line 2

Observe que o erro `"no method matching empuxo_0(::Float64, ::Float64, ::Int64)"` significa que não há um método compatível com os argumentos passados em `(0.05 ::Float64, 1.0 ::Float64, 10 ::Int64`). O erro está no argumento `gravidade` que foi passado como inteiro e deve ser do tipo Float64. Julia informa o local do erro e tipo correto em  `!Matched::Float64`.
```
```

**Argumentos padronizados**

In [1]:
function empuxo_1( v, d = 1.0, g = 9.8)
    println("Volume: ",v,"m³")
    println("Densidade: ",d,"kg/m³")
    println("A.gravidade: ",g,"m/s²")
    
    return v*d*g
end

empuxo_1 (generic function with 3 methods)

In [2]:
empuxo_1(0.05,1.0,10)

Volume: 0.05m³
Densidade: 1.0kg/m³
A.gravidade: 10m/s²


0.5

In [6]:
# se não for passado nenhum parâmetro a função utiliza os valores padrões
empuxo_1(0.05)

Volume: 0.05m³
Densidade: 1.0kg/m³
A.gravidade: 9.8m/s²


0.49000000000000005

In [5]:
# a ordem dos argumentos importa
empuxo_1(0.05,10,1.0)

Volume: 0.05m³
Densidade: 10kg/m³
A.gravidade: 1.0m/s²


0.5

Observe que neste ultimo exemplo a ordem dos elementos é importante e embora o valor calculado esteja certo, os valores das variáveis estão trocados.
```
```

**Argumentos Nomeados**

In [50]:
function empuxo_2( v; d = 1.0, g = 9.8)
    println("Volume: ",v,"m³")
    println("Densidade: ",d,"kg/m³")
    println("A.gravidade: ",g,"m/s²")
    
    return d*g*v
end

empuxo_2 (generic function with 1 method)

In [52]:
# a ordem dos argumentos não importa
empuxo_2(0.5, g = 10 , d = 0.9)

Volume: 0.5m³
Densidade: 0.9kg/m³
A.gravidade: 10m/s²


4.5

In [30]:
# a ordem dos argumentos não importa
empuxo_2(0.5 , d = 0.9 , g = 10)

Volume: 0.5m³
Densidade: 0.9kg/m³
A.gravidade: 10m/s²


4.5

In [14]:
# se não for passado nenhum parâmetro a função utiliza os valores padrões
empuxo_2(0.5)

4.9

In [53]:
# só é possível passar parâmetros indicando o nome das variáveis e valor
empuxo_2(0.5, 0.9 , 10)

LoadError: LoadError: MethodError: no method matching empuxo_2(::Float64, ::Float64, ::Int64)
Closest candidates are:
  empuxo_2(::Any; d, g) at In[50]:2
while loading In[53], in expression starting on line 2

### IMPORTANDO FUNÇÕES GRAVADAS EM ARQUIVOS

O código deve ser escrito em um arquivo com a extensão ".jl" e importado usando a função **include("arquivo.jl")**. É possível colocar várias funções (nomes diferentes) em um arquivo e fazer a importação com o **include("arquivo.jl")**. As funções importadas serão executadas pelo nome.

In [60]:
include("ffiboR_JL.jl")

ffiboR_JL (generic function with 1 method)

In [61]:
@time ffiboR_JL(40)

  0.932148 seconds (697 allocations: 37.835 KB)


102334155

In [62]:
? ffiboR_JL

search: ffiboR_JL



Função calcula serie de fibonacci

ffiboR_JL(valor)


### CONTROLANDO A EXECUÇÃO DE FUNÇÕES (TASKS)

Julia possui um recurso de controle de fluxo chamado `Task` (Tarefas) que permite que os cálculos de uma função sejam suspensos e reiniciados de forma interativa. Esse recurso às vezes é chamado por outros nomes, como co-rotinas simétricas, segmentos leves, multitarefa cooperativa ou continuações one-shot. `Tasks` são ótimos quando é importante obter um valor de um laço que não sabemos o fim. Sintaxe:

Criar 
```julia
function nome_tarefa(argumentos)
    produce(instruções)
end

var = @task nome_tarefa(argumentos)
```
Executar
```julia
consume(var)
```

In [13]:
function teste_task(i)
    for n = 1:i
        produce([x^2 for x = 1:n])
    end
    produce("Fim Tarefa")
end

teste_task (generic function with 1 method)

In [14]:
teste = @task teste_task(3)

Task (runnable) @0x00007fddfdabb5b0

In [15]:
consume(teste)

1-element Array{Int64,1}:
 1

In [16]:
consume(teste)

2-element Array{Int64,1}:
 1
 4

In [17]:
consume(teste)

3-element Array{Int64,1}:
 1
 4
 9

In [18]:
consume(teste)

"Fim Tarefa"

**% FIM PROGRAMAÇÃO BÁSICA %**