# ALGEBRA LINEAR

## VETORES 

### CRIAÇÃO DE VETORES E ACESSO A ELEMENTOS

* ** Vetor Linha **

Vetores Linhas são vetores Bidimensionais, **Array{Tipo_dado,2}**, ou seja são na verdade uma matriz.

In [128]:
v_linha = [1 2 3 4 5] 

v_linha

1x5 Array{Int64,2}:
 1  2  3  4  5

* ** Vetor Coluna **

Vetores Linhas são vetores Unidimensionais, **Array{Tipo_dado,1}**.

In [129]:
v_coluna1 = [1;2;3;4;5]

v_coluna1

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [130]:
v_coluna2 = [1,2,3,4,5]

v_coluna2

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [131]:
# collect(inicio,passo, fim)

collect(0:2:10)

6-element Array{Int64,1}:
  0
  2
  4
  6
  8
 10

In [132]:
collect(10:-2:0)

6-element Array{Int64,1}:
 10
  8
  6
  4
  2
  0

In [133]:
# vetor criado a partir de uma função

vecf = [i^2 + 2*i  for i in 1:4]

4-element Array{Int64,1}:
  3
  8
 15
 24

* ** Acessar elementos do vetor **

In [134]:
v_linha[2]

2

In [135]:
v_coluna1[2]

2

In [136]:
# listar a partir do terceiro elemento até o fim

v_linha[3:end]

3-element Array{Int64,1}:
 3
 4
 5

### OPERAÇÕES COM VETORES

* ** Soma de vetores **

In [137]:
v = [1, 2, 3]
u = [4, 5, 6]

u+v

3-element Array{Int64,1}:
 5
 7
 9

* **Subtração **

$[4-1 ~~ 5-2 ~~  6-3]$ e $[1-3 ~~  2-5 ~~  3-6]$

In [138]:
v = [1, 2, 3]
u = [4, 5, 6]

display(u-v)

display(v-u)

3-element Array{Int64,1}:
 3
 3
 3

3-element Array{Int64,1}:
 -3
 -3
 -3

### OPERAÇÕES COM NUMEROS ESCALARES

* ** Multiplicação por escalar ** 

$[1x2 ~~ 2x2 ~~ 3x2]$

In [139]:
v = [1, 2, 3]

2*v

3-element Array{Int64,1}:
 2
 4
 6

* ** Multiplicação elemento por elemento entre vetores** 

$[1x4 ~~ 2x5 ~~ 3x6]$

In [140]:
v = [1, 2, 3]
u = [4, 5, 6]

v.*u

3-element Array{Int64,1}:
  4
 10
 18

* **Multiplicação elemento por elemento entre vetores**

$[1x4 ~~ 2x5 ~~ 3x6]$ pelo map()


In [141]:
map(*, v, u)

3-element Array{Int64,1}:
  4
 10
 18

* **Divisão por escalar**

In [142]:
# [1/2, 2/2, 3/2]

v = [1, 2, 3]

v/2

3-element Array{Float64,1}:
 0.5
 1.0
 1.5

In [143]:
# Divisão elemento por elemento entre vetores [1/4, 2/5, 3/6]

v = [1, 2, 3]
u = [4, 5, 6]

v./u

3-element Array{Float64,1}:
 0.25
 0.4 
 0.5 

In [144]:
# Divisão elemento por elemento entre vetores [1/4, 2/5, 3/6] pelo map()

map(/, v, u)

3-element Array{Float64,1}:
 0.25
 0.4 
 0.5 

* ** Potencia por escalar**

In [145]:
# Potencia elemento por elemento [1^2 2^2 3^2]

v = [1 2 3]

v.^2

1x3 Array{Int64,2}:
 1  4  9

In [146]:
# Potencia elemento por elemento entre vetores [1^4 2^5 3^6]

v = [1, 2, 3]
u = [4, 5, 6]

v.^u

3-element Array{Int64,1}:
   1
  32
 729

In [147]:
# Potencia elemento por elemento entre vetores [1^4, 2^5, 3^6] pelo map()

map(^, v,u)

3-element Array{Int64,1}:
   1
  32
 729

### TRANSPOSIÇÃO DE UM VETOR 

Veja que a transposição altera o tipo do vetor de Unidimensional(Array{Tipo_dado,1}) para Bidimensional(Array{Tipo_dado,2}) ou o contrário

In [148]:
display(v)

display(transpose(v))

display(v')

3-element Array{Int64,1}:
 1
 2
 3

1x3 Array{Int64,2}:
 1  2  3

1x3 Array{Int64,2}:
 1  2  3

### VETOR ALEATORIO 

Para criar um vetor de dados aleatórios entre 0 e 1 use:
```julia
rand(coluna) 
```
O array criado será do tipo **Array{Float64,1}**

In [149]:
display(rand(4)) 

display(rand(5))

4-element Array{Float64,1}:
 0.783488
 0.539087
 0.739654
 0.510189

5-element Array{Float64,1}:
 0.350334
 0.522717
 0.356752
 0.73157 
 0.236853

**CUIDADO**: é possível definir rand(coluna, linha). Dessa forma o vetor será bidimensional do tipo **Array{Float64,2}**. Ex: **rand(1,5)** cria o vetor bidimensional de 1 linha e 5 colunas

### VALORES DE  Max e Min DE UM VETOR

In [150]:
# Valor máximo do vetor

v = [1, 5, -9]

maximum(v)

5

In [151]:
# Valor máximo de um vetor e indice

valor_max, indice_max = findmax(v)

(5,2)

In [152]:
# valores extremos de um vetor: minimo e máximo simultâneo.

extrema(v)

(-9,5)

In [153]:
# Valor mínimo de um vetor

minimum(v)

-9

In [154]:
# Valor minimo de um vetor e indice

valor_min, indice_min = findmin(v)

(-9,3)

In [155]:
v = [1, 2, 3]
u = [4, 5, 6]

dot(v,u), dot(u,v)

(32,32)

### PRODUTO INTERNO E EXTERNO ENTRE VETORES 

In [156]:
# Produto interno: somente vetores coluna. aqui o uso do transpose ou v' nao funciona
# caso use vetores linha, transforme - o em coluna com vec(vetor_linha)

v = [1, 2, 3]
u = [4, 5, 6]

dot(v,u), dot(u,v)

(32,32)

In [157]:
# Produto externo ou vetorial

cross(v,u), cross(u,v)

([-3,6,-3],[3,-6,3])

## MATRIZES

### CRIAÇÃO DE MATRIZES E ACESSO A ELEMENTOS

* ** Criação de uma matrix **

In [158]:
# Mais comum 
Ma1 = [1 2 3;4 5 6]

2x3 Array{Int64,2}:
 1  2  3
 4  5  6

In [159]:
# concatenação de vetores linha
Ma2 = [[1 2 3 ];[4 5 6 ]]

2x3 Array{Int64,2}:
 1  2  3
 4  5  6

In [1]:
# concatenação de vetores colunas
Ma3 = [[1, 2, 3 ] [4, 5, 6 ]]

3x2 Array{Int64,2}:
 1  4
 2  5
 3  6

In [2]:
# utilizando uma LC
Ma4 = [i^j for i in 1:4, j in 1:7]

4x7 Array{Int64,2}:
 1   1   1    1     1     1      1
 2   4   8   16    32    64    128
 3   9  27   81   243   729   2187
 4  16  64  256  1024  4096  16384

* **Acessando elementos da matriz **

In [161]:
# Elemento da 1ª Linha e 2ª coluna

Ma1[1,2]

2

In [162]:
# Todos os elementos da segunda linha

Ma1[2,:]

1x3 Array{Int64,2}:
 4  5  6

In [163]:
# Todos os elementos da segunda coluna

Ma1[:,2]

2-element Array{Int64,1}:
 2
 5

In [164]:
# alterando o valor de um elemento da matriz

Ma1[1,1] = 1000

Ma1

2x3 Array{Int64,2}:
 1000  2  3
    4  5  6

* ** Redimensionar matrzes **

In [165]:
# Cria uma matriz a partir de um vetor coluna na forma reshape([vetor],linha,coluna)

Mra = reshape([1,2,3,4,5,6], 3,2)

Mrb = reshape([1,2,3,4,5,6], 2,3)

display(Mra) 

display(Mrb)

3x2 Array{Int64,2}:
 1  4
 2  5
 3  6

2x3 Array{Int64,2}:
 1  3  5
 2  4  6

### OPERAÇÕES COM MATRIZES

* ** Soma de matrizes **

In [171]:
Ma = [1 2 3; 4 5 6]
Mb = [4 5 6; 7 8 9]

Ma + Mb

2x3 Array{Int64,2}:
  5   7   9
 11  13  15

* ** Subtração de matrizes**

In [172]:
Ma = [1 2 3; 4 5 6]
Mb = [4 5 6; 7 8 9]

Ma - Mb

2x3 Array{Int64,2}:
 -3  -3  -3
 -3  -3  -3

### OPERAÇÕES COM NUMEROS ESCALARS 

* **Multiplicação por escalar**

In [173]:
Ma = [1 2 3; 4 5 6]

2*Ma

2x3 Array{Int64,2}:
 2   4   6
 8  10  12

* **Multiplicação elemento por elemento entre vetores **

$[1x4  ~ 2x5 ~  3x6; 4x7 ~  5x8 ~  6x9]$

In [174]:
Ma = [1 2 3; 4 5 6]
Mb = [4 5 6; 7 8 9]

Ma.*Mb

2x3 Array{Int64,2}:
  4  10  18
 28  40  54

* ** Divisão por escalar**

In [175]:
Ma = [1 2 3; 4 5 6]

Ma/2

2x3 Array{Float64,2}:
 0.5  1.0  1.5
 2.0  2.5  3.0

* ** Divisão elemento por elemento entre vetores $[1/4  ~  2/5 ~  3/6; 4/7 ~  5/8 ~  6/9]$ **

In [176]:
Ma = [1 2 3; 4 5 6]
Mb = [4 5 6; 7 8 9]

Ma./Mb

2x3 Array{Float64,2}:
 0.25      0.4    0.5     
 0.571429  0.625  0.666667

* ** Potencia elemento por elemento $[1^2 ~ 2^2 ~ 3^2; 4^2  ~ 5^2 ~  6^2]$ **

In [177]:
Ma = [1 2 3; 4 5 6]

Ma.^2

2x3 Array{Int64,2}:
  1   4   9
 16  25  36

* ** Potencia elemento por elemento entre vetores $[1^4 ~  2^5 ~  3^6; 4^7 ~  5^8 ~  6^9]$ **

In [178]:
Ma = [1 2 3; 4 5 6]
Mb = [4 5 6; 7 8 9]

Ma.^Mb

2x3 Array{Int64,2}:
     1      32       729
 16384  390625  10077696

### TRANSPOSIÇÃO DE MATRIZES 

In [179]:
Ma = [1 2 3; 4 5 6]

transpose(Ma), Ma'

(
3x2 Array{Int64,2}:
 1  4
 2  5
 3  6,

3x2 Array{Int64,2}:
 1  4
 2  5
 3  6)

### MATRIZ ALEATORIA

In [180]:
# Matriz aletória entre 0 e 1 rand(linhas,colunas)

Mc = rand(3,4)

3x4 Array{Float64,2}:
 0.692582   0.0858766   0.218182  0.716512 
 0.743547   0.615371    0.433915  0.822831 
 0.0539662  0.00717433  0.941094  0.0538761

### MULTIPLICAÇÃO DE MATRIZES 

Multiplicação Ma(linhas_Ma,colunas_Ma) * Mb(linhas_Mb,colunas_Mb) , só é possível se colunas_Ma = linhas_Mb ou seja se o número de colunas de Ma for igual ao número de linhas de Mb resultando em uma matriz de Ma_linhas e Mb_colunas

In [181]:
Ma = [1 2 3;4 5 6]

Md = [0.26 0.55 0.95 0.81; 0.35 0.61 0.86 0.40;0.41 0.65 0.35 0.45]

3x4 Array{Float64,2}:
 0.26  0.55  0.95  0.81
 0.35  0.61  0.86  0.4 
 0.41  0.65  0.35  0.45

In [182]:
Md, Ma, Ma*Md

(
3x4 Array{Float64,2}:
 0.26  0.55  0.95  0.81
 0.35  0.61  0.86  0.4 
 0.41  0.65  0.35  0.45,

2x3 Array{Int64,2}:
 1  2  3
 4  5  6,

2x4 Array{Float64,2}:
 2.19  3.72   3.72  2.96
 5.25  9.15  10.2   7.94)

### MATRIZ INVERSA 

In [183]:
Mx = rand(3,3)
Mx_inv = inv(Mx)

Mx,Mx_inv

(
3x3 Array{Float64,2}:
 0.837035  0.318536  0.585224
 0.168057  0.330272  0.521461
 0.70516   0.815967  0.712486,

3x3 Array{Float64,2}:
  1.39589   -1.83914   0.199487
 -1.82009   -1.34831   2.48181 
  0.702903   3.36438  -1.63617 )

### MATRIZES ESPECIAIS 

* **Matriz de zeros **

Matriz no qual todos os elementos são zeros. Sintaxe:
```julia
zeros(linhas, colunas)
```

In [184]:
Me = zeros(3,4)

3x4 Array{Float64,2}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

* ** Matriz de uns **

Matriz no qual todos os elementos são "uns". Sintaxe:
```julia
ones(linhas, colunas)
```

In [185]:
Me = ones(3,4)

3x4 Array{Float64,2}:
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0

* ** Matriz identidade **

Matriz quadrada no qual todos os elementos da diagnoa principal são "1" e os demais "0". Sintaxe:
```julia
eye(linhas)
```

In [186]:
Mf = eye(3)

3x3 Array{Float64,2}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

* ** Matriz identidade Mx*inv(Mx). **

O resultado apresenta valores proximos de zero para os numeros fora da diagonal principal

In [187]:
Mx = [0.91   0.43   0.41; 0.45   0.03   0.83; 0.85   0.55   0.10]

Mx*inv(Mx)

3x3 Array{Float64,2}:
  1.0           1.33227e-15  1.11022e-15
 -8.88178e-16   1.0          4.44089e-16
 -1.22125e-15  -1.66533e-16  1.0        

### DETERMINANTE , BASES E DIMENSÃO 

In [188]:
Mx = [0.91   0.43   0.41; 0.45   0.03   0.83; 0.87   0.55   0.10]

3x3 Array{Float64,2}:
 0.91  0.43  0.41
 0.45  0.03  0.83
 0.87  0.55  0.1 

* ** Determinante  **

In [189]:
Mx, det(Mx)

(
3x3 Array{Float64,2}:
 0.91  0.43  0.41
 0.45  0.03  0.83
 0.87  0.55  0.1 ,

-0.03075800000000006)

* **Norma**

In [190]:
norm(Mx)

1.6280341355208716

* ** Redução de linhas **

* ** Base **

* ** Rank de uma matriz **

In [191]:
rank(Mx), Mx

(3,
3x3 Array{Float64,2}:
 0.91  0.43  0.41
 0.45  0.03  0.83
 0.87  0.55  0.1 )

* ** Dimensão **

In [192]:
ndims(Mx), Mx

(2,
3x3 Array{Float64,2}:
 0.91  0.43  0.41
 0.45  0.03  0.83
 0.87  0.55  0.1 )

### DECOMPOSIÇÃO VETORIAL DE MATRIZES

#### DECOMPOSIÇAO LU 

Encontra a decomposição LU, p*a = l * u, no qual:
* L - triangular inferior,
* U - triangular superior,
* p – matriz de permutação.
* A matriz "a" não necessita ser quadrada.

In [193]:
(l,u,p) = lu(Mx)

(
3x3 Array{Float64,2}:
 1.0        0.0       0.0
 0.494505   1.0       0.0
 0.956044  -0.760529  1.0,

3x3 Array{Float64,2}:
 0.91   0.43      0.41    
 0.0   -0.182637  0.627253
 0.0    0.0       0.185066,

Int32[1,2,3])

## SISTEMAS LINEARES

Dado um sistema de equações lineares, formado pela matriz A matriz dos coeficientes do sistema ou matriz do sistema, vetor b dos coeficientes do sistema, e x vetor das incógnitas. Temos que:
![](sistema_matricial.png)


$$A\cdot x = b $$ 
$$x = b \setminus A$$

In [194]:
# criando duas matrizes aleatórias

A = rand(3,3); # matriz das coeficientes
B = rand(3,1); # vetor dos termos independentes

display(A)
display(B)

3x3 Array{Float64,2}:
 0.985039  0.773578  0.948328
 0.567557  0.907346  0.380116
 0.386761  0.887322  0.191891

3x1 Array{Float64,2}:
 0.822364
 0.636927
 0.647852

In [195]:
# X1,X2,X3: solução dos sistema

x = A\B

3x1 Array{Float64,2}:
 -4.41299
  1.7907 
  3.99027

** O poder de cálculo JULIA na manipulação de matrizes**

Vamos calcular um sistema linear de 5000 equações e 5000 variáveis. ATENÇÃO!!! Ao definir matrizes grandes, atente ao tamanho da memória ram do computador, pois dependendo do tamanho pode ser consumida toda a ram e toda a memória virtual (swap) e travar a máquina

In [196]:
A = rand(5000,5000);
B = rand(5000,1);

In [209]:
@elapsed x = A\B

4.432253626

In [198]:
typeof(x)

Array{Float64,2}

In [199]:
#Qual o resultado de x2 e de x4999?

x[2], x[4999]

(1.6645174523518325,-2.742295611847515)

%%% Fim Algebra linear %%%