# TIPOS DE DADOS II

## NUMÉRICOS

### NUMEROS COMPLEXOS 

O conjunto dos números complexos $C$ é definido por  $C = \{ a + bi ~|~ a, b ∈ R \}$, sendo $i = \sqrt{-1}$. Na linguagem Julia definimos um número complexo de acordo com as formas:
```julia
a + bim 
ou 
complex(a, b)
```
Sendo:
* **a, b** = constantes;
* **im** = imaginário.


In [1]:
# real e imaginário
complex(8, 4)

8 + 4im

In [2]:
# real e imaginário
1 + 2im

1 + 2im

In [3]:
# extrair somente a parte real
real(1 + 2im)

1

In [4]:
# extrair somente a parte imaginária
imag(1 + 2im)

2

**Soma de complexos**

$z + w = w + z = (a + bi) + (c + di) = (a + c) + (b+d)i$

In [5]:
(1 + 8im) + (2 - 3im)

3 + 5im

**Produto de números complexos**

${\displaystyle z \cdot w~ = ~w \cdot z=(a+bi)\cdot (c+di)=(a  c-b d)+(b  c+a  d)i}$


In [6]:
(2 + 3im)*(10 - 5im)

35 + 20im

**Divisão de números complexos**

${\displaystyle \frac{z}{w} = {\frac {a+bi}{c+di}}=\left({ac+bd \over c^{2}+d^{2}}\right)+\left({bc-ad \over c^{2}+d^{2}}\right)i.} $


In [7]:
(2 + 3im)/(10 - 5im)

0.04 + 0.32im

**Conjugado**

$ {\displaystyle {\overline {z}}=a-bi}$

In [8]:
conj(2 + 3im)

2 - 3im

**Módulo de um número complexo**

$|z| = {\sqrt {a^{2}+b^{2}}}$

In [9]:
abs(2 + 3im)

3.6055512754639896

**Argumento**

Dado $\displaystyle {cos(θ)=\frac {a}{|z|}}~~$  e ${~~\displaystyle sen(θ)=\frac {b}{|z|}}~~$, temos que : $\displaystyle θ=arcsen(\frac{b}{|z|})$ ou $\displaystyle θ=arcos(\frac{a}{|z|})$.

In [10]:
angle(2 + 3im) # em radianos

0.982793723247329

**Potência**

Dado um complexo na forma trigonométrica $~~z=|z|⋅cos(θ)+|z|⋅sen(θ)i~~$, sendo $~~b=|z|⋅sen(θ)~~$ e $~~a=|z|⋅cos(θ)~~$, 
$\displaystyle {z^n=|z|^n⋅(cos(nθ)+i⋅sen(nθ))}$

In [11]:
(2 + 3im)^2

-5 + 12im

In [12]:
(2 + 3im)^(1 - 2im)

-0.2923869406660075 - 25.738749188332598im

## DICIONÁRIO

Os dicionários são estruturas de dados que contém pares de chave-valor. Diferente de um vetor no qual os valores são indexados por numeros inteiros, dicionários são indexados por chaves (keys), que podem ser de qualquer tipo de dado. Dicionários são delimitados por parenteses e contém uma lista de pares (chave, valor) separada por vírgulas. Sintaxe:
```julia
Dict([(chave_1, valor_1),(chave_2, valor_2),..., (chave_n, valor_n) ]) 

ou 

Dict(chave_1 => valor, chave_2 => valor, ..., chave_n => valor_n)

ou 

Var = Dict()
     Var[Chave_1] = valor_1
     Var[Chave_2] = valor_2
     ...
     Var[Chave_n] = valor_n
```

O tipo de um dicionário é na forma: 
```julia
Dict{"Tipo basico chave","Tipo basico valor"}
```
"Tipo basico" pode ser inteiro, Float, string, complex e any.

**Exemplo 1.** Chaves do tipo string e valores do tipo Inteiro.

In [13]:
d1 = Dict([("a", 1), ("b", 2),("c", 10)])

Dict{String,Int64} with 3 entries:
  "c" => 10
  "b" => 2
  "a" => 1

**Exemplo 2.** Chaves do tipo string e valores do tipo string.

In [14]:
d2 = Dict("Soft1" => "Maxima", "Soft2" => "SageMath", "Soft3" =>"Julia")

Dict{String,String} with 3 entries:
  "Soft1" => "Maxima"
  "Soft3" => "Julia"
  "Soft2" => "SageMath"

**Exemplo 3**. Chaves do tipo "Any" e valores do tipo "Any".

In [15]:
d3 = Dict()
     d3["Amostra"] = 100
     d3["b"] = 2
     d3[2] = "raio"
d3

Dict{Any,Any} with 3 entries:
  2         => "raio"
  "b"       => 2
  "Amostra" => 100

**Tipos do par chave-valor**

In [16]:
typeof(d1), typeof(d2), typeof(d3)

(Dict{String,Int64}, Dict{String,String}, Dict{Any,Any})

**Manipular valores e chaves**

In [17]:
# acessar valor da chave "c" de d1
d1["c"]

10

In [18]:
# acessar somente as chaves de d1
keys(d1)

Base.KeySet for a Dict{String,Int64} with 3 entries. Keys:
  "c"
  "b"
  "a"

In [19]:
# deletar uma key de d1
delete!(d1, "b")

Dict{String,Int64} with 2 entries:
  "c" => 10
  "a" => 1

In [20]:
# ordenar os valores do dicionário d2
sort(collect(values(d2)))

3-element Array{String,1}:
 "Julia"   
 "Maxima"  
 "SageMath"

In [21]:
d1["c"]

10

In [22]:
# alterar o valor da chave "c" de d1
d1["c"] = 99

99

**Alterar a Key do dicionário**

`Keys` são imutáveis, logo não permitem modificação de nome ou tipo. O que se faz é copiar o conteúdo de uma `key` desejada para outra `nova_key` e depois apaga-se o a `key` antiga.

In [23]:
# copia a key "c" para a key "novo" e apaga-se a key "c"
d1["Amostra"] = pop!(d1,"c")

99

In [24]:
d1

Dict{String,Int64} with 2 entries:
  "Amostra" => 99
  "a"       => 1

**União e Merge**

A função `union()` une os dois dicionários em um `Array` mantendo a ordem de cada um. Sintaxe:
```julia 
union(dic_1,dic_2, ..., dic_n)
union!(dic_1,dic_2, ..., dic_n) # une os dicionários e sobrescreve em dic_1. CUIDADO!
```
A função `marge()` agrupa os dicionários em outro dicionário e se a mesma chave estiver presente em outro dicionário, o valor dessa chave será o valor que ela possui no último dicionário. Sintaxe:
```julia 
merge(dic_1,dic_2, ..., dic_n)
merge!(dic_1,dic_2, ..., dic_n) # agrupa os dicionário e sobrescreve em dic_1. CUIDADO!
```

In [25]:
display(d1), display(d3)

Dict{String,Int64} with 2 entries:
  "Amostra" => 99
  "a"       => 1

Dict{Any,Any} with 3 entries:
  2         => "raio"
  "b"       => 2
  "Amostra" => 100

(nothing, nothing)

In [26]:
union(d1,d3)

5-element Array{Pair{Any,Any},1}:
 "Amostra" => 99    
       "a" => 1     
         2 => "raio"
       "b" => 2     
 "Amostra" => 100   

In [27]:
# d1 e d3 possuem a chave "Amostra". Será atribuído o valor de d3.
merge(d1, d3)

Dict{Any,Any} with 4 entries:
  2         => "raio"
  "b"       => 2
  "Amostra" => 100
  "a"       => 1

In [28]:
# d1 e d3 possuem a chave "Amostra". Será atribuído o valor de d1.
merge(d3, d1)

Dict{Any,Any} with 4 entries:
  2         => "raio"
  "b"       => 2
  "Amostra" => 99
  "a"       => 1

**Diferença e interseção entre dicionários**

A função `setdiff(dic_1, dic_2)` lista os pares chave-valor que pertecem ao dicionário `dic_1` e não pertencem ao `dic_2`. A função `intersect(dic_1, dic_2)` lista os pares chave-valor em comum entre os dicionários.

In [29]:
setdiff(d1, d3)

2-element Array{Pair{String,Int64},1}:
 "Amostra" => 99
       "a" => 1 

In [30]:
setdiff(d3, d1)

3-element Array{Pair{Any,Any},1}:
         2 => "raio"
       "b" => 2     
 "Amostra" => 100   

In [31]:
intersect(d1, d3)

0-element Array{Pair{String,Int64},1}

## CONJUNTOS

Um `Set` é um conjunto de elementos semelhante a um dicionário sem elementos duplicados e ordenados. A vantagem em usar conjuntos é que podemos trabalhar as relações de pertinência e as operações de intersecção, união, subconjunto e diferença de conjuntos. Os caracteres unicode podem ser inseridos na forma `"\cod_latex{tab}"`. Sintaxe:
```julia
Set([valor1, valor2])
``` 
O tipo básico pode ser: inteiro, float, complex... ou any.

In [32]:
# O conjunto filtra elementos repetidos permitindo somente entrada única
Conj_1 = Set(["Julia", 10.0 , "Julia"])

Conj_2 = Set(["Sagemath", 10.0 , [10, 50, 99], "Julia"]);

In [33]:
# veja que o elemento "Julia" não foi duplicado
Conj_1

Set(Any[10.0, "Julia"])

In [34]:
# acrescentando elemento
push!(Conj_1, [7 8 9; 4 5 6], "Scilab") 

Set(Any[10.0, [7 8 9; 4 5 6], "Julia", "Scilab"])

In [35]:
# retirar o primeiro elemento de um conjunto
pop!(Conj_1)

10.0

**Relação de pertinência**

Se um elemento $x$ pertencente ao conjunto $A$ podemos dizer que $x$ pertence a $A$, ou $x \in A$.

verificar se um valor pertence ao conjunto

In [36]:
"Julia" in Conj_1, in("Julia", Conj_1)

(true, true)

Verificar se um valor pertence ao conjunto

In [37]:
10 ∈ Conj_1, ∉(Conj_1, Conj_2)

(false, true)

**União**

Dados dois conjuntos $A$ e $B$, o conjunto união $A \cup B$ é dado por:
$x \in A \cup B ⇔ x \in A$ ou $x \in B$


In [38]:
union(Conj_1,Conj_2)

Set(Any["Sagemath", 10.0, [7 8 9; 4 5 6], "Julia", [10, 50, 99], "Scilab"])

In [39]:
Conj_1 ∪ Conj_2

Set(Any["Sagemath", 10.0, [7 8 9; 4 5 6], "Julia", [10, 50, 99], "Scilab"])

In [40]:
∪(Conj_1,Conj_2)

Set(Any["Sagemath", 10.0, [7 8 9; 4 5 6], "Julia", [10, 50, 99], "Scilab"])

**Intersecção** 

O conjunto intersecção $A \cap B$ é formado pelos elementos que pertencem simultaneamente a A e B: $x \in A \cap B ⇔ x \in A$ e $x \in B$

In [41]:
intersect(Conj_1,Conj_2)

Set(Any["Julia"])

In [42]:
Conj_1 ∩ Conj_2

Set(Any["Julia"])

In [43]:
∩(Conj_2,Conj_1)

Set(Any["Julia"])

**Diferença entre conjuntos**

Dados dois conjuntos $A$ e $B$, define-se a diferença $A - B$  como sendo o conjunto formado pelos elementos de $A$ que não pertencem  a $B$ : $ A - B = \{ X ~ |~ x \in A ~e~ x \notin B \}$

In [44]:
setdiff(Conj_1, Conj_2)

Set(Any[[7 8 9; 4 5 6], "Scilab"])

In [45]:
setdiff(Conj_2, Conj_1)

Set(Any["Sagemath", 10.0, [10, 50, 99]])

**Subconjunto**

Um conjunto $B$ é um subconjunto do conjunto $A$ se todo elemento de $B$ é também elemento de $A$ ou seja:  $B \subset A$.


In [46]:
issubset(Conj_1, Conj_2)

false

In [47]:
Conj_1 ⊆ Conj_2

false

In [48]:
⊆(Conj_2, Conj_1)

false

## LISTAS, ARRAY, VETORES E MATRIZES PARTE II

### ARRAY UNIDIMENSIONAL / VETORES PARTE II

Atenção: A função `pop()` nao serve para vetores linha! Funciona somente para vetores coluna.

#### CRIANDO VETORES USADO LINRANGE()

A função `LinRange()` cria uma sequencia do tipo `LinRange`. Sintaxe:
```julia
LinRange(inicio, fim, quantidade de elementos)
```

In [49]:
LinRange(10, 10, 15)

15-element LinRange{Float64}:
 10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0

In [50]:
vl = LinRange(0, 10, 15)

15-element LinRange{Float64}:
 0.0,0.714286,1.42857,2.14286,2.85714,…,7.14286,7.85714,8.57143,9.28571,10.0

É possível acessar os elementos de acordo com o índice, porém não é possível alterar o valor de um elemento da range.

In [51]:
vl[2] = 0

ErrorException: setindex! not defined for LinRange{Float64}

**CRIANDO VETORES USADO `COLLECT()`**

A função `collect()` cria vetores unidimensional ( Array{Tipo_dado,**1**} ). Sintaxe:
```julia
collect(inicio : passo : fim)
```
Sendo:

In [52]:
# Criando um vetor de 1 a 2 de 0.25 em 0.25
vc = collect(1:0.25:2)

5-element Array{Float64,1}:
 1.0 
 1.25
 1.5 
 1.75
 2.0 

In [53]:
# dimensoes do vetor
ndims(vc)

1

In [54]:
# quantidade de elementos de um vetor ou tamanho do vetor
length(vc)

5

É possível acessar os elementos de acordo com o índice e alterar o valor de um elemento da range.

In [55]:
# acessando dados no vetor y
vc[1], vc[2]

(1.0, 1.25)

In [56]:
# alterando o valor do elemento v[1]
vc[1] = 0

0

**Cuidado com os tipos!** 

In [57]:
vc0 = collect(1: 2: 6)   # vetor unidimensional do tipo inteiro
vc1 = collect(1.0: 2: 6) # vetor unidimensional do tipo float
vc2 = collect(1: 2.0: 6) # vetor unidimensional do tipo float

@show typeof(vc0), ndims(vc0)
@show typeof(vc1), ndims(vc1)
@show typeof(vc2), ndims(vc1);

(typeof(vc0), ndims(vc0)) = (Array{Int64,1}, 1)
(typeof(vc1), ndims(vc1)) = (Array{Float64,1}, 1)
(typeof(vc2), ndims(vc1)) = (Array{Float64,1}, 1)


**CRIANDO VETORES USANDO `RANGE`**

Consiste de um conjunto ordenado de elementos,semelhante a um vetor, com cada elemento identificado por um índice. Range cria vetores unidimensionais ( Array{Tipo_dado,**1**} ). Sintaxe:
```julia
range(inicio, stop = valor, length = valor) 
```
Ou
```
inicio:passo:fim
```
O tipo básico pode ser: inteiro, float, complex e outros. Não é possível alterar um valor de uma Range.

In [58]:
vr1 = range(0, stop=10, length = 5)

0.0:2.5:10.0

In [59]:
typeof(vr1)

StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}

In [60]:
# acessando elementos 
vr1[5]

10.0

É possível acessar os elementos de acordo com o índice, porém não é possível alterar o valor de um elemento da range.

In [61]:
vr1[5] = 0.0

ErrorException: setindex! not defined for StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}

Outra forma:

In [62]:
vr2 = 1:0.25:2

1.0:0.25:2.0

In [63]:
typeof(vr2)

StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}

Podemos, no entanto, usar `collect` para converter um `range` num vetor normal (mutável).

In [64]:
vr2 = collect(vr1)

5-element Array{Float64,1}:
  0.0
  2.5
  5.0
  7.5
 10.0

In [65]:
vr2[5] = 0.0

0.0

In [66]:
# acessando elementos
vr2[1], vr2[2]

(0.0, 2.5)

**Cuidados com os tipos!**

In [67]:
r0 = range(1, stop = 5) # ranger do tipo inteiro
r1 = 1: 1.0: 5          # ranger do tipo float, observe o valor 1.0 do tipo float;

In [68]:
typeof(r0), ndims(r0)

(UnitRange{Int64}, 1)

In [69]:
typeof(r1), ndims(r1)

(StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}, 1)

**SUBVETORES**

O resultado é um vetor coluna contendo os elementos do subvetor.
```julia
view(vetor, faixa)
```
Sendo:
* **vetor:** vetor de dados;
* **faixa:** 


In [70]:
v = [0, 3, 6, 9, 12, 100, 105, 108, 109, 110, 111, 112, 113, 114, 115]
u = ["a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "l" "m" "n" "o" "p"];

Exemplo 1: criar um subarray do vetor "v" dos elemento de índice 1 até o elemento de índice 10 tomando de 3 em 3 índices.

In [71]:
view(v, 1:3:10)

4-element view(::Array{Int64,1}, 1:3:10) with eltype Int64:
   0
   9
 105
 110

Exemplo 2: criar um subconjunto coluna do vetor "u" dos elemento de índice 10 até o elemento de índice 1 tomando de 3 em 3 índice decrescente.

In [72]:
view(u, 10:-3:1)

4-element view(::Array{String,1}, 10:-3:1) with eltype String:
 "j"
 "g"
 "d"
 "a"

**MANIPULAÇÃO DE ARRAY/VETORES**

Os comandos abaixo não funcionam para vetores linha.

In [73]:
a = [10, 20, 30, 40, 50, 60]

6-element Array{Int64,1}:
 10
 20
 30
 40
 50
 60

**Função `splice()`**
```julia
splice!(vetor, índice)
splice!(vetor, faixa de índices)
```
Sendo:
* **vetor**: vetor de dados;
* **faixa**:

Exemplo 1: o vetor [100, 1] é colocado no índice 2 do vetor "a". A função `splice()` retorna o elemento substituído. 

In [74]:
splice!(a, 2, [100, 200])

20

In [75]:
a

7-element Array{Int64,1}:
  10
 100
 200
  30
  40
  50
  60

Exemplo 2: substituir os elementos dos índices de 2 a 6 pelo vetor [500, -500]. A função `splice()` retorna os elementos substituídos. 

In [76]:
splice!(a, 2:6, [500, -500])

5-element Array{Int64,1}:
 100
 200
  30
  40
  50

In [77]:
a

4-element Array{Int64,1}:
   10
  500
 -500
   60

**Função `resize!()`**

Varia o tamanho do vetor para $n$ índices. Quando $n$ é maior que o tamanho do vetor, serão acrescentados números aleatórios, e quando $n$ é menor os itens dos índices superiores serão eliminados. `#undef` significa tipo indefinido
```julia
resize!(vetor, tamanho )
```

In [78]:
a = [10, 20, 30, 40]

4-element Array{Int64,1}:
 10
 20
 30
 40

In [79]:
# redimensiona o vetor "a" para um vetor de tamanho 2 
resize!(a, 2)

2-element Array{Int64,1}:
 10
 20

In [80]:
a

2-element Array{Int64,1}:
 10
 20

In [81]:
# redimensiona o vetor "a" aumentando seu tamanho para 5
resize!(a, 5)

5-element Array{Int64,1}:
     10
     20
 569348
      0
      0

**FILTRO APLICADO A VETORES**

Aplica o filtro a um vetor e imprime somente os valores filtrados. Sintaxe:
```julia
vetor[vetor .operador valor]
```
Sendo: 
* **vetor**: vetor de dados;
* **operador**: operador (>, <, & >=, <=, |, !, ==);
* **valor**: valor de referência.

O ponto "." antes do operador é necessário para comparar elemento por elemento.

In [82]:
# definir o vetor 
vet_num = collect(0:5);

Exemplo 1: listar os numeros menores que 3.

In [83]:
vet_num[vet_num.> 3]

2-element Array{Int64,1}:
 4
 5

Exemplo 2: listar numeros diferente de 3.

In [84]:
vet_num[vet_num.!= 3]

5-element Array{Int64,1}:
 0
 1
 2
 4
 5

Exemplo 3: listar nomes diferentes de "julia".

In [85]:
vet_nomes = ["julia", "sage", "maxima", "julia", "scilab", "fremat"]

6-element Array{String,1}:
 "julia" 
 "sage"  
 "maxima"
 "julia" 
 "scilab"
 "fremat"

In [86]:
vet_nomes[vet_nomes.!= "julia"]

4-element Array{String,1}:
 "sage"  
 "maxima"
 "scilab"
 "fremat"

Exemplo 5: listar nomes maiores que contenham letra superior a "j" da string "julia.

In [87]:
vet_nomes[vet_nomes.> "julia"]

3-element Array{String,1}:
 "sage"  
 "maxima"
 "scilab"

Exemplo 6: listar nomes diferentes de "julia" **E** "maxima".

In [88]:
vet_nomes[.&((vet_nomes.!= "julia"),(vet_nomes.!= "maxima"))]

3-element Array{String,1}:
 "sage"  
 "scilab"
 "fremat"

**PAR DE ELEMENTOS COM COM FUNÇÃO ZIP**

A função `zip()` agrupa vários objetos em uma única estrutura.

In [89]:
vet_1  = [8.4, 9.5, 10.6]
vet_2  = [0, 1, 2]
vet_3  = [1+im, 5+im, 6+im]
vet_4  = ["a", "b", "c"]

coisas_tipos = zip(vet_1, vet_2, vet_2, vet_3, vet_4 )

Base.Iterators.Zip{Tuple{Array{Float64,1},Array{Int64,1},Array{Int64,1},Array{Complex{Int64},1},Array{String,1}}}(([8.4, 9.5, 10.6], [0, 1, 2], [0, 1, 2], Complex{Int64}[1 + 1im, 5 + 1im, 6 + 1im], ["a", "b", "c"]))

In [90]:
typeof(coisas_tipos)

Base.Iterators.Zip{Tuple{Array{Float64,1},Array{Int64,1},Array{Int64,1},Array{Complex{Int64},1},Array{String,1}}}

### ARRAY MULTIDIMENSIONAL / MATRIZES PARTE II

**PREENCHIMENTO DE MATRIZES**

**Função `fill()`**
```julia
fill(valor, mlinhas, ncolunas)
```
* **valor**: valor de referência. Pode ser um string, numérico, vetor, etc;
* **mlinhas, ncolunas**: número de linhas e número de colunas.

In [91]:
# Cria uma matriz 3x3 preenchendo (fill) de strings "julia"
Mf1 = fill("Julia", 3, 3)

3×3 Array{String,2}:
 "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"
 "Julia"  "Julia"  "Julia"

In [92]:
# Cria uma matriz 3x3 preenchendo (fill) de tuplas (1,2,3)
Mf2 = fill((1, 2, 3), 3, 3)

3×3 Array{Tuple{Int64,Int64,Int64},2}:
 (1, 2, 3)  (1, 2, 3)  (1, 2, 3)
 (1, 2, 3)  (1, 2, 3)  (1, 2, 3)
 (1, 2, 3)  (1, 2, 3)  (1, 2, 3)

**Função `repeat()`**

Cria uma matriz repetindo a matriz `n x m` em `x linhas` e `y colunas`. 
```julia
repeat(matriz, mlinhas, ncolunas)
```
Sendo:
* **matriz**: matriz de dados;

* **mlinhas, ncolunas**: quantidade de repetições para m linhas e n colunas.

In [93]:
A = [1 2; 3 4]

2×2 Array{Int64,2}:
 1  2
 3  4

In [94]:
# a função abaixo cria uma matriz repetindo a matriz 2x2 em 2 linhas e 3 colunas
repeat(A, 2, 3)

4×6 Array{Int64,2}:
 1  2  1  2  1  2
 3  4  3  4  3  4
 1  2  1  2  1  2
 3  4  3  4  3  4

**Função `reshape()`**

Cria uma matriz com $x \cdot y$ elementos utilizando um vetor (pode ser também range, rand e outros). Sintaxe:
```julia
reshape(vetor, mlinhas, ncolunas)
```
Sendo:
* **vetor**: vetor de dados;
* **mlinhas, ncolunas**: número de linhas e colunas da matriz.

Exemplo: a função abaixo cria uma matriz de 5 linhas e 3 colunas a partir de um vetor de 15 elementos

In [95]:
reshape(1:15, 5, 3)

5×3 reshape(::UnitRange{Int64}, 5, 3) with eltype Int64:
 1   6  11
 2   7  12
 3   8  13
 4   9  14
 5  10  15

**Função `repeat()`**

Repete os elementos na forma interna(`inner`) ou externa(`outer`). Interna ocorre a repet
```julia
repeat(matriz, inner = (mlinhas, ncolunas))
repeat(matriz, outer = (mlinhas, ncolunas))
repeat(matriz, inner = (mlinhas, ncolunas), outer = (mlinhas, ncolunas))
```
Sendo:
* **matriz**: matriz de dados;
* **mlinhas, ncolunas**: 

In [96]:
A = [1 2; 3 4]

2×2 Array{Int64,2}:
 1  2
 3  4

In [97]:
repeat(A, outer = (3 , 2) )

6×4 Array{Int64,2}:
 1  2  1  2
 3  4  3  4
 1  2  1  2
 3  4  3  4
 1  2  1  2
 3  4  3  4

In [98]:
repeat(A, inner = (3 , 2))

6×4 Array{Int64,2}:
 1  1  2  2
 1  1  2  2
 1  1  2  2
 3  3  4  4
 3  3  4  4
 3  3  4  4

**FILTRO APLICADO A MATRIZES**

Aplica o filtro a uma matriz e imprime somente os valores filtrados. Sintaxe:
```julia
matriz[matriz .operador valor]
```
Sendo: 
* **matriz**: matriz de dados;
* **operador**: operador (>, <, & >=, <=, |, !, ==);
* **valor**: valor de referência.

O ponto "." antes do operador é necessário para comparar elemento por elemento.

In [99]:
# criar uma matriz 
mat_num = [x + 2*y - 1 for x = 1:3, y = 1:3]

3×3 Array{Int64,2}:
 2  4  6
 3  5  7
 4  6  8

Exemplo 1: listar os numeros maiores ou iguais a 5. O ponto "." antes do operador ">=" é necessário para comparar elemento por elemento.

In [100]:
mat_num[mat_num .>= 5]

5-element Array{Int64,1}:
 5
 6
 6
 7
 8

Observe que é listado elementos repetidos. Se for um problema, a função `unique()` retira os elementos repetidos.

In [101]:
unique(mat_num[mat_num .>= 5])

4-element Array{Int64,1}:
 5
 6
 7
 8

Exemplo 2: listar os elementos maiores ou igual a 5 **E** menores ou igual a 7. O ponto "." antes dos operadores "$", ">" e "<=", é necessário para comparar elemento por elemento.

In [102]:
mat_num[.&((mat_num.>= 5),(mat_num.<= 7))]

4-element Array{Int64,1}:
 5
 6
 6
 7

Exemplo 3: listar os elementos menores que 3 **OU** maiores que 8. O ponto "." antes dos operadores "|", "<" e ">", é necessário para comparar elemento por elemento.

In [103]:
mat_num[.|((mat_num.< 5),(mat_num.> 8))]

4-element Array{Int64,1}:
 2
 3
 4
 4

### COMBINAÇÃO E PERMUTAÇÃO DE ELEMENTOS

**Combinação**: O número de combinações de $n$ objetos tomados $p$ a $p$, representado por $C_{n,p}$ é dado por:. 

$\displaystyle{C_{n,p} = \frac{n!}{(n - p)!p!}}$

Na combinação não importa a ordem dos elementos. Sintaxe:
```julia
collect(combinations(n, p))
```
Sendo: 
* **n**: vetor, matriz ou tupla não nomeada de elementos;
* **p**: número de elementos selecionados. 

**Permutação**: O número de permutações de $n$ objetos tomados $p$ a $p$ é representado por $P_{n,p}$ é dado por:
 
$\displaystyle{P_{n,p} = \frac{n!}{(n - p)!}}$

Na permutação a ordem dos elementos importa. Sintaxe:
```julia
collect(permutations(n, p))
```
Sendo: 
* **n**: vetor, matriz ou tupla não nomeada de elementos;
* **p**: número de elementos selecionados.

Em Julia 0.5 ou superior a função `combinations()` pertence ao pacote `Combinatorics.jl`. Para instalar utilize:
```julia
using Pkg
Pkg.add("Combinatorics")
```

In [104]:
using Combinatorics

In [105]:
vetor = [1, 2, 4, 4];

In [106]:
# permutação P_4,2
collect(permutations(vetor, 2))

12-element Array{Array{Int64,1},1}:
 [1, 2]
 [1, 4]
 [1, 4]
 [2, 1]
 [2, 4]
 [2, 4]
 [4, 1]
 [4, 2]
 [4, 4]
 [4, 1]
 [4, 2]
 [4, 4]

Note que há elementos repetidos. Para filtrar use a função `unique!()`:

In [107]:
# permutação P_4,2
unique!(collect(permutations(vetor, 2)))

7-element Array{Array{Int64,1},1}:
 [1, 2]
 [1, 4]
 [2, 1]
 [2, 4]
 [4, 1]
 [4, 2]
 [4, 4]

In [108]:
# combinação C_4,2
collect(combinations(vetor, 2))

6-element Array{Array{Int64,1},1}:
 [1, 2]
 [1, 4]
 [1, 4]
 [2, 4]
 [2, 4]
 [4, 4]

Note que há elementos repetidos. Para filtrar use a função `unique!()`:

In [109]:
unique!(collect(combinations(vetor, 2)))

4-element Array{Array{Int64,1},1}:
 [1, 2]
 [1, 4]
 [2, 4]
 [4, 4]

In [110]:
# permutação P_4,3
unique!(collect(permutations(vetor, 3)))

12-element Array{Array{Int64,1},1}:
 [1, 2, 4]
 [1, 4, 2]
 [1, 4, 4]
 [2, 1, 4]
 [2, 4, 1]
 [2, 4, 4]
 [4, 1, 2]
 [4, 1, 4]
 [4, 2, 1]
 [4, 2, 4]
 [4, 4, 1]
 [4, 4, 2]

In [111]:
# combinação C_4,3
unique!(collect(combinations(vetor, 3)))

3-element Array{Array{Int64,1},1}:
 [1, 2, 4]
 [1, 4, 4]
 [2, 4, 4]

## TIPOS DEFINIDOS PELO PROGRAMADOR##

In [112]:
mutable struct Amostra
    material  ::AbstractString
    massa     ::Float64 # kg
    volume    ::Float64 # m^3
end

In [113]:
typeof(Amostra)

DataType

In [114]:
# criar um elemento do tipo amostra
objeto1 = Amostra("isopor", 0.001, 0.0001)

Amostra("isopor", 0.001, 0.0001)

In [115]:
# conferir tipo
typeof(objeto1)

Amostra

In [116]:
# conferir campos
fieldnames(Amostra)

(:material, :massa, :volume)

In [117]:
# conferir atributos do elemento criado
objeto1.massa, objeto1.material

(0.001, "isopor")

In [118]:
# alterar valor atributo massa
objeto1.massa = 0.002

0.002

**%%% Fim Tipos de Dados %%%**