# ALGEBRA LINEAR

Julia possui um conjunto próprio comandos de álgebra linear que permite trabalhar diversas operações com matrizes e vetores. Entretanto, há o pacote `Nemo` que possui bem mais recursos algébricos. Pkg.add("Nemo")

`Nemo` é um pacote de álgebra que permite trabalhar álgebra comutativa, teoria dos números e teoria do grupo. Atualmente está sendo desenvolvido por William Hart, Tommy Hofmann, Fredrik Johansson, Claus Fieker e Oleksandr Motsak com contribuições de outros desenvolvetores. Nemo oferece atualmente:

- Wrappers de MPIR, Flint, Arb e Antic
- Um Wrappers  experimental de Pari
- Anéis de polinômios genéricos, espaços de matriz, anéis de resíduos, série de potência
- Campos finitos, p-adics, inteiros, racionais, permutações e outros.

In [18]:
Pkg.update("Nemo")

INFO: Updating METADATA...
INFO: Updating cache of DataFrames...
INFO: Computing changes...
INFO: No packages to install, update or remove


In [1]:
using Nemo


Welcome to Nemo version 0.5.1

Nemo comes with absolutely no warranty whatsoever



## VETORES 

### OPERAÇÕES COM VETORES

* ** Soma de vetores **

$vetorA + vetorB$

$[a_1+b_1 ~,~ a_2+b_2 ~,~  a_3+b_3]$ e $[b_1+a_1 ~,~ b_2+a_2 ~,~  b_3+a_3]$

In [137]:
v = [1, 2, 3]
u = [4, 5, 6]

u+v

3-element Array{Int64,1}:
 5
 7
 9

* **Subtração **

$vetorA - vetorB$

$[a_1-b_1 ~,~ a_2-b_2 ~,~  a_3-b_3]$ e $[b_1-a_1 ~,~ b_2-a_2 ~,~  b_3-a_3]$

In [138]:
v = [1, 2, 3]
u = [4, 5, 6]

display(u-v)

display(v-u)

3-element Array{Int64,1}:
 3
 3
 3

3-element Array{Int64,1}:
 -3
 -3
 -3

### OPERAÇÕES COM NUMEROS ESCALARES

* ** Multiplicação por escalar ** 

$k*vetorA$

$[a_1*k ~,~ a_2*k ~,~  a_3*k]$ 

In [139]:
v = [1, 2, 3]

2*v

3-element Array{Int64,1}:
 2
 4
 6

* ** Multiplicação elemento por elemento entre vetores** 

$[a_1*b_1 ~,~ a_2*b_2 ~,~  a_3*b_3]$ e $[b_1*a_1 ~,~ b_2*a_2 ~,~  b_3*a_3]$

In [2]:
v = [1, 2, 3]
u = [4, 5, 6]

v.*u

3-element Array{Int64,1}:
  4
 10
 18

In [3]:
# utilizando o map
map(*, v, u)

3-element Array{Int64,1}:
  4
 10
 18

* **Divisão por escalar**

$[{a_1 \over k} ~,~ {a_2 \over k} ~,~  {a_3 \over k}]$ 

In [142]:
# [1/2, 2/2, 3/2]

v = [1, 2, 3]

v/2

3-element Array{Float64,1}:
 0.5
 1.0
 1.5

In [143]:
# Divisão elemento por elemento entre vetores [1/4, 2/5, 3/6]

v = [1, 2, 3]
u = [4, 5, 6]

v./u

3-element Array{Float64,1}:
 0.25
 0.4 
 0.5 

In [144]:
# Divisão elemento por elemento entre vetores [1/4, 2/5, 3/6] pelo map()

map(/, v, u)

3-element Array{Float64,1}:
 0.25
 0.4 
 0.5 

* ** Potencia por escalar**

In [145]:
# Potencia elemento por elemento [1^2 2^2 3^2]

v = [1 2 3]

v.^2

1x3 Array{Int64,2}:
 1  4  9

In [146]:
# Potencia elemento por elemento entre vetores [1^4 2^5 3^6]

v = [1, 2, 3]
u = [4, 5, 6]

v.^u

3-element Array{Int64,1}:
   1
  32
 729

In [147]:
# Potencia elemento por elemento entre vetores [1^4, 2^5, 3^6] pelo map()

map(^, v,u)

3-element Array{Int64,1}:
   1
  32
 729

### TRANSPOSIÇÃO DE UM VETOR 

Veja que a transposição altera o tipo do vetor de Unidimensional(Array{Tipo_dado,1}) para Bidimensional(Array{Tipo_dado,2}) ou o contrário

Sintaxe:
```julia
transpose(vetor)
ou
vetor'
```

In [148]:
display(v)

display(transpose(v))

display(v')

3-element Array{Int64,1}:
 1
 2
 3

1x3 Array{Int64,2}:
 1  2  3

1x3 Array{Int64,2}:
 1  2  3

### VALORES DE  Max e Min DE UM VETOR

In [3]:
# Valor máximo do vetor

v = [1, 5, -9]

maximum(v)

5

In [151]:
# Valor máximo de um vetor e indice

valor_max, indice_max = findmax(v)

(5,2)

In [152]:
# valores extremos de um vetor: minimo e máximo simultâneo.

extrema(v)

(-9,5)

In [153]:
# Valor mínimo de um vetor

minimum(v)

-9

In [154]:
# Valor minimo de um vetor e indice

valor_min, indice_min = findmin(v)

(-9,3)

In [155]:
v = [1, 2, 3]
u = [4, 5, 6]

dot(v,u), dot(u,v)

(32,32)

### PRODUTO INTERNO E EXTERNO ENTRE VETORES 

In [1]:
# Produto interno: somente vetores coluna. aqui o uso do transpose ou v' nao funciona
# caso use vetores linha, transforme - o em coluna com vec(vetor_linha)

v = [1, 2, 3]
u = [4, 5, 6]

dot(v,u), dot(u,v)

(32,32)

In [157]:
# Produto externo ou vetorial

cross(v,u), cross(u,v)

([-3,6,-3],[3,-6,3])

## MATRIZES

### OPERAÇÕES COM MATRIZES

* ** Soma de matrizes **

In [171]:
Ma = [1 2 3; 4 5 6]
Mb = [4 5 6; 7 8 9]

Ma + Mb

2x3 Array{Int64,2}:
  5   7   9
 11  13  15

* ** Subtração de matrizes**

In [172]:
Ma = [1 2 3; 4 5 6]
Mb = [4 5 6; 7 8 9]

Ma - Mb

2x3 Array{Int64,2}:
 -3  -3  -3
 -3  -3  -3

### OPERAÇÕES COM NUMEROS ESCALARES 

* **Multiplicação por escalar**

In [173]:
Ma = [1 2 3; 4 5 6]

2*Ma

2x3 Array{Int64,2}:
 2   4   6
 8  10  12

* **Multiplicação elemento por elemento entre vetores **

$[1x4  ~ 2x5 ~  3x6; 4x7 ~  5x8 ~  6x9]$

In [174]:
Ma = [1 2 3; 4 5 6]
Mb = [4 5 6; 7 8 9]

Ma.*Mb

2x3 Array{Int64,2}:
  4  10  18
 28  40  54

* ** Divisão por escalar**

In [175]:
Ma = [1 2 3; 4 5 6]

Ma/2

2x3 Array{Float64,2}:
 0.5  1.0  1.5
 2.0  2.5  3.0

* ** Divisão elemento por elemento entre vetores $[1/4  ~  2/5 ~  3/6; 4/7 ~  5/8 ~  6/9]$ **

In [176]:
Ma = [1 2 3; 4 5 6]
Mb = [4 5 6; 7 8 9]

Ma./Mb

2x3 Array{Float64,2}:
 0.25      0.4    0.5     
 0.571429  0.625  0.666667

* ** Potencia elemento por elemento $[1^2 ~ 2^2 ~ 3^2; 4^2  ~ 5^2 ~  6^2]$ **

In [177]:
Ma = [1 2 3; 4 5 6]

Ma.^2

2x3 Array{Int64,2}:
  1   4   9
 16  25  36

* ** Potencia elemento por elemento entre vetores $[1^4 ~  2^5 ~  3^6; 4^7 ~  5^8 ~  6^9]$ **

In [178]:
Ma = [1 2 3; 4 5 6]
Mb = [4 5 6; 7 8 9]

Ma.^Mb

2x3 Array{Int64,2}:
     1      32       729
 16384  390625  10077696

### TRANSPOSIÇÃO DE MATRIZES 

In [179]:
Ma = [1 2 3; 4 5 6]

transpose(Ma), Ma'

(
3x2 Array{Int64,2}:
 1  4
 2  5
 3  6,

3x2 Array{Int64,2}:
 1  4
 2  5
 3  6)

### MULTIPLICAÇÃO DE MATRIZES 

Multiplicação `Ma(linhas_Ma,colunas_Ma) * Mb(linhas_Mb,colunas_Mb)` , só é possível se `colunas_Ma = linhas_Mb` ou seja se o número de colunas de Ma for igual ao número de linhas de Mb resultando em uma matriz de `Ma_linhas e Mb_colunas`

In [181]:
Ma = [1 2 3;4 5 6]

Md = [0.26 0.55 0.95 0.81; 0.35 0.61 0.86 0.40;0.41 0.65 0.35 0.45]

3x4 Array{Float64,2}:
 0.26  0.55  0.95  0.81
 0.35  0.61  0.86  0.4 
 0.41  0.65  0.35  0.45

In [182]:
Md, Ma, Ma*Md

(
3x4 Array{Float64,2}:
 0.26  0.55  0.95  0.81
 0.35  0.61  0.86  0.4 
 0.41  0.65  0.35  0.45,

2x3 Array{Int64,2}:
 1  2  3
 4  5  6,

2x4 Array{Float64,2}:
 2.19  3.72   3.72  2.96
 5.25  9.15  10.2   7.94)

### MATRIZ INVERSA 

In [183]:
Mx = rand(3,3)
Mx_inv = inv(Mx)

Mx,Mx_inv

(
3x3 Array{Float64,2}:
 0.837035  0.318536  0.585224
 0.168057  0.330272  0.521461
 0.70516   0.815967  0.712486,

3x3 Array{Float64,2}:
  1.39589   -1.83914   0.199487
 -1.82009   -1.34831   2.48181 
  0.702903   3.36438  -1.63617 )

### MATRIZES ESPECIAIS 

* **Matriz de zeros **

Matriz no qual todos os elementos são zeros. Sintaxe:
```julia
zeros(linhas, colunas)
```

In [184]:
Me = zeros(3,4)

3x4 Array{Float64,2}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

* ** Matriz de uns **

Matriz no qual todos os elementos são "uns". Sintaxe:
```julia
ones(linhas, colunas)
```

In [185]:
Me = ones(3,4)

3x4 Array{Float64,2}:
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0

* ** Matriz identidade **

Matriz quadrada no qual todos os elementos da diagnoa principal são "1" e os demais "0". Sintaxe:
```julia
eye(linhas)
```

In [186]:
Mf = eye(3)

3x3 Array{Float64,2}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

* ** Matriz identidade na forma $ I = M*inv(M)$. **

O resultado apresenta valores proximos de zero para os numeros fora da diagonal principal

In [187]:
Mx = [0.91   0.43   0.41; 0.45   0.03   0.83; 0.85   0.55   0.10]

Mx*inv(Mx)

3x3 Array{Float64,2}:
  1.0           1.33227e-15  1.11022e-15
 -8.88178e-16   1.0          4.44089e-16
 -1.22125e-15  -1.66533e-16  1.0        

### DETERMINANTE , BASES E DIMENSÃO 

In [20]:
Mx = [0.91   0.43   0.41; 0.45   0.03   0.83; 0.87   0.55   0.10]

3×3 Array{Float64,2}:
 0.91  0.43  0.41
 0.45  0.03  0.83
 0.87  0.55  0.1 

* ** Determinante  **

In [21]:
Mx, det(Mx)

(
[0.91 0.43 0.41; 0.45 0.03 0.83; 0.87 0.55 0.1],

-0.030758000000000056)

* **Norma**

In [22]:
norm(Mx)

1.6280341355208716

* ** Redução de linhas **

In [3]:
rref(Mx)

LoadError: LoadError: MethodError: no method matching rref(::Array{Int64,2})
Closest candidates are:
  rref(!Matched::Nemo.nmod_mat) at /home/jmarcellopereira/.julia/v0.5/Nemo/src/flint/nmod_mat.jl:301
  rref(!Matched::Nemo.fmpq_mat) at /home/jmarcellopereira/.julia/v0.5/Nemo/src/flint/fmpq_mat.jl:483
  rref(!Matched::Nemo.fmpz_mat) at /home/jmarcellopereira/.julia/v0.5/Nemo/src/flint/fmpz_mat.jl:870
  ...
while loading In[3], in expression starting on line 1

* ** Base **

* ** Rank de uma matriz **

In [5]:
rank(Mx), Mx

(3,
[0.91 0.43 0.41; 0.45 0.03 0.83; 0.87 0.55 0.1])

* ** Dimensão **

In [192]:
ndims(Mx), Mx

(2,
3x3 Array{Float64,2}:
 0.91  0.43  0.41
 0.45  0.03  0.83
 0.87  0.55  0.1 )

### DECOMPOSIÇÃO VETORIAL DE MATRIZES

#### DECOMPOSIÇAO LU 

Encontra a decomposição LU na forma $p  a = L  U$, no qual:
* L - triangular inferior,
* U - triangular superior,
* p - matriz de permutação.

    *A matriz "a" não necessita ser quadrada.

In [7]:
L,U,p = lu(Mx)

display(L)
display(U)
display(p)

3×3 Array{Float64,2}:
 1.0        0.0       0.0
 0.494505   1.0       0.0
 0.956044  -0.760529  1.0

3×3 Array{Float64,2}:
 0.91   0.43      0.41    
 0.0   -0.182637  0.627253
 0.0    0.0       0.185066

3-element Array{Int32,1}:
 1
 2
 3

## SISTEMAS LINEARES

Dado um sistema de equações lineares, formado pela matriz A matriz dos coeficientes do sistema ou matriz do sistema, vetor b dos coeficientes do sistema, e x vetor das incógnitas. Temos que:
![](sistema_matricial.png)


$$A\cdot x = b $$ 
$$x = A \setminus b$$

In [7]:
# criando duas matrizes aleatórias

A = rand(3,3) # matriz das coeficientes
B = rand(3,1) # vetor dos termos independentes

display(A)
display(B)

3×3 Array{Float64,2}:
 0.361597  0.985671  0.239431
 0.215711  0.999347  0.948109
 0.58168   0.973782  0.893004

3×1 Array{Float64,2}:
 0.539096
 0.965195
 0.531188

In [8]:
# X1,X2,X3: solução dos sistema

x = A\B

3×1 Array{Float64,2}:
 -1.07158 
  0.85157 
  0.364233

** O poder de cálculo JULIA na manipulação de matrizes**

Vamos calcular um sistema linear de 5000 equações e 5000 variáveis. ATENÇÃO!!! Ao definir matrizes grandes, atente ao tamanho da memória ram do computador, pois dependendo do tamanho pode ser consumida toda a ram e toda a memória virtual (swap) e travar a máquina

In [11]:
A = rand(5000,5000)
B = rand(5000,1);

In [12]:
@elapsed x = A\B

2.123256429

In [198]:
typeof(x)

Array{Float64,2}

In [199]:
#Qual o resultado de x2 e de x4999?

x[2], x[4999]

(1.6645174523518325,-2.742295611847515)

## AUTOVALORES E AUTOVETORES


### AUTOVALORES

Em álgebra linear, um escalar λ é valor próprio (ou autovalor) de um operador linear ${\displaystyle A:V\rightarrow V} $ se existir um vector x diferente de zero tal que ${\displaystyle A{\mathbf {x}}=\lambda {\mathbf {x}}}$. O vector x é chamado vector próprio.

Os autovalores de uma dada matriz quadrada A de dimensão ${\displaystyle n\times n}$ são os n números que resumem as propriedades essenciais daquela matriz. O autovalor de A é um número λ tal que, se for subtraído de cada entrada na diagonal de A, converte A numa matriz singular(ou não-invertível). Subtrair um escalar λ de cada entrada na diagonal de A é o mesmo que subtrair λ vezes a matriz identidade I de A. Portanto, λ é um autovalor se, e somente se, a matriz $   {\displaystyle (A-\lambda I)} $ for singular. Wikipedia.

### AUTOVETORES

Em Álgebra linear, um autovetor ou vetor próprio representa uma direção que é preservada por uma transformação linear. Mais precisamente, seja V um espaço vectorial sobre um corpo F, e A: V→ V uma transformação linear. v é um autovetor quando v não é o vector nulo e existe um escalar ${\displaystyle \lambda } $ tal que

$ {\displaystyle A\ v=\lambda \ v\,} $.

Nesse caso, dizemos também que ${\displaystyle \lambda \,}$ é um autovalor ou valor próprio. v é chamado de autovetor associado ao autovalor ${\displaystyle \lambda \,} $. Wikipedia.

%%% Fim Algebra linear %%%